### ISSUE TITLE
Example responses

### ISSUE THREAD

**Issue by NovaGL** [coldfire84/node-red-alexa-home-skill-v3-web#10]
Can you give some examples of responses, I would imagine the v2 responses don't work

eg
````
msg.extra = {
    "temperatureReading": {
        "value": 21.11
    },
    "applianceResponseTimestamp": new Date().toISOString()
};
msg.acknowledge= true;
return msg; 
````

You have an example for state but not response.
Also you have a typo "msg.acknowledge **tp** be either true or false."

````
msg {
    acknowledge: true,
    payload {
        state { 
            "power": ON/ OFF,
            "brightness": 0-100,
            "colorHue": 0-360,
            "colorSaturation": 0-1,
            "colorTemperature": 0-10000, 
            "input": string,
            "lock": LOCKED/ UNLOCKED,
            "playback": playback,
            "thermostatMode": HEAT/ COOL,
            "thermostatSetPoint" : temp in celsius or farenheit
        }
    }
}
````

**Comment by coldfire84** [comment]
I started [this](https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/wiki/Example-Flows#default-node-outputs) a while back, and will look to update/ populate for all capabilities.

For reference, I dropped "msg.extra" in this version of the API, but feedback the specifics of the command in the payload, or within the device state element stored in the DB that is passed to Alexa Report State API directly.

**Comment by NovaGL** [comment]
Thanks, as I don't how to respond to current temperature.

**Comment by coldfire84** [comment]
Hopefully [these example outputs](https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/wiki/Example-Flows-and-Node-Outputs#default-node-outputs) give you what you need.

**Comment by NovaGL** [comment]
Updates look good. Still can't figure out why my thermostat doesn't update and has wrong info when I ask get temperature.

Only think I can think of is that my msg.state is wrong.

**Comment by coldfire84** [comment]
In #9 I have included an example Thermostat.

**Comment by NovaGL** [comment]
Thanks I'm struggling with the code. The rest works

**Comment by coldfire84** [comment]
Can you share the flow/ code? Happy to help.
