### ISSUE TITLE
Mqtt timeout

### ISSUE THREAD

**Issue by tomtom30** [coldfire84/node-red-alexa-home-skill-v3-web#102]
**Describe the bug**
When I trigger a command I Have an MQTT timeout

`alexa_alexav3-web.1.946ddhrq63pv@docker3    | debug: [Alexa API] Received command for user: thomas, command: {"directive":{"header":{"namespace":"Alexa.PowerController","name":"TurnOn","payloadVersion":"3","messageId":"8f507ecd-3324-41ae-b8a0-2a9e5eb9fb7e","correlationToken":"AAAAAAAAAQDBswNzql97tJZpR6uVtF2TDAIAAAAAAAA/me/P2sZG+eJzhy8I+Xib+ChcNPUW1r46jFJGvnmTsCXjIHfIQJNNTsWu3NPPWTLn+ABlOeA=="},"endpoint":{"scope":{"type":"BearerToken","token":"szd9rgBlGF5uZ6WpNsRj68EqnAO9EkqJOCaLo5r01k7zAaG1TpH8p3Sf8aic"},"endpointId":"4","cookie":{}},"payload":{}}} {"timestamp":"2020-02-11T20:33:05.402Z"}
alexa_alexav3-web.1.946ddhrq63pv@docker3    | debug: [Alexa Command] Received command API request for user: thomas command: {"directive":{"header":{"namespace":"Alexa.PowerController","name":"TurnOn","payloadVersion":"3","messageId":"8f507ecd-3324-41ae-b8a0-2a9e5eb9fb7e"},"endpoint":{"scope":{"type":"BearerToken"},"endpointId":"4","cookie":{}},"payload":{}}} {"timestamp":"2020-02-11T20:33:05.407Z"}
alexa_alexav3-web.1.946ddhrq63pv@docker3    | info: [Alexa Command] Published MQTT command for user: thomas topic: command/thomas/4 {"timestamp":"2020-02-11T20:33:05.407Z"}
alexa_alexav3-web.1.946ddhrq63pv@docker3    | verbose: 10.0.0.2 - - [11/Feb/2020:20:33:07 +0000] "POST /api/v1/command2 HTTP/1.1" - - "-" "-"
alexa_alexav3-web.1.946ddhrq63pv@docker3    |  {"timestamp":"2020-02-11T20:33:07.366Z"}
alexa_alexav3-web.1.946ddhrq63pv@docker3    | warn: [MQTT] Sent Alexa time-out response for user: thomas, message: 8f507ecd-3324-41ae-b8a0-2a9e5eb9fb7e {"timestamp":"2020-02-11T20:33:07.446Z"}`

**To Reproduce**
Calling "serveur de film" to start

**Log Output**
In Nodered my connection to Mqtt is ok and alexaweb too.

**Environment (please complete the following information):**
 - Node-RED node version: 0.4.66
 - Node-RED version: v0.20.8

**Additional context**
`11 Feb 21:38:19 - [info] [alexa-remote-account:Alexa Bureau] intialising "Alexa Bureau" with the PROXY method and saved data...
11 Feb 21:38:20 - [info] [alexa-smart-home-v3-conf:c8c058cb.0d3648] Successfully connected to Alexa/ Google Home Skill MQTT server: mqtt.mydomain.nf, account username: thomas
`

It said me "device not responding" because of that.

Can you help me?
thanks

**Comment by coldfire84** [comment]
This looks like you're using your own instance/ deployment rather than the hosted service? 

You need to use the mosquitto_sub command (in the docs, but modify hostname for your MQTT server/ deployment) to try and show that connectivity to your MQTT server is working. I'm guessing it will fail, and this is your issue.

You can subscribe, using your "thomas" account to '#' and see all traffic hitting the service. Test this from your Node-RED server.

**Comment by coldfire84** [comment]
In case you are unaware, you do not need to use your own instance, the service is available/ free to use via https://red.cb-net.co.uk.

**Comment by tomtom30** [comment]
yes sorry I forgot. yes I am on self hosted.
I can connect with mosquitto_sub, here is the payload for command/thomas/4 : 
`{"directive":{"header":{"namespace":"Alexa.PowerController","name":"TurnOn","payloadVersion":"3","messageId":"2d13e21f-173c-44a1-8565-8a1189952693"},"endpoint":{"scope":{"type":"BearerToken"},"endpointId":"4","cookie":{}},"payload":{}}}`

It seems to be ok?
I don't understand why it answered timeout.

**Comment by tomtom30** [comment]
Ok after investigations, the topic "command/thomas/4" was not available for thomas but only for mqtt superuser. I don't know why.
I deleted all my devices and topics, and after recreate it works.
