### ISSUE TITLE
Contact Sensor doesn't trigger routines

### ISSUE THREAD

**Issue by sibandrew** [coldfire84/node-red-alexa-home-skill-v3-web#104]
Hi!

My system works very well, so i can see contact sensors state changes when the alexa app is opened, but when it change, **my routine is not triggered**.

When my contact state change, i can see an error in the red docker logs:
```
error: [AlexaAuth] No Alexa Grant Code for user: myUser {"timestamp":"2020-02-15T06:45:59.623Z"}
```

In the code, i see this comment: `// User needs to un-link/ re-link Amazon account, no grant code`, so i tried to re-link the account, but this has no solved the issue.
I think the problem is that my bridge doesn't send changeReport to the Alexa because it can't get an access token.

Do you have any idea about this problem?
Thank you in advance.

----------------------------
I also have another issue which can be related to the one above.
When i create a new routine in the Alexa app, i can't see the thermostat temperature sensor in the list of possible trigger for that routine.

**Comment by coldfire84** [comment]
Is this still an issue, or were you able to resolve?

**Comment by sibandrew** [comment]
No, I resolved. Thank you.

**Comment by miaszh** [comment]
How did you do it?
