### ISSUE TITLE
GrantCode not saved in mongodb

### ISSUE THREAD

**Issue by Fab0020** [coldfire84/node-red-alexa-home-skill-v3-web#107]
Hi, I'am using this code and it's work great, the only problem that i've found is into the routes / alexa.js files: the '/ authorization' page used for saving the grant code of a user is never called. And all the users i've created haven't a grant code. Where should i put a redirect to that link?

**Comment by coldfire84** [comment]
Apologies, I missed the original Issue being opened, did you resolve this?

**Comment by Fab0020** [comment]
Yes thanks, there was a flag disabled on the alexa developer console and this caused the problem.

-----------------------------------------------------------------------------------------------------
       Fabio Del Carlo
-----------------------------------------------------------------------------------------------------



Da: coldfire84<mailto:notifications@github.com>
Inviato: lunedì 2 marzo 2020 19:07
A: coldfire84/node-red-alexa-home-skill-v3-web<mailto:node-red-alexa-home-skill-v3-web@noreply.github.com>
Cc: Fab0020<mailto:fabio0020@hotmail.it>; State change<mailto:state_change@noreply.github.com>
Oggetto: Re: [coldfire84/node-red-alexa-home-skill-v3-web] GrantCode not saved in mongodb (#107)


Apologies, I missed the original Issue being opened, did you resolve this?
