### ISSUE TITLE
alexa smart home v3 state - persistent context - circular reference error

### ISSUE THREAD

**Issue by nilsbernhar** [coldfire84/node-red-alexa-home-skill-v3-web#109]
Hey,

First off, thank you very much for the great skill. I am just upgrading to version 3 (forked by coldfire84) and really like it!

However, I just discovered a small problem with persistent context and the "state" node.

When setting all "context storage" to "localfilesystem"
`contextStorage: {
        default    : { module: "localfilesystem"},
        storeInFile: { module: "localfilesystem"},
        memoryOnly : { module: "memory" }
    },`
, I get a recurring warning:
`17 Apr 18:44:26 - [info] [alexa-smart-home-v3-conf:c5fdbcbe.b18888] Successfully connected to Alexa/ Google Home Skill MQTT server: mq-red.cb-net.co.uk, account username: ---`
`17 Apr 18:45:56 - [warn] Context 51db8b1d.fc8c5c:cf8836e9.9e651 contains a circular reference that cannot be persisted`

Setting the default storage to memory solves the warning. Additionally, disabling the "alexa smart home v3 state" node also solves the warning. The normal "alexa smart home v3" output node does not seem to be affected.

I require persistent context and would prefer to store all data in the local file system. It would be amazing if you could help achieve this.

Thanks so much in advance,
Nils

**Environment (please complete the following information):**
 - Node-RED node version: v0.4.66
 - Node-RED version: v1.0.5

**Comment by coldfire84** [comment]
This issue is now resolved with node-red-contrib-alexa-smart-home version 0.4.67 onwards, which provides an option on the config node to select a context store by name.
