### ISSUE TITLE
Alexa Skill: French fr-FR Translation

### ISSUE THREAD

**Issue by coldfire84** [coldfire84/node-red-alexa-home-skill-v3-web#11]
Required for Alexa skill enablement in French-speaking markets.

If you can help please let me know!

Translation required:

| Skill Text | English Text | 
| ----|----|
|Public Name | Node-RED Smart Home Control |
|One Sentence Description| Add Alexa voice control to your Smart Home Node-RED Flows|
| Detailed Description| Using this bridge you can control a variety of Node-RED endpoints, such as MQTT, HTTP(S), Yamaha AVRs, Chromecast (anything that has a Node-RED integration). This bridge currently supports Power, Brightness, Colour, Colour Temperature, Input, Lock, Thermostat, Playback, Step Speaker and Scene control. You'll need to follow the instructions here to get up and running: https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/wiki/Use-the-Hosted-Instance|
|Example Phrase 1| Alexa, turn on the lights|
|Example Phrase 2| Alexa, pause Lounge TV|
|Example Phrase 3| Alexa, set AV Receiver to HDMI 2|

**Comment by nwaelti** [comment]
Hi there,
If french translation is still required, I'll be glad to help, I'm a french native...
Let me know...

**Comment by non092** [comment]
Please find below my French translation, looking forward to test this skill to replace v2 from Hardillb.

Skill Text | English Text | French Text
-- | -- | --
Public Name | Node-RED Smart Home Control | Node-RED Contrôle de la maison connectée
One Sentence Description | Add Alexa voice control to your Smart Home Node-RED Flows | Ajoute la commande vocale Alexa à vos flux Node-RED
Detailed Description | Using this bridge you can control a variety of Node-RED endpoints, such as MQTT, HTTP(S), Yamaha AVRs, Chromecast (anything that has a Node-RED integration). This bridge currently supports Power, Brightness, Colour, Colour Temperature, Input, Lock, Thermostat, Playback, Step Speaker and Scene control. You'll need to follow the instructions here to get up and running: https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/wiki/Use-the-Hosted-Instance | En utilisant cette passerelle, vous pouvez contrôler une variété de terminaux Node-RED, tels que MQTT, HTTP(S), Yamaha AVRs, Chromecast (tout ce qui a une intégration Node-RED). Ce pont prend actuellement en charge l'alimentation, la luminosité, la couleur, la température de couleur, l'entrée, le verrouillage, le thermostat, la lecture, les hauts-parleurs et le contrôle de scène. Vous devez suivre les instructions ici pour commencer à utiliser ce skill : https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/wiki/Use-the-Hosted-Instance
Example Phrase 1 | Alexa, turn on the lights | Alexa, allume les lumiéres
Example Phrase 2 | Alexa, pause Lounge TV | Alexa, mets la télévision du salon en pause
Example Phrase 3 | Alexa, set AV Receiver to HDMI 2 | Alexa, mets le récepteur AV sur HDMI 2

**Comment by coldfire84** [comment]
Thanks for sharing this, I have submitted the fr-FR and fr-CA skill to Amazon for review.

**Comment by coldfire84** [comment]
fr-FR and fr-CA skill has been approved and should be live in the Alexa Skills library. This resolves #11 and #12.

Thanks for your help @non092
