### ISSUE TITLE
Help wanted: Alexa Temperatur-Sensor Flow

### ISSUE THREAD

**Issue by superpower10** [coldfire84/node-red-alexa-home-skill-v3-web#111]
I am looking for a Temperatur-Sensor Example Flow. Sadly there is none on this website: https://docs.cb-net.co.uk/en/development/example-flows.html

I tried it myself but I couldn't get it work.

Could somebody please help me?

Thank you very much

**Comment by emme73** [comment]
![image](https://user-images.githubusercontent.com/26736389/80351572-e05c0e00-8872-11ea-9a21-f7163bbc96fb.png)
This is mine temp flow... I get the value from zigbee and push it to Alexa.
the function contains a value adjustment (decondz sends it without decimals)

the function contains:
```
return {
    acknowledge: true,
    payload : {
        state : {
            temperature: msg.payload/100
        }
    }
};
```
