### ISSUE TITLE
warn on console in a persistent context enviroment

### ISSUE THREAD

**Issue by emme73** [coldfire84/node-red-alexa-home-skill-v3-web#112]
I'm not really sure this is the right place where to write this...
But I'm experiencing an annoying issue with the state nodes.

I'm running NodeRed with persistent context and on each state node I get this warning in the debug window:
Context xxxxxxxx.xxxxxxxx:xxxxxxxxx.xxxxxx contains a circular reference that cannot be persisted.

If I remove the persistent context the warning does not appear anymore.
this seems to affect only the state nodes
thanks

**Comment by coldfire84** [comment]
Have you set the correct Context Store in the [configuration node](https://docs.cb-net.co.uk/en/development/getting-started.html#node-red-configuration)? The version released 4 days ago enables this.

**Comment by emme73** [comment]
uh... I'm running 0.4.66 with no upgrades available... but in the configuration node I do not have the context config option
![image](https://user-images.githubusercontent.com/26736389/80359042-93316980-887d-11ea-850e-3cbc9b3564dc.png)
![image](https://user-images.githubusercontent.com/26736389/80359210-caa01600-887d-11ea-8c2e-60453c83d63d.png)

**Comment by coldfire84** [comment]
There is a lag on the pallet, you can update using npm command below, or just wait:
```npm update node-red-contrib-alexa-smart-home```

**Comment by emme73** [comment]
Manual upgrade made the trick

Thanks!
