### ISSUE TITLE
Wrong password with user creation

### ISSUE THREAD

**Issue by tomtom30** [coldfire84/node-red-alexa-home-skill-v3-web#114]
Hi,
I have a recently problem with my own deploy.
When I create a user it doesn't initialise the both passwords with PBKDF2 hash

Here is a log of my mongodb user just after creation:

`{"_id":{"$oid":"5eb830e5715cf1001335fdfa"},"mqttPass":"e4e7d4efaf3f203ec50ed34aaabd8d44","superuser":false,"activeServices":[],"active":true,"isVerified":true,"attempts":{"$numberInt":"0"},"username":"test1","email":"test@dqs.fr","country":"FR","region":"Europe","password":"e4e7d4efaf3f203ec50ed34aaabd8d44","created":{"$date":{"$numberLong":"1589129445578"}},"last":{"$date":{"$numberLong":"1589130008085"}},"salt":"m/FN/0n6Ucl4vW2I","hash":"sCzTc3gGufmZHdbRPOnh9DlIqwSKvsNQ","__v":{"$numberInt":"0"}}`

 - Node-RED node version: 0.4.66
 - Node-RED version: 1.0.6
I am in docker with the last web image version ( yesterday old ).

To make it correct I need to manually change the password to get a right hash.

In my mind , my second problem ( device do not respond ) is due to this.
My "test1" user can't subscribe or publish in MQTT.

If someone can helps 
Thanks

**Comment by coldfire84** [comment]
This is by design, there is email verification built into the account creation workflow, when this is completed the passwords are synchronised. 

This was introduced to enable service changes in future (to advise consumers of any potential changes they would need to make such as hostnames used for MQTT etc): without the verification contacting users is virtually impossible.

**Comment by tomtom30** [comment]
Ok, I understand.
I changed "isverified" entry to true manually in mongodb to win time....
Not a good idea.
Thanks for your time

**Comment by coldfire84** [comment]
> Not a good idea.

I don't understand why you can't verify the user account via the email workflow?
