### ISSUE TITLE
Blinds/Rollershutter miss a stop / halt command

### ISSUE THREAD

**Issue by tsdogs** [coldfire84/node-red-alexa-home-skill-v3-web#115]
I haven't found a way to make my shutters stop with Alexa control.

Basically I can control my shutters with only 3 commands.
Up / Down / Stop (or Close / Open / Halt if preferred).
I have successfully binded all the commands to mqtt and control them via Home Assistant.

It seems to be Alexa missing the functionality but maybe allowing the user to add personalized presets in the range control could solve the problem or at least add a halt / stop preset like medium, low, high.

**Comment by coldfire84** [comment]
The RangeController interface is setup as outlined here: https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-rangecontroller.html#discover-blinds

It doesn't look like there is a stop/ halt command available, may be worth testing with a custom device with custom a combination of capabilities.

You can use numerical values 1-100, so could group/ set any of these individually to represent specific presets in Node-RED/ that are used in your MQTT commands.
