### ISSUE TITLE
open/close command not working with blinds

### ISSUE THREAD

**Issue by quadhammer** [coldfire84/node-red-alexa-home-skill-v3-web#117]
Nothing is recorded in the node red full debug if I use open or close as the command.  If I say, set curtains to 30%, I get a payload of 30, and all is good.

The thing is, I picked the wrong device on start-up, a light, or plug, that didn't have 'range'.  If I make a new device with a different name, then the open and close works, but I want 'curtains' to be my device name, and no matter what I try: forgetting devices, making a new account, forgetting tokens, changing passwords, deleting the server in node red, changing device types back and forth...nothing seemed to fix the missing open and close command.

Node-RED
Current version: 6.2.0 
Home Assistant Community Add-on: Node-RED

Thank you for looking.

**Comment by scrhall** [comment]
I have a similar problem.
this solve my problem:

1. Delete the device on alexa
2. Delete in the service, 
3. Recreate
4. Discover again on Alexa

open/close are working now

**Comment by coldfire84** [comment]
@quadhammer , did the above solution work for you? 

I can echo similar anomalies from working with the API, typically adding devices that are blinds and waiting 24h resolves these issues (i.e. commands such as raise/ lower not working).

**Comment by coldfire84** [comment]
Please re-open if this is still an issue.
