### ISSUE TITLE
report status rangeController

### ISSUE THREAD

**Issue by scrhall** [coldfire84/node-red-alexa-home-skill-v3-web#119]
I wat to report status change of my blinds, with rangeController.

The voice commands works well , but when I ask for the position to alexa, always says 5%
and in the app show always 5% 
How can I update the value?

**Comment by coldfire84** [comment]
Do you have a state node setup/ are you sending state for the device in question?

**Comment by dominikoyen** [comment]
I have the same Problem. I try to combine a simple light with on/off change this to true/false. This works fine. But when i change the status of the light directly with my CCU the new status will not transmitted to Google Home during the flows. The message payload says at the output of the CCU isn"OFF" and "ON". But also: "Kücheninsel state node: msg.payload missing state element!"

What is my mistake?

Greets

**Comment by coldfire84** [comment]
I don't have enough information to resolve this, you're welcome to joint he Slack workspace and we can discuss there.
Link: https://join.slack.com/t/cb-net/shared_invite/zt-b6dilewh-YN_2Ae_6WNnox5MTKHTv4w

**Comment by bsteimer** [comment]
Hey guys, I had the same problem with my blinds aka rangeController, that the alexa app always showed 5% although the update was carried out in node red. 
So what I did, as I initially wanted all states to be synchronous throughout all systems. I write the update from my source system to alexa every time the state changes. This has the nice side effect that now even the acknowledgement does not work as expected the outcome in the alexa app is what I wanted to have. Just if anyone has similar problems.
