### ISSUE TITLE
Alexa Skill: French (Canada) fr-CA Translation

### ISSUE THREAD

**Issue by coldfire84** [coldfire84/node-red-alexa-home-skill-v3-web#12]
Required for Alexa skill enablement in Canadian French-speaking markets.

If you can help please let me know!

Translation required:

| Skill Text | English Text | 
| ----|----|
|Public Name | Node-RED Smart Home Control |
|One Sentence Description| Add Alexa voice control to your Smart Home Node-RED Flows|
| Detailed Description| Using this bridge you can control a variety of Node-RED endpoints, such as MQTT, HTTP(S), Yamaha AVRs, Chromecast (anything that has a Node-RED integration). This bridge currently supports Power, Brightness, Colour, Colour Temperature, Input, Lock, Thermostat, Playback, Step Speaker and Scene control. You'll need to follow the instructions here to get up and running: https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/wiki/Use-the-Hosted-Instance|
|Example Phrase 1| Alexa, turn on the lights|
|Example Phrase 2| Alexa, pause Lounge TV|
|Example Phrase 3| Alexa, set AV Receiver to HDMI 2|

**Comment by NorthernMan54** [comment]
How about this?

https://github.com/NorthernMan54/alexaAwsBackend/blob/master/skillPublish/skill_publish_text.md

We should talk on Slack as I'm also using a derivative of this codebase

**Comment by coldfire84** [comment]
@NorthernMan54 thanks, will have a look through. Happy to talk on slack, just finishing off the Google Assistant extension for the bridge, will be in touch when this is done.

**Comment by coldfire84** [comment]
fr-CA skill live as of 29/08/19.
