### ISSUE TITLE
Devices not showing up in Node-RED

### ISSUE THREAD

**Issue by jarlave** [coldfire84/node-red-alexa-home-skill-v3-web#120]
**Describe the bug**
After adding devices to my account, linking to Alexa (Devices show up here), I tried to also get the devices in node-red. Sadly I only get returned data: undefined.
Tried multiple times to delete token and relink again, nothing works.
I run the news docker nodered/node-red:latest-12 image

**To Reproduce**
Just normal install like the documentation says

**Expected behavior**
Devices to show up in node-red

**Log Output**
```
[info] [alexa-smart-home-v3-conf:60df77ec.51f698] Connecting to Alexa/ Google Home Skill MQTT server: mq-red.cb-net.co.uk, account username: ********
Error: getDevices status code: 401
Error: getDevices returned data: undefined
[alexa-smart-home-v3-conf:60df77ec.51f698] Successfully connected to Alexa/ Google Home Skill MQTT server: mq-red.cb-net.co.uk, account username: ********
```

this is all, nothing more comes up, only the two erros are showing up again when I pres the reload button to get the devices

**Environment (please complete the following information):**
 - Node-RED node version: 12.16.3 
   (getting the same issue with docker latest/latest-10 with version 10.20.1)

 - Node-RED version: 1.0.6

**Comment by coldfire84** [comment]
Are you able to browse to: https://red.cb-net.co.uk/api/v1/devices ?

Enter your skill username and password to authenticate, this performs the same call that Node-RED and Alexa perform to get devices.

**Comment by jarlave** [comment]
I can open this site and the login promt is coming up, but I can not log in.

//Edit: I changed my password, which had lot of symbols ```{A[+nP:EZUnM()`*fc;G3Q$p=)J`8:KJ``` (old password now, so I don't care if public) to something with less symbols, now I can sign in

Looks like it doesn't like all of them, but the site allows it, and it works with the site.

**Comment by coldfire84** [comment]
Interesting ref the password, I'll look at any limitations of the current hashing algorithm.

With the new password does Node-RED work?

**Comment by jarlave** [comment]
Yes, with the new password it also works in node-red

**Comment by coldfire84** [comment]
Does this mean you're now able to link accounts/ control devices via Alexa?

**Comment by jarlave** [comment]
Needed to add everything first to check and yes, everything works. Finally I could make the switch!
