### ISSUE TITLE
Identify the device the command came from

### ISSUE THREAD

**Issue by Kallb123** [coldfire84/node-red-alexa-home-skill-v3-web#122]
It would be ideal if the message from an input node would contain an identifier for the device where the command originated.

When speaking directly to an Alexa device, the message that gets passed into the node red flow should contain a unique identifier for the device. This would allow us to issue commands back to the device (such as speech).

**Comment by coldfire84** [comment]
IIRC the Alexa Smart Home API (which the skill is built upon) doesn't include the ability to do this.

**Comment by coldfire84** [comment]
Have been through the Smart Home API documentation again and confirmed this still looks to be unsupported.
