### ISSUE TITLE
Verification mall not received 

### ISSUE THREAD

**Issue by deon-dup** [coldfire84/node-red-alexa-home-skill-v3-web#124]
Hi

I want to try out your software. i have registerd user my id deondup18, retried several times to get verification mail, but alas nothing. I have checked my junk folders, again no mail received. Can you assist please?

**Comment by coldfire84** [comment]
I've run some tests today after fixing an intermittent DB issue, and have had numerous Account Verification emails send without issue. 

Can you confirm if this is resolved?

**Comment by deon-dup** [comment]
Yes it has been resolved, thanks

(personal contact detail removed)
