### ISSUE TITLE
Alexa Skill: Italian it-IT Translation

### ISSUE THREAD

**Issue by coldfire84** [coldfire84/node-red-alexa-home-skill-v3-web#13]
Required for Alexa skill enablement in Italian-speaking markets.

If you can help please let me know!

Translation required:

| Skill Text | English Text | 
| ----|----|
|Public Name | Node-RED Smart Home Control |
|One Sentence Description| Add Alexa voice control to your Smart Home Node-RED Flows|
| Detailed Description| Using this bridge you can control a variety of Node-RED endpoints, such as MQTT, HTTP(S), Yamaha AVRs, Chromecast (anything that has a Node-RED integration). This bridge currently supports Power, Brightness, Colour, Colour Temperature, Input, Lock, Thermostat, Playback, Step Speaker and Scene control. You'll need to follow the instructions here to get up and running: https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/wiki/Use-the-Hosted-Instance|
|Example Phrase 1| Alexa, turn on the lights|
|Example Phrase 2| Alexa, pause Lounge TV|
|Example Phrase 3| Alexa, set AV Receiver to HDMI 2|

**Comment by montaofficial** [comment]
Here it is! 👍

Node-RED Smart Home Control    =>   Node-RED Controllo Domotica

Add Alexa voice control to your Smart Home Node-RED Flows
=>
Aggiungi il controllo vocale di Alexa ai tuoi Flow per la Domotica in Node-RED

Using this bridge you can control a variety of Node-RED endpoints...
=>
Usando questo bridge puoi controllare diversi enpoint, come MQTT, HTTP(S), Yamaha AVRs, Chromecast (qualsiasi dispositivo che sia stato integrato in Node-RED). Questo bridge supporta attualmente Attivazione, Luminosità, Colore, Temperatura Colore, Ingressi, Serrature Smart, Termostati, Controlli di Riproduzione, Altoparlanti e gestione delle Scene. Segui qui le istruzioni per la configurazione:
https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/wiki/Use-the-Hosted-Instance


Frase di esempio 1: Alexa, accendi le luci

Frase di esempio 2: Alexa, metti in pausa TV Salotto

Frase di esempio 3: Alexa, imposta l'ingresso del Ricevitore AV su HDMI 2

**Comment by coldfire84** [comment]
@montaofficial - thank you, much appreciated.

I have updated the Alexa Skill with Italian language as above 👍

**Comment by coldfire84** [comment]
@montaofficial are you able to assist with this translation for Google Home extension? https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/issues/47

Thanks!
