### ISSUE TITLE
Own Deployed - No error but can't link account neither with Google nor Alexa

### ISSUE THREAD

**Issue by rockstar2020** [coldfire84/node-red-alexa-home-skill-v3-web#131]
Hi @coldfire84,
First of all thanks a lot for this wonderful work!

I have successfully managed to install and run your code on AWS's Ubuntu server.
I can login to the webapp and create users/services with no issues.
but I can't perform Account Linking neither in Google nor Alexa.
The strange part is that Oauth2 is authenticated with no issues but nothing happens after I authenticate on the webapp.
There's no error log on "red" container!
Any hint where I should look for the root cause?
Is your latest app version (red) still 0.11?

Many thanks in advance

**Comment by coldfire84** [comment]
Apologies I have missed this, this type of issue needs to go to the Slack workspace, here: https://join.slack.com/t/cb-net/shared_invite/zt-b6dilewh-YN_2Ae_6WNnox5MTKHTv4w
