### ISSUE TITLE
Devices discovered in Alexa, but not getting listed in node-red node

### ISSUE THREAD

**Issue by sameeraakbar** [coldfire84/node-red-alexa-home-skill-v3-web#132]
Hi !

The new capabilities like playback control sound very promising, I want to test them. But the devices are not getting listed in the node-red. What am I missing? I am attaching screengrab of the web-app as well as node-red
![webapp](https://user-images.githubusercontent.com/16999630/95058070-a2fa8700-0714-11eb-82e8-bb692e05ab15.JPG)
![Capture](https://user-images.githubusercontent.com/16999630/95058325-fd93e300-0714-11eb-8afe-95c20f9588fe.JPG)

**Comment by coldfire84** [comment]
Apologies for the delay on this, the Slack workspace can be used for general help (best endeavors), GitHub is used for feature requests, code-issues etc.

You can join the Slack workspace here: https://join.slack.com/t/cb-net/shared_invite/zt-b6dilewh-YN_2Ae_6WNnox5MTKHTv4w
