### ISSUE TITLE
Google Home Devices do not appear in "My Devices"

### ISSUE THREAD

**Issue by hepcat72** [coldfire84/node-red-alexa-home-skill-v3-web#133]
**Describe the bug**

Maybe I don't understand what this service is supposed to do, but I have a few devices set up in my google home app on my iPhone. When I created an account on `https://red.cb-net.co.uk/` and linked it to google home, I had expected my google home devices to appear under `https://red.cb-net.co.uk/devices` so that their state changes could be sent to Node RED, but none of my devices setup in google home appear there.  I can manually add devices and those show up in Node RED, but they are completely disconnected from the actual devices in google home...  Am I understanding what this service is supposed to do or is there some sort of problem that needs to be addressed here?

**To Reproduce**

In a browser...

1. Create an account via https://red.cb-net.co.uk/new-user
2. Click the verification link you receive in your email

In the googlehome app...

1. tap the "+" at the top left
2. Tap add a device
3. tap "Have something already set up?"
4. Tap the magnifying glass
5. Enter "node red"
6. Tap "Node RED Smart Home Control"

Enter your red.cb-net.co.uk login credentials and tap "Authorise" [sic]

Go to: https://red.cb-net.co.uk/devices

...and observe that none of your google home devices are listed there.

Nor are they listed in the node RED node (though manually added devices do appear in the Node RED node device list).

**Expected behavior**

I thought my google home devices would automatically populate so I could receive events from them (e.g. I turned on/off)...

**Log Output**

No errors.

**Environment (please complete the following information):**
 - Node-RED node version: no problems with node red
 - Node-RED version: no problems with node red

**Additional context**

My intent is to receive wattage threshold events from a "Currant" outlet that shows up in the google home app, but I have a few other chrome cast devices that I also expected would appear.

**Comment by coldfire84** [comment]
Hi @hepcat72 , the sync works the other way/ I don't think the service will address your use case.

Let's say you have a [zigbee2mqtt ](https://www.zigbee2mqtt.io/)connected device, or a [Tasmota ](https://tasmota.github.io/docs/)Wi-Fi connected device --> neither of these fully/ natively support Alexa or Google Home connectivity, this service acts as a 'bridge' between these devices and Alexa/ Google Home.

A typical workflow:
1. You define devices via https://red.cb-net.co.uk/devices, that represent smart devices in your home (such as those listed above).
2. [Supported devices](https://docs.cb-net.co.uk/en/development/#supported-capabilities) you define will automatically appear in Google Home/ Alexa once your link your account(s).
3. You can now use voice control (or Alexa/ Google Home app control) of these devices. Any commands will come in to Node-RED and you can use these to trigger flows/ actions, as outlined in the [docs](https://docs.cb-net.co.uk/en/development/example-flows.html#example-flows).

I hope that is clearer... if not happy to chat through on our Slack workspace.

**Comment by hepcat72** [comment]
That is clear, thanks.  I will close this issue.  You don't happen to know of an alternate means of getting status updates *from* a google home device, do you?
