### ISSUE TITLE
Cannot access the deviceId of Alexa device responding

### ISSUE THREAD

**Issue by s3frank** [coldfire84/node-red-alexa-home-skill-v3-web#135]
I apologize upfront, this is not a bug report I think...maybe feature request.
But I am trying to understand how to get a unique ID of some form that helps me to know in my flow which alexa echo dot in my house is responding. The idea being to have one Fan flow and dynamically based on the device know which fan to turn on or off.

Any help with that would be hugely appreciated.

**Comment by coldfire84** [comment]
Some devices already support room awareness, such as lights, so, assuming you have a room, with a light and assigned Echo device, you can just say "Alexa, turn off the light."

The issue you've run into is that room awareness does not extend to all devices, as-per the feature request here to extend room awareness to cover additional devices: https://alexa.uservoice.com/forums/906892-alexa-skills-developer-voice-and-vote/suggestions/41106895-context-awareness-room-awareness-for-any-device

Last time I checked, there is no information regarding the originating Echo device in any command issued, essentially Room Awareness is designed to eliminate the need for this, albeit Amazon have stopped short of what you'd expect it to offer.

**Comment by s3frank** [comment]
Thanks. If I understand the two paths for me it's:

1) commit to groups and expose my devices directly via home assistant to
alexa and use the models and groups native to alexa.
- create virtual devices via nodered for anything that's harder, flow based
- more logic ends up inside alexa this way but maybe smoother.

2) create virtual devices as lights via nodered for all so I can make
generic flows that act on the correct room based on a variable injecting
the room context. I got that working via a local alexa nodered node. But
the limitation is everything is a light basically.


-FF
