### ISSUE TITLE
Changing Colour, the brigthness go to 1.

### ISSUE THREAD

**Issue by Rapejim** [coldfire84/node-red-alexa-home-skill-v3-web#15]
![image](https://user-images.githubusercontent.com/7972545/50569981-a6125780-0d77-11e9-872c-1c0cfd866c13.png)

I'm integrating the colour control of a RGB light (Xiaomi Gateway) in NodeRED with Alexa, but when I choose a colour of list (in AlexaApp), the "msg.payload" always have the brigthness value to 1 (while hue and saturation are right).

![image](https://user-images.githubusercontent.com/7972545/50569984-e5d93f00-0d77-11e9-8468-b7a9edd797dd.png)

If I put the brigthness to 100% (in AlexaApp, the ligth response Ok) and try change color, the input node set brigthness to 1 again.

Do you need more screenshoots?

**Comment by coldfire84** [comment]
> Do you need more screenshots?

No, thank you - I think I understand the problem you have.

Interestingly, this is as per the [Alexa.ColorController](https://developer.amazon.com/docs/device-apis/alexa-colorcontroller.html) specification. What are you expecting to pass to the target device/ endpoint?

**Comment by coldfire84** [comment]
I've separated out the state data for brightness and color (there was an overlap).

The output form the node is correct (in-line with the specifications), but if you have a BrightnessController assigned to the device the brightness state will now not be changed.

**Comment by Rapejim** [comment]
Thanks for the info. 
I have readed the Alexa.ColorController specification and put this:

" Important: The brightness value of a SetColor directive will align to the customer's requested color, however, for the best customer experience when you make a color change, you should maintain the current brightness setting of the target endpoint. For example, if a bulb is set to white at 50% brightness (0.5), and a customer requests a color change to red, the SetColor directive provides hue, saturation and brightness values of 0,1,1, respectively, which indicates full brightness. In this case, you should ignore the brightness value in the directive, and maintain the current brightness setting of 0.5."

Then it isn't a bug (like you write, it's in-line with the specifications), but I did know it yesterday, xD
Now when I change Colour, I ignore the brightness value, :p

**Comment by coldfire84** [comment]
@Rapejim, on this basis are you happy to close this issue?

**Comment by Rapejim** [comment]
Off course!!

**Comment by marcdo70** [comment]
Hello, have the same problem, how did you solve it. I'm new to Node Red and need help there. Which node do I have to use and how do I set it?
What is your flow like?
Glg Marcus
