### ISSUE TITLE
"Alexa turn on aircon" - "It is in cooling mode"

### ISSUE THREAD

**Issue by logon84** [coldfire84/node-red-alexa-home-skill-v3-web#153]
**Describe the bug**
It's been 2/3 days since I am unable to start aircon telling alexa. Every time I say to her I want to start aircon, she replies it is in cooling mode. It's not that Alexa tells me my actual working mode, but it in fact switches my working mode from HEAT to COOLING.

**To Reproduce**
"Alexa turn on aircon" - "It is in cooling mode" ||| "Alexa enciende el aire" - "Está en modo enfriamiento"

**Expected behavior**
"Alexa turn on aircon" --> aircon starts operating.

**Log Output**
```
5 Jan 12:25:31 - [info] Starting flows
5 Jan 12:25:31 - [info] [alexa-smart-home-v3-conf:5803a0a7.51fa3] Node-RED contrib version: v0.4.66
5 Jan 12:25:31 - [info] [alexa-smart-home-v3-conf:5803a0a7.51fa3] Connecting to Alexa/ Google Home Skill MQTT server: mq-red.cb-net.co.uk, account username: XXXXXX
5 Jan 12:25:32 - [info] [alexa-smart-home-v3-conf:97a70534.f2dd1] Node-RED contrib version: v0.4.66
5 Jan 12:25:32 - [info] [alexa-smart-home-v3-conf:97a70534.f2dd1] Connecting to Alexa/ Google Home Skill MQTT server: mq-red.cb-net.co.uk, account username: XXXXXX
5 Jan 12:25:32 - [info] Started flows
5 Jan 12:25:32 - [info] [mqtt-broker:XXXXX mqtt server] Connected to broker: mqtt://192.168.1.1:1883
5 Jan 12:25:32 - [info] [alexa-smart-home-v3-conf:97a70534.f2dd1] Successfully connected to Alexa/ Google Home Skill MQTT server: mq-red.cb-net.co.uk, account username: XXXXXX
5 Jan 12:25:32 - [info] [alexa-smart-home-v3-conf:5803a0a7.51fa3] Successfully connected to Alexa/ Google Home Skill MQTT server: mq-red.cb-net.co.uk, account username: XXXXXX
5 Jan 12:25:33 - [info] [alexa-smart-home-v3-conf:5803a0a7.51fa3] sensor ambiental : sending state update, topic:state/strummer84/6634 message:{"messageId":"af59bf18-3675-4166-915d-b819c397f16f","payload":{"state":{"temperature":18}}}
5 Jan 12:25:33 - [info] [alexa-smart-home-v3-conf:5803a0a7.51fa3] Aire : sending state update, topic:state/strummer84/6612 message:{"messageId":"03c52f91-af23-4b8e-976a-cfca386d6210","payload":{"state":{"power":"OFF","thermostatMode":"HEAT","thermostatSetPoint":24.5}}}
5 Jan 12:26:06 - [info] [alexa-smart-home-v3-state:sensor ambiental] sensor ambiental state node: discarded duplicate state payload
5 Jan 12:26:06 - [info] [alexa-smart-home-v3-state:Aire] Aire state node: discarded duplicate state payload
5 Jan 12:26:32 - [info] [alexa-smart-home-v3-state:sensor ambiental] sensor ambiental state node: discarded duplicate state payload
5 Jan 12:26:37 - [info] [alexa-smart-home-v3-state:sensor ambiental] sensor ambiental state node: discarded duplicate state payload

<<<<<<<<ALEXA turn ON aircon>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

5 Jan 12:27:09 - [info] [alexa-smart-home-v3-conf:5803a0a7.51fa3] Aire : sending state update, topic:state/strummer84/6612 message:{"messageId":"84371931-fef8-4e53-bc75-a5e1d7689ac4","payload":{"state":{"power":"OFF","thermostatMode":"COOL","thermostatSetPoint":24.5}}}
```
**Environment (please complete the following information):**
 - Node-RED node version: 14.17.6
 - Node-RED version: 1.0.3

**Additional context**

**Comment by coldfire84** [comment]
Have you sent the thermostat mode as a state update to Node RED Smart Home Control? See: https://docs.cb-net.co.uk/en/development/state-reporting.html#state-payload-reference

If the mode last sent to the service is 'COOL' that is what will be forwarded on to Alexa/ Google Home, the service itself doesn't change the mode.

**Comment by logon84** [comment]
Hi. The thing is that, I can see thru a debug node (msg.command) connected to alexa--smart-home v3 node that when saying "turn on aircon", the debug node shows SetThermostatMode command only, so it doesn't turn on. I don't know, I talk in spanish to Alexa, maybe is a language issue....But I tried different ways of telling to turn On and I always get the SetThermostatMode command. It is strange because the same setup has been working perfectly for two years now until 3 days ago.

EDIT: upsss sorry, this issue is in the wrong repo, I thought I was at node-red-alexa-home-skill-v3 repo.

**Comment by logon84** [comment]
Wrong place for this issue
