### ISSUE TITLE
Missing Directives

### ISSUE THREAD

**Issue by NovaGL** [coldfire84/node-red-alexa-home-skill-v3-web#16]
### Performing a Set Volume command results in "Not supported"

Directive can be found here: https://developer.amazon.com/docs/device-apis/alexa-speaker.html#setvolume

Eg Lower volume **to** five (not supported - SetVolume)
Lower volume **by** five (supported - AdjustVolume)

Is it possible information to say increase, decrease or set, currently when I receive the action I don't know what to do with it.

I just assume it's a lower if it starts with a dash.

Strangely the V2 API had:

> SetPercentageRequest, 
> IncrementPercentageRequest
> DecrementPercentageRequest

<del>
### Performing PlaybackController directives result in "Not supported"
Directive can be found here: https://developer.amazon.com/docs/device-apis/alexa-playbackcontroller.html#directives

The following directives are missing and return not supported.

> FastForward 
> Next
> Previous
> Rewind
> StartOver
</del>

**Comment by coldfire84** [comment]
@NovaGL,

> Performing a Set Volume command results in "Not supported"

Your findings are as expected (currently!). At present I have only extended the skill to cover [Alexa.StepSpeaker](https://developer.amazon.com/docs/device-apis/alexa-stepspeaker.html) which enables increase/ decrease and mute but not specific "known" volume levels. I'll look to add support for [Alexa.Speaker](https://developer.amazon.com/docs/device-apis/alexa-speaker.html).

> Performing PlaybackController directives result in "Not supported"

I've extended the supported directives under [Alexa.PlaybackController](https://developer.amazon.com/docs/device-apis/alexa-playbackcontroller.html), you'll need to re-run discovery to ensure your devices support the new directives.

**Comment by NovaGL** [comment]
Thanks! Playback controls works as expected now

**Comment by coldfire84** [comment]
SetVolume is now supported, ensure you select "Speaker Control" instead of "Step Speaker Control" in the device specification. 

You can now use the command:  "Alexa, set volume on Lounge TV to 50"

Note Speaker support requires that you update the node-red-contrib to version 0.4.11.

**Comment by coldfire84** [comment]
PercentageController interface is also now available. 

Note you **must use a State node with any device configured to have a PercentageController capability**, the state data is used to work out actual value after an increment/ decrement command (which would return negative values on decrement otherwise and cause an error as far as Alexa is concerned).

Note that PercentageController  support requires that you update the node-red-contrib to version 0.4.14.

**Comment by NovaGL** [comment]
Can you give me the command and response for percentage controller as I still get Telly doesn't support that.

**Comment by NovaGL** [comment]
> Challenge here is that to provide this information I need to have names, numbers and images for every channel, in every country.

Yeh, that's why I said it's not required as it would see no use. I could provide it in the response to the app if I so wished but don't feel it's worth it.

**Comment by coldfire84** [comment]
> SetPercentage and SetVolume works fine now, can I ask why this can't be under speakers? As you wouldn't only want to adjust the volume up or down you would want to set it too?
> 
> Whats the difference between
> Speaker Control and Step Speaker Control ?

I figured the StepSpeaker and Speaker thing would raise some questions (thanks Amazon!). The two controllers/ interfaces are different and have different capabilities.
* Speakers - are "smart", in that they can be set to specific numerical values for volume (or perhaps percentages). These speakers know what value/ percentage they are set to. This interface also support increase/ decrease and mute.
* StepSpeakers - are dumb. They don't know what value / percentage their volume is set to, they can just increase or decrease in volume and mute.

I can extend PercentageController to the Speaker interface (some speakers cannot do this - i.e. StepSpeaker - these support volume up/ down and not specific numbers or percentages).

**Comment by NovaGL** [comment]
Makes sense. There should only be speakers and step speakers imo. You might need to have a little description

**Comment by coldfire84** [comment]
I've looked at SkipChannels and this won't be possible based on the [response](https://developer.amazon.com/docs/device-apis/alexa-channelcontroller.html#response) required to the command/ directive.

Essentially, the response has to contain the new channel number/ name which the skill cannot know (it is *very* unlikely to be a simple case of increment any state data we could store.

I'll look at how I can feedback to the user that the command failed, as from what I understand based on your feedback, it **appears** as if the command is supported based on response from the bridge/ skill.

**Comment by coldfire84** [comment]
SkipChannels directive now returns "**\<device name\> doesn't support that**" via [INVALID_DIRECTIVE Error Response](https://developer.amazon.com/docs/device-apis/alexa-errorresponse.html#error-message-format)

**Comment by NovaGL** [comment]
I don't think that is correct. According to the response it doesn't change to that channel number it increments by that number.

> An integer value that indicates the channels to increment. A negative number indicates steps down, a positive number a steps up

So I would just return with a positive 1 or negative one.

So someone could say skip 5 channels.
I would say if it said 5 its up to the user to program channel up 5 times.

**Comment by coldfire84** [comment]
The command accepts an integer value within the payload, its the response that is the issue, example commands and response [here](https://github.com/alexa/alexa-smarthome/tree/master/sample_messages/ChannelController) - response for both SkipChannels and ChangeChannel looks the same.

**Comment by NovaGL** [comment]
As far as I could see channel count can be a negitive. channel number cant

**Comment by coldfire84** [comment]
Response only caters for number, callsign or affiliateCallSign though. I'm assuming that response "number" element cannot be negative.

The command will pass through to the API, but Alexa will say something along the lines of something went wrong/ device is not responding unless the expected response JSON object is passed back. 

Arguably, this could be *any* positive number, if state is not saved/ to be viewed in the Alexa App.

**Comment by NovaGL** [comment]
I don't think channel numbers need to be viewable in the alexa app but that's just me.

I guess I find it a bit misleading how the request can be negitive but not the response

**Comment by coldfire84** [comment]
> I guess I find it a bit misleading how the request can be negative but not the response

Indeed. It's the same with percentage controller and another controller which escapes me. With percentage controller you can send an adjust command with -25, but the response *has* to be a positive value - i.e. current value - 25. Learnt this the hard way as the docs aren't necessarily as clear as they could be.

**Comment by coldfire84** [comment]
Speaker functionality is now working as expected (both Alexa.Speaker and Alexa.StepSpeaker) as is PercentageController. Coupled with the [example outputs](https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/wiki/Example-Flows-and-Node-Outputs#default-node-outputs) I *think* that's everything from this issue.
