### ISSUE TITLE
Error "Certificate has expired" connecting to mq-red.cb-net.co.uk

### ISSUE THREAD

**Issue by Oriondely** [coldfire84/node-red-alexa-home-skill-v3-web#160]
Hi, starting from tonight NodeRed continuously try to connect to mq-red.cb-net.co.uk
"Re-connecting to Alexa/ Google Home Skill MQTT server: mq-red.cb-net.co.uk, account username: xxxx"
and then a "Certificate has experied" error is shown.
Obviously Alexa vocal commands don't work.

Please, someone can help me?
Thank you.

**Comment by Blade0001** [comment]
Hi, I have the same Issue.

**Comment by mathiaslehmann** [comment]
Hello, I have the same problem.

![image](https://user-images.githubusercontent.com/16978467/200273232-a16313b3-ac60-4a6e-9e0d-d604bb0d9645.png)

**Comment by coldfire84** [comment]
Seems to be impacting a subset of users following an automated certificate renewal, I've bounced the MQTT server which should resolve the issue.

**Comment by Oriondely** [comment]
Thank you @coldfire84, all works fine for me now 👍

**Comment by mathiaslehmann** [comment]
Thank you @coldfire84, it works again

**Comment by Blade0001** [comment]
For me too

**Comment by SCarter77** [comment]
New user - same issue

**Comment by Izhora2024** [comment]
I'm not using any MQTT at all, but I'm getting the same error: "Re-connecting to Alexa/Google Home Skill MQTT server: mq-red.cb-net.co.uk,...". It just won't connect to the server. What could be the issue?
