### ISSUE TITLE
registration problem

### ISSUE THREAD

**Issue by botioni** [coldfire84/node-red-alexa-home-skill-v3-web#161]
cant confirm email it say thet i alredy confirmed and i cant login because it say you need to confirm email !!!

**Comment by Chris-656** [comment]
> cant confirm email it say thet i alredy confirmed and i cant login because it say you need to confirm email !!!

Its the same for me. There are no emails send for verification
Regards Chris

**Comment by im0en** [comment]
I have the same problem.

**Comment by coldfire84** [comment]
Gnarly / intermittent issue, finally got to the bottom of what was going on with email provider. 

Should now be resolved.

**Comment by im0en** [comment]
Works! Thanks a lot
