### ISSUE TITLE
Error: certificate has expired

### ISSUE THREAD

**Issue by Fernando-Checa** [coldfire84/node-red-alexa-home-skill-v3-web#168]
**Describe the bug**
lots of messages like this.
II tried to redeploy the nodes but no fix yet.

**Log Output**
`7 Mar 10:07:06 - [warn] [alexa-smart-home-v3-conf:0a407f1bc09a3464] Re-connecting to Alexa/ Google Home Skill MQTT server: mq-red.cb-net.co.uk, account username: xxxxxx

7 Mar 10:07:06 - [error] [alexa-smart-home-v3-conf:0a407f1bc09a3464] Error: certificate has expired`

**Environment (please complete the following information):**

- Node-RED node version:
3.0.2

**Comment by Fernando-Checa** [comment]
I can ping both servers just fine:

```
PING mq-red.cb-net.co.uk (178.79.148.16) 56(84) bytes of data.
64 bytes from li268-16.members.linode.com (178.79.148.16): icmp_seq=1 ttl=53 time=35.6 ms
```

```
PING red.cb-net.co.uk (172.67.131.163) 56(84) bytes of data.
64 bytes from 172.67.131.163 (172.67.131.163): icmp_seq=1 ttl=56 time=25.9 ms
```

Also restarted Nodered, the whole machine and even changed my password on the website to update the node.

But still not working

**Comment by Fernando-Checa** [comment]
Also tried to clear tokens and relinking the skill...

**Comment by ChKolumbus** [comment]
Same problem here since some hours: 

The skill does not work anymore the nodes are disconnected and try to reconnect regularly but they do not succeed.
For a long time nothing has changed on the own server or the flows, so I assume a problem with the service server.
I hope someone can fix this, because the service has worked excellent so far. 

Debug Messages from NodeRed:

7.3.2023, 13:45:25[node: 2477ed594d34bee6](http://192.168.178.140:1880/#)msg : string[103]
"Re-connecting to Alexa/ Google Home Skill MQTT server: mq-red.cb-net.co.uk, account username: XXXXX"
7.3.2023, 13:45:25[node: 2477ed594d34bee6](http://192.168.178.140:1880/#)
msg : error
"Error: certificate has expired"

**Comment by wossix** [comment]
Same problem here.

**Comment by minskicat** [comment]
Ditto. Also tried deleting tokens and re linking.

**Comment by jimmycd** [comment]
same here

**Comment by Fernando-Checa** [comment]
now it has changed to:

`Error: connect ECONNREFUSED 178.79.148.16:8883`

nodered log:

`7 Mar 20:33:22 - [warn] [alexa-smart-home-v3-conf:0a407f1bc09a3464] Re-connecting to Alexa/ Google Home Skill MQTT server: mq-red.cb-net.co.uk, account username: xxxxxx

7 Mar 20:33:23 - [error] [alexa-smart-home-v3-conf:0a407f1bc09a3464] Error: connect ECONNREFUSED 178.79.148.16:8883

7 Mar 20:33:23 - [error] [alexa-smart-home-v3-conf:0a407f1bc09a3464] Error: connect ECONNREFUSED 178.79.148.16:8883`

**Comment by coldfire84** [comment]
I’m on it. Bear with me.

**Comment by Fernando-Checa** [comment]
Take your time.
If you  need any help, tests or logs just ask.

**Comment by jimmycd** [comment]
if you need help tell us

**Comment by coldfire84** [comment]
This should now be resolved. Still trying to get to the bottom of what happened --> cert renewed automatically, as expected, but this  led to *some* users not being able to connect. Inconsistent results across different groups of users, always makes RCA hard.

I have reset certs across the stack (hence some of the downtime tonight - first real outage in years 😭).

**Comment by privet971** [comment]
.Thanks a lot , I confirm that all are ok now.

Good job !!!!

**Comment by Fernando-Checa** [comment]
Seems resolved from here as well.
Thanks so much for your time

**Comment by coldfire84** [comment]
I have refactored the cert-renewal hook scripts this evening, I am hopeful this should solve/ prevent a reoccurrence of the issue.
