### ISSUE TITLE
[alexa-smart-home-v3-conf] Re-connecting to Alexa/ Google Home Skill MQTT server: Certificate expired

### ISSUE THREAD

**Issue by Oriondely** [coldfire84/node-red-alexa-home-skill-v3-web#169]
Hello,
first of all thank you for your support.

Sometimes, as now, I have the following error:

WARN [alexa-smart-home-v3-conf:ca74b379.e4e06] Re-connecting to Alexa/ Google Home Skill MQTT server: mq-red.cb-net.co.uk, account username: *********

ERROR [alexa-smart-home-v3-conf:ca74b379.e4e06] Error: certificate has expired

Nodes status in node-red continously change from "reconnecting" to  "disconnected" in loop.
Can you please check if everything is ok from your side?

Thank you.

**Comment by privet971** [comment]
Hello, 
I also have this problem and I think it's the same problem as the previous number (#168)
Thks

**Comment by cypher0815** [comment]
Hi,
same error. No SSL connection possible due to certificate expired on 06.03.2023 (Let´s Encrypt)

**Comment by coldfire84** [comment]
Duplicate of #168
