### ISSUE TITLE
Problem with Motion Sensor in Alexa

### ISSUE THREAD

**Issue by ArekKubacki** [coldfire84/node-red-alexa-home-skill-v3-web#171]
**Describe the bug**
Alexa has not seen the MotionSensor status change for several days now. You can't access sensors in Alexa. I also checked by adding a new one. It is found but upon entering there is a white screen and the routines do not respond to the change. After adding, for example, a light bulb, everything works fine.

**To Reproduce**
Everything worked fine for several years. No changes were made.

**Expected behavior**
No error messages in node-red. It's hard to say what happened.

**Log Output**
No errors. 

**Environment (please complete the following information):**

- Node-RED node version: 0.4.68
- Node-RED version: 3.0.2

**Additional context**
I didn't change anything in node-red or Alexa. 3 days ago it suddenly stopped working. As I wrote earlier, Alexa has a problem with entering MotionSensor.

**Comment by HaknCo** [comment]
Hi, I experienced the same issue. My routines stopped working on the 8.3. The state updates work but routines are not triggered. I noticed that the SSL certitificate of the MQTT server expired on the 6.3. I dropped a message on the Slack Channel, maybe the problem is related to it.

**Comment by coldfire84** [comment]
This should now be resolved.

**Comment by HaknCo** [comment]
Routines work again. Thanks.

**Comment by ArekKubacki** [comment]
Unfortunately it still doesn't work for me :(

**Comment by coldfire84** [comment]
@ArekKubacki  can you try and re-link the skill.
