### ISSUE TITLE
Capabilities icons are not unique

### ISSUE THREAD

**Issue by NovaGL** [coldfire84/node-red-alexa-home-skill-v3-web#18]
It's a bit confusing to know what the icons represent when they are duplicated,
https://nr-alexav3.cb-net.co.uk/devices

- Temperature Sensor 
- Thermostat (1-Point) 

- Speaker Control
- Step Speaker Control

**Comment by coldfire84** [comment]
Temperature Sensor and Thermostat **are** different, you need to clear your browser cache. I used the original Thermostat icon for Temperature Sensor and changed the Thermostat Icon (hence the fact you're seeing double).

I'm deliberating how to change the icon for StepSpeaker!

**Comment by coldfire84** [comment]
Speaker icon has been changed. StepSpeaker remains as it was.

This will take time to show due to web server / browser cache.

**Comment by coldfire84** [comment]
I've also purged CDN cache, which seems to ensure that the icon changes show after a Ctrl-F5.

**Comment by NovaGL** [comment]
Thanks, not sure the wave length fits with the description, maybe this

https://thenounproject.com/search/?q=speaker&i=380655

**Comment by coldfire84** [comment]
Agreed, I'm not happy with outcome of new icon. I'm going to refresh all of the icons in the UI tomorrow... watch this space.
