### ISSUE TITLE
Authentication Faild - Mongo DB

### ISSUE THREAD

**Issue by diba78** [coldfire84/node-red-alexa-home-skill-v3-web#2]
Hi coldfire,

first thanks for you howto. so i can setup my own bridge. I had some trouble with with the web services and the connection to mongodb 4.0.3 docker image. I fixed this with ?authSource=admin at the end of the mongo url at this two points in the index.js:

1. // Connect to Mongo Instance
mongo_url = "mongodb://" + mongo_user +":" + mongo_password + "@" + mongo_host + ":" + mongo_port + "/users" + "?authSource=admin&authMechanism=SCRAM-SHA-1";

2. app.use(session({
        store: new mongoStore({
                url: "mongodb://" + mongo_user +":" + mongo_password + "@" + mongo_host + ":" + mongo_port + "/sessions" + "?authSource=admin&authMechanism=SCRAM-SHA-1"

If you have a better advice let me know.

Best regards

Dirk

**Comment by coldfire84** [comment]
> I had some trouble with with the web services and the connection to mongodb 4.0.3 docker image. I fixed this with ?authSource=admin at the end of the mongo url at this two points in the index.js:

Strange, I've deployed this numerous times with the code as-is. My own MongoDB instance also updates to vCurrent every night automatically (via Watchtower) so surprised I have not run into this.

I assume you used the scripts I created for account generation in MogoDB: https://gist.github.com/coldfire84/93ae246f145ef09da682ee3a8e297ac8

I'll do some more testing to see if I can replicate this issue.

**Comment by coldfire84** [comment]
I've re-reviewed the code and don't think specifying the admin DB as source is necessary.

Flow is as follows:
1. When you create the MongoDB instance, the guide stipulates the use of the MONGO_INITDB_ROOT_USERNAME and MONGO_INITDB_ROOT_PASSWORD as part of the startup params for the container
2. You then re-use these credentials to execute [this script](https://gist.github.com/coldfire84/93ae246f145ef09da682ee3a8e297ac8) on startup which creates users in the users and sessions databases - using docker-entrypoint-initdb.d to auto-launch on first run
3. You then re-use the \<web-app-user\> account when you launch the web service via the docker command, as this account exists in the users db, and that's the DB the service is connecting to there is no need to specify the '?authSource' param.

**Comment by diba78** [comment]
Hi coldfire,

the mistake was on my site. i used the wrong user. with the web user as mongo user for the web server it works. i used the mongo admin user before. Thanks for your help.

Best regards

Dirk
