### ISSUE TITLE
Alexa App: Thermostat state view not working

### ISSUE THREAD

**Issue by coldfire84** [coldfire84/node-red-alexa-home-skill-v3-web#25]
Regression as this was functional. Response as-is (not working) form Lambda as below.

App shows "Waiting for Node-RED..." - other state view are working as expected.

---

```
{
    "event": {
        "header": {
            "messageId": "7c226850-e259-4cf9-bc71-4730cb4b1387",
            "correlationToken": "<correlation-token>",
            "namespace": "Alexa",
            "name": "StateReport",
            "payloadVersion": "3"
        },
        "endpoint": {
            "scope": {
                "type": "BearerToken",
                "token": "<token>"
            },
            "endpointId": "91",
            "cookie": {}
        }
    },
    "context": {
        "properties": [
            {
                "namespace": "Alexa.TemperatureSensor",
                "name": "temperature",
                "value": {
                    "value": 22,
                    "scale": "CELSIUS"
                },
                "timeOfSample": "2019-01-14T21:56:54.896Z",
                "uncertaintyInMilliseconds": 10000
            },
            {
                "namespace": "Alexa.ThermostatController",
                "name": "targetSetpoint",
                "value": {
                    "value": 21.5,
                    "scale": "CELSIUS"
                },
                "timeOfSample": "2019-01-14T21:56:54.896Z",
                "uncertaintyInMilliseconds": 10000
            },
            {
                "namespace": "Alexa.ThermostatController",
                "name": "thermostatMode",
                "value": "HEAT",
                "timeOfSample": "2019-01-14T21:56:54.896Z",
                "uncertaintyInMilliseconds": 10000
            },
            {
                "namespace": "Alexa.EndpointHealth",
                "name": "connectivity",
                "value": {
                    "value": "OK"
                },
                "timeOfSample": "2019-01-14T21:56:54.896Z",
                "uncertaintyInMilliseconds": 10000
            }
        ]
    },
    "payload": {}
}
```

**Comment by coldfire84** [comment]
Can you confirm if you have sent temperature sensor data state to the device? By default both the Thermostat and Temperature Sensor device types are selected.

If you are not supplying temperature state data then un-tick this under Device Types and re-discover devices.

I can also see your deviceId is being rate-limited (+100 state requests in an hour for state data!). This may explain the Alexa App issue.

**Comment by Langer75** [comment]
Ok I think I got it. I provided temperature data in the state response and then I could see see it in the app. But it works only a few times. Now it is again stucking. Is it because of the rate-limit? But I did not made more than 30 requests I guess

**Comment by Langer75** [comment]
Now I got all the time "device does not react"

**Comment by coldfire84** [comment]
The Alexa App polls every 2-3 seconds, which is why I have put the rate limit in-place (each poll uses Lambda resources, which are chargeable).

If you leave the Alexa App open for a couple of minutes, open on a specific device, you'll chew through the rate limit. The limit is user *and* device specific.

**Comment by Langer75** [comment]
Ok understood, But why I can deselect the Temperature sensor but not the Temperature capability. Would this help?

**Comment by coldfire84** [comment]
Rate limit was hit, give it an hour and it should work as expected.

> Ok understood, But why I can deselect the Temperature sensor but not the Temperature capability. Would this help?

Sorry, not sure I fully understand the question. If you remove "Temperature Sensor" capability you can then ask Alexa to "discover devices." The only difference is the ambient temperature is not reported in the Thermostat view in the Alexa App. You'll still have to wait for the rate limit to expire.

**Comment by Langer75** [comment]
Yes, this would I expect too. But I can not deselect the Temperature Sensor capability while Thermostat capability is selected.

**Comment by coldfire84** [comment]
I've opened an enhancement to review the device creation process. As capabilities have grown the options are confusing! #32 will cover this work, which is underway.

**Comment by Langer75** [comment]
Ok, Thanks a lot for your help and your work. I will wait for that

**Comment by coldfire84** [comment]
@Langer75 , were you able to confirm whether this is now working?
