### ISSUE TITLE
Percentage capability

### ISSUE THREAD

**Issue by Langer75** [coldfire84/node-red-alexa-home-skill-v3-web#31]
Hi

I tried the percentage capability. Unfortunately node red receives undefined payload. Does it work in german? Or do I something wrong?

langer

**Comment by coldfire84** [comment]
Can you share node output, just tested with SetPercentage command:

```
msg : Object
object
topic: ""
name: "Test Fan"
_messageId: "8bd1c4ba-01a9-40f2-9058-5d5636605a0b"
_endpointId: "104"
_confId: "bfd0fcf4.bc90e"
command: "SetPercentage"
extraInfo: object
payload: 25
acknowledge: true
_msgid: "268313a5.2fecbc"
```

**Comment by coldfire84** [comment]
Also worth checking console log for Node-RED and sharing anything relevant.

**Comment by coldfire84** [comment]
Are you using the latest version of the node-red-contib? https://www.npmjs.com/package/node-red-contrib-alexa-smart-home

**Comment by Langer75** [comment]
Actually I am using 4.1 I will update it right now

**Comment by Langer75** [comment]
Ok thats it. Now I got a payload.
