### ISSUE TITLE
Add info to Device Type

### ISSUE THREAD

**Issue by NovaGL** [coldfire84/node-red-alexa-home-skill-v3-web#37]
I'm not sure if you agree but with the addition of Google home the Device Configuration is getting a bit messy.

Maybe items can be dynamically shown based on what service(Google or Alexa) and what device type is shown.

Another thing is you have a device called "Advanced/ Other" what does that mean.

**Comment by NovaGL** [comment]
You are very prompt at doing this. Unless you were already trying to make things dynamically shown?

**Comment by coldfire84** [comment]
The new modal/ device creation process has been in place for a couple of days. This was delivered under #32

**Comment by NovaGL** [comment]
Thanks,

I still think that Google and Alexa should be separated so the user only sees the devices related to that platform.

So I would have a row called Platform with the options of Alexa, Google Home and Both.
Once you add some information on what device types mean such as Other then you can close this issue.

**Comment by coldfire84** [comment]
> I still think that Google and Alexa should be separated so the user only sees the devices related to that platform.

The challenge here is that I want to see the same devices on both platforms, whilst minimising the size/ complexity of the Device Modal (creation/ modification wizard). 

> Once you add some information on what device types mean such as Other then you can close this issue.

I'll add a tooltip on device types (perhaps just the Other/ Advanced type) to the effect of "danger, there be dragons" / results will vary.

**Comment by NovaGL** [comment]
Thanks, but you haven't explained what other actually is?

**Comment by coldfire84** [comment]
> Thanks, but you haven't explained what other actually is?

I guess you can surmise this as "Expert" mode. You can create any combination (with some specific restrictions) but your results could be mixed in terms of outcomes. i.e. a smart bulb with a temperature sensor (a use case for a beta user today).

I'll be adding a tooltip that covers this, plus warning as above later in the week. 

Priority at the moment is getting async state reporting working for Google Home (synchronous state reports are already working), specifically for commands/ interactions that occur outside of Google Home.

**Comment by coldfire84** [comment]
Tool-tip added to Other/ Advanced device type.
