### ISSUE TITLE
Support changing channel

### ISSUE THREAD

**Issue by NovaGL** [coldfire84/node-red-alexa-home-skill-v3-web#4]
Does this API support Alexa.ChannelController Interface

See below, would be really cool if it did.
https://developer.amazon.com/docs/device-apis/alexa-channelcontroller.html

**Comment by coldfire84** [comment]
I've added this to the [Release 0.5 Plan](https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/wiki/Features-Roadmap). Will review the required steps and feedback if this is achievable.

Out of interest what is your target endpoint/ node for the channel change?

**Comment by NovaGL** [comment]
Thanks, I want to use it for changing channels on cable.

I currently do "Hey Google, Channel ABC" and it changes the channel.
I'm using IFTTT and Node-Red.

I'm trying to centralise everything with Node-Red. Got lights working great, AV in general is a sub par experience.  So I want to fix that. Inputs and other things should help. 

I sent you an email. I'll help test things.

**Comment by coldfire84** [comment]
Support for channel name and number added - if you use a channel number the resulting payload will be the channel number, if you use a channel name, the payload will be the supplied name.

For reference:
- If you are using hosted instance the lambda/ web API changes are effective. **You still need to update Node-RED contrib nodes**.
- If you are hosting your own instance, pull an updated version of the coldfire84/nr-alexav3-web:latest container and update you lambda code to release-0.5. You'll also need to ensure you are running the latest Node-RED contrib nodes.

**Comment by NovaGL** [comment]
Let me know if you managed to find the website to give invites

**Comment by coldfire84** [comment]
I'm unable to share a link from within the Alexa App, and from Desktop I can't view the skill (to share the link) as it is still under development (Alexa Skill store has a banner saying "Visit the Alexa App to manage skills in development."

I've confirmed your email address is in-scope of the testing group, in the same way all of the other active testers have been setup.
