### ISSUE TITLE
Missing Thermostat Modes Support

### ISSUE THREAD

**Issue by zyrorl** [coldfire84/node-red-alexa-home-skill-v3-web#40]
Currently only COOL and HEAT are supported, can we please get ECO, OFF and AUTO mode supported?

AUTO | Indicates automatic heating or cooling based on the current temperature and the setpoint.
-- | --
COOL | Indicates cooling mode.
HEAT | Indicates heating mode.
ECO | Indicates economical mode.
OFF | Indicates that heating and cooling is turned off, but the device may still have power.

See: https://developer.amazon.com/docs/device-apis/alexa-property-schemas.html#temperature

**Comment by NovaGL** [comment]
OFF won't be supports as you have to enable Power. I requested this one already, so you can say turn aircon off or turn aircon on.

**Comment by coldfire84** [comment]
> Currently only COOL and HEAT are supported

AUTO, HEAT, COOL, ON and OFF **are** supported at time of writing (may be I've not updated the Wiki to reflect this, _so many changes_ in the last week or so!). ECO currently isn't, but can be. 

The challenge here is working out the response logic - i.e when a change in target set point is made, what mode should the bridge report back. The more modes supported the more complex this becomes. In effect end up having to write logic for the thermostat firmware itself!

You're able to select supported modes via the new device creation wizard/ modal.

**Comment by coldfire84** [comment]
> AUTO, HEAT, COOL, ON and OFF are supported at time of writing (may be I've not updated the Wiki to reflect this, so many changes in the last week or so!). ECO currently isn't, but can be.

This was causing device discovery issues, "ON" is not actually a supported mode. I have removed that this evening and added "ECO" in its place. Discovery is working as expected.

**Comment by miaszh** [comment]
Hi,
Still Thermostat doesn't show/support turning ON or OFF.. neither changing modes..
There is no Power option in alexa / routines .. can this be done somehow?

Thanks
