### ISSUE TITLE
Alexa skill invitation requirements

### ISSUE THREAD

**Issue by Keltere** [coldfire84/node-red-alexa-home-skill-v3-web#44]
Hi, i wanted to know if there are any requirements to access the skill service or it's open to anyone who ask for it?
The FAQ apparently doesn't state anything about it so i just wanted to ask to be sure of it.

**Comment by coldfire84** [comment]
No specific requirements, I'm just wrapping up the code for the Alexa.Authorization framework (to hopefully enable async state updates), am delaying accepting new testers for a couple of days as a result, but have a (small) backlog of users that will be enabled in the next 48hrs or so.

Once development work is finalised the skill will be submitted and will be generally available to anyone.

**Comment by Keltere** [comment]
instead of opening another issue ill ask right here.
For binary command like TunOn/Off Mute/UnMute etc wouldn't be better if the payload was a boolean instead of a string?

**Comment by coldfire84** [comment]
Define "better" :) - in all seriousness, I understand your point though.

For the Alexa payloads I use the response from the Alexa Smart Home API as a template, hence the format to-date. I can change this, but it would have to be a transition catering for existing users.

**Comment by Keltere** [comment]
For better i mean that i can immediately use a function (if true) instead of comparing two strings.
But if it's based on the official response it's better to keep like that.
Sry, just an idea i've had while making a remote control for my marantz amp.
Hope to test it soon.

**Comment by coldfire84** [comment]
> Sry, just an idea i've had while making a remote control for my marantz amp.

Please don't apologise, to get the feedback/ questions is really good 💯

**Comment by coldfire84** [comment]
@Keltere not sure if you had a queued-up request, but have invited you to the beta now that the code-drop for #41 is in place.

**Comment by Keltere** [comment]
Hi, yes thanks i've already set it up.
I'm already testing it, i will try to make a module for marantz and denon amplifiers compatible with this.
Too bad the input selection doesn't seem to work in italian, instead mute, volume, power seem to work just fine.

**Comment by coldfire84** [comment]
> Too bad the input selection doesn't seem to work in Italian, instead mute, volume, power seem to work just fine.

This can probably be resolved by enabling custom entries/ inputs. I'd be interested to know what commands you have tried/ console output from the node red instance.

**Comment by coldfire84** [comment]
Yep, that's right - I'd not seen that! Will look to create a matrix of supported commands/ interfaces by country at some point.

**Comment by coldfire84** [comment]
FAQ updated to reflect no requirements to join beta.

**Comment by Keltere** [comment]
@coldfire84 look at [this](https://developer.amazon.com/it/docs/device-apis/list-of-interfaces.html)

**Comment by coldfire84** [comment]
@Keltere thanks, I'll create a link to that in the Wiki now!

**Comment by Keltere** [comment]
strange fact: the speaker controller works in italian even if it's not listed but the volume control sometimes overlap the echo settings. If i ask alexa to set the amplifier volume she will keep changing the volume of that amplifier even without naming it, it will override the echo volume request. To resolve this ill have to ask alexa to stop.

Here are the passages:
1. `Alexa, amplifier set volume 20`
2. `Alexa, set volume 5`  <- instead of changing echo volume it will change the amplifier volume
3. `Alexa, stop`
4. `Alexa, set volume 5` <- now it will set the volume of the echo device correctly

Alexa still a long way to go.

**Comment by coldfire84** [comment]
Interestingly I quite like the overlap. For example using the playback controller and after the initial command, "Alexa, pause" and "Alexa, play" work well. I find this is much more intuitive than having to remember (or get someone else to remember who doesn't know) the device names.
