### ISSUE TITLE
Google Home: German de-DE Translation

### ISSUE THREAD

**Issue by coldfire84** [coldfire84/node-red-alexa-home-skill-v3-web#45]
|Item|English Text|
|---|---|
|Short Description| Control your Node-RED flows with Google Assistant |
|Full Description| Using this device bridge you can control a variety of Node-RED endpoints, such as MQTT, HTTP(S), Yamaha AVRs, Chromecast (anything that has a Node-RED integration). This bridge currently supports Power, Brightness, Colour, Colour Temperature, Scene and Thermostat traits. You'll need to follow the instructions here to get up and running: https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/wiki/Use-the-Hosted-Instance|

**Comment by fulcrumEFX** [comment]
Translation:

Item | German Text
-- | --
Kurzbeschreibung | Steuern Sie Ihre Node-RED Flows mit dem Google Assistant
Volle Beschreibung | Mit dieser Geräte-Bridge können Sie mit einer weiten Reihe von Node-RED Endpunkten kommunizieren, z.B. MQTT, HTTP(S), Yamaha AVRs, Chromecast (alles was eine Node-RED Integration hat). Diese Bridge unterstützt zur Zeit Power, Helligkeit, Farbtemperatur, Szene und Thermostatfunktionen. Folgen Sie der Beschreibung, um alles einzurichten: https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/wiki/Use-the-Hosted-Instance

**Comment by coldfire84** [comment]
@fulcrumEFX - thank you! I've updated the Action with this information and re-published the beta. If this has been extended to you I'd be interested to know if it is now working when you try to link accounts.
