### ISSUE TITLE
Google Home: Italian it-IT Translation

### ISSUE THREAD

**Issue by coldfire84** [coldfire84/node-red-alexa-home-skill-v3-web#47]
|Item|English Text|
|---|---|
|Short Description| Control your Node-RED flows with Google Assistant |
|Full Description| Using this device bridge you can control a variety of Node-RED endpoints, such as MQTT, HTTP(S), Yamaha AVRs, Chromecast (anything that has a Node-RED integration). This bridge currently supports Power, Brightness, Colour, Colour Temperature, Scene and Thermostat traits. You'll need to follow the instructions here to get up and running: https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/wiki/Use-the-Hosted-Instance|

**Comment by Keltere** [comment]
Short Description => Controlla i tuoi Flow su Node-RED tramite Google Assistant

Full Description => Con questo bridge puoi controllare diversi endpoint tra cui MQTT, HTTP(S), Yamaha AVRs, Chromecast (qualsiasi cosa che sia integrata in Node-RED).
Questo bridge attualmente supporta Accensione, Luminosità, Colore, Temperatura colore, Scene e (Thermostat traits). Segui queste istruzioni per l'installazione: https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/wiki/Use-the-Hosted-Instance

**Comment by Keltere** [comment]
Don't know what you mean by "Thermostat traits", could you please be more specific?

**Comment by coldfire84** [comment]
"Trait" is [Google's terminology](https://developers.google.com/actions/smarthome/traits/) for Smart Home capabilities.

**Comment by Keltere** [comment]
Ok updated.

**Comment by coldfire84** [comment]
Thanks @Keltere , that's awesome!
