### ISSUE TITLE
Device configration buttons disappear

### ISSUE THREAD

**Issue by NovaGL** [coldfire84/node-red-alexa-home-skill-v3-web#49]
Click the Thermostat and Temperature Sensor device type and then remove one of them and all the options disappear.

You have to unclick everything for it to be functional again.

**Comment by coldfire84** [comment]
Still some issues when top-level device type is changed (namely when Thermostat and temperature Sensor are both selected and one is disabled). Still working the logic out on this.

Capability-level changes are now handled much better, for example thermostat modes/ options are now remembered when the capability is re-selected.

**Comment by NovaGL** [comment]
Scale Options is also now broken

**Comment by coldfire84** [comment]
Believe this is now resolved.

**Comment by NovaGL** [comment]
I just tried it, not working
