### ISSUE TITLE
Echo device information on msg

### ISSUE THREAD

**Issue by orxaz** [coldfire84/node-red-alexa-home-skill-v3-web#52]
Hi.

This is not an issue but a suggestion.

Would be nice that the msg received when a device is invoked, has information about the Echo device has received the command. This way, if you have several Echo devices, the command can do different actions depending on which Echo has received the command.

**Comment by NovaGL** [comment]
I believe this isn't possible.

If you have multiple Echos you can set them up in rooms and then link the echo to that room.

Eg if you say turn on lights to the bedroom dot it should only turn the lights on in the bedroom as they are linked.

**Comment by orxaz** [comment]
Hi.

Thanks for your reply.

Yes, I know, in fact I have all my Echos this way, with lights and Node-red devices in groups too, but I have some nodes now that, when invoking them, run scripts that make the Echos to say some information, and would be nice that the Echo that answer was the same that the one being asked. Now this is not possible, I must decide, on time of making the script, which Echo will answer.

If is not possible, then is nothing to do, but if in any way, the Alexa API would return any kind of ID of the device that got the command, would be nice that the object received on Node-red has this information.

In any case, I am happy to be able to use the nodes as them are, but with this enhancement, them will be even better.

**Comment by coldfire84** [comment]
Yep, as-per @NovaGL's comments this isn't possible. Not a limitation of the Node-RED bridge, rather the Alexa API itself. Requests from Alexa do not contain device/ room information.

Closing this issue as I'm unable to do anything with it.

**Comment by orxaz** [comment]
Ok, I supposed some like that, anyway, many thanks for this great job, I'am using it now and am really happy with what it can do.
