### ISSUE TITLE
Increase/decrease channel

### ISSUE THREAD

**Issue by orxaz** [coldfire84/node-red-alexa-home-skill-v3-web#53]
Hi.

Again, this is not an issue but a suggestion.

Would be nice to be able to increase or decrease channels on multimedia devices:
https://developer.amazon.com/es/docs/device-apis/alexa-channelcontroller.html#skipchannels

I think this is not possible right now, am I wrong?

**Comment by coldfire84** [comment]
See https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/issues/16

**Comment by orxaz** [comment]
Ok, thanks and excuse me for not finding it before asking.
