### ISSUE TITLE
any limitation?

### ISSUE THREAD

**Issue by matispf84** [coldfire84/node-red-alexa-home-skill-v3-web#54]
Hi, 

first I want to thank you for the excellent work you did.
I started using it a few days ago. I have a question, do you have any kind of limitation for use? or by number of devices? because after adding my 15 devices and restarting my raspberry, the nodes did not connect anymore (with the green status tags saying: "connected")

![captura](https://user-images.githubusercontent.com/2854288/53445854-4ab7bb00-39f0-11e9-85c3-51184cfc9b77.PNG)

**Comment by coldfire84** [comment]
I'm running 25 devices from the bridge at present, with no issues... 15 should be fine.

**Comment by matispf84** [comment]
> I'm running 25 devices from the bridge at present, with no issues... 15 should be fine. Although I'm using the 25 across multiple flows/ tabs in Node-RED.

since yesterday it started to work again. So I really do not know what happened, I did not make any changes.

**Comment by coldfire84** [comment]
OK, let me know if you have any further issues.
