### ISSUE TITLE
Own deploy, Starting NodeJS WebApp fails

### ISSUE THREAD

**Issue by Langer75** [coldfire84/node-red-alexa-home-skill-v3-web#56]
![Error](https://user-images.githubusercontent.com/45699779/54317398-51932000-45e3-11e9-81d1-0ae15a9f1f10.PNG)
Unfortunately the NodeJs WebApp container does not start corectly. Any idea?

**Comment by Langer75** [comment]
![Error](https://user-images.githubusercontent.com/45699779/54335044-12d38900-4628-11e9-8dd5-999a9871a84e.PNG)
Afer setting ALEXA_DEBUG as environment variable I got another error. It seems that NodeJS can not connect to mongodb container. I have no idea why. Whwere can I found the mentined logfile? I can not find oit under the given path

**Comment by Langer75** [comment]
This was Network Problem. Nur Ärger fixing it I geh an Authentication Terror. U will Provider Terror los älter.

**Comment by coldfire84** [comment]
Can you share the authentication error?

**Comment by Langer75** [comment]
Here error log the log. 

stdout	> node-red-alexa-home-skill-v3@0.8.0 start /usr/src/app
stdout	> node server.js 

stdout	"[32minfo[39m: [Core] Log Level set to: debug {""timestamp"":""2019-03-14T18:26:38.790Z""}" 
stdout	"[32minfo[39m: [Core] Connecting to MongoDB server: mongodb://mongodb:27017/users {""timestamp"":""2019-03-14T18:26:49.352Z""}" 
stdout	"[32minfo[39m: [Core] Connecting to MongoDB... {""timestamp"":""2019-03-14T18:26:49.384Z""}" 
stdout	"[33mwarn[39m: [App] Using default Cookie Secret, please supply new secret using COOKIE_SECRET environment variable {\timestamp\"":\""2019-03-14T18:26:51.104Z\""}" 
stdout	"[33mwarn[39m: [GHome API] JSON Web Token not supplied via ghomeJWT environment variable. Google Home Report State disabled. {""timestamp"":""2019-03-14T18:26:59.541Z""}" 
stdout	"[33mwarn[39m: [Core] No HOMEGRAPH_APIKEY environment variable supplied. New devices, removal or device changes will not show in users Google Home App without this {\timestamp\"":\""2019-03-14T18:26:59.542Z\""}" 
stdout	"[32minfo[39m: [GHome API] Connecting to MQTT server: mqtt://mosquitto {""timestamp"":""2019-03-14T18:27:02.676Z""}" 
stdout	"[32minfo[39m: [Alexa API] Connecting to MQTT server: mqtt://mosquitto {""timestamp"":""2019-03-14T18:27:10.138Z""}" 
stdout	"[33mwarn[39m: [GHome API] JSON Web Token not supplied via ghomeJWT environment variable. Google Home Report State disabled. {""timestamp"":""2019-03-14T18:27:10.231Z""}" 
stdout	"[32minfo[39m: [State API] Connecting to MQTT server: mqtt://mosquitto {""timestamp"":""2019-03-14T18:27:10.234Z""}" 
stdout	"[33mwarn[39m: [Core] No HOMEGRAPH_APIKEY environment variable supplied. New devices, removal or device changes will not show in users Google Home App without this {\timestamp\"":\""2019-03-14T18:27:10.247Z\""}" 
stdout	"[32minfo[39m: [Core] App listening on: 0.0.0.0:3000 {""timestamp"":""2019-03-14T18:27:10.707Z""}" 
stdout	"[32minfo[39m: [Core] App_ID -> http://localhost:3000 {""timestamp"":""2019-03-14T18:27:10.708Z""}" 
stdout	"[33mwarn[39m: [Logger] AWS credentials file does not exist at ~/.aws/credentials. Cludwatch logging disabled. {""timestamp"":""2019-03-14T18:27:10.747Z""}" 
stdout	"[32minfo[39m: [Core] Connecting to Redis server... {""timestamp"":""2019-03-14T18:27:13.568Z""}" 
stdout	"[32minfo[39m: [Core] Redis connection ready! {""timestamp"":""2019-03-14T18:27:13.908Z""}" 
stdout	"[31merror[39m: [GHome API] MQTT connect error {""timestamp"":""2019-03-14T18:27:13.953Z""}" 
stdout	"[31merror[39m: [Alexa API] MQTT connect error {""timestamp"":""2019-03-14T18:27:13.969Z""}" 
stdout	"[31merror[39m: [State API] MQTT connect error {""timestamp"":""2019-03-14T18:27:13.975Z""}" 
stdout	[31merror[39m: uncaughtException: Authentication failed. 
stdout	MongoError: Authentication failed. 
stdout	    at Function.MongoError.create (/usr/src/app/node_modules/mongodb-core/lib/error.js:31:11) 
stdout	    at /usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:497:72 
stdout	    at authenticateStragglers (/usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:443:16) 
stdout	    at Connection.messageHandler (/usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:477:5) 
stdout	    at Socket.<anonymous> (/usr/src/app/node_modules/mongodb-core/lib/connection/connection.js:333:22) 
stdout	    at emitOne (events.js:116:13) 
stdout	    at Socket.emit (events.js:211:7) 
stdout	    at addChunk (_stream_readable.js:263:12) 
stdout	    at readableAddChunk (_stream_readable.js:250:11) 
stdout	    at Socket.Readable.push (_stream_readable.js:208:10) 
stdout	"    at TCP.onread (net.js:601:20) {\error\"":{\""name\"":\""MongoError\"""	"\""message\"":\""Authentication failed.\"""	"\""ok\"":0"	"\""errmsg\"":\""Authentication failed.\"""	"\""code\"":18"	"\""codeName\"":\""AuthenticationFailed\""}"	"\""stack\"":\""MongoError: Authentication failed.\n    at Function.MongoError.create (/usr/src/app/node_modules/mongodb-core/lib/error.js:31:11)\n    at /usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:497:72\n    at authenticateStragglers (/usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:443:16)\n    at Connection.messageHandler (/usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:477:5)\n    at Socket.<anonymous> (/usr/src/app/node_modules/mongodb-core/lib/connection/connection.js:333:22)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:601:20)\"""	"\""exception\"":true"	"\""date\"":\""Thu Mar 14 2019 18:27:14 GMT+0000 (UTC)\"""	"\""process\"":{\""pid\"":16"	"\""uid\"":0"	"\""gid\"":0"	"\""cwd\"":\""/usr/src/app\"""	"\""execPath\"":\""/usr/local/bin/node\"""	"\""version\"":\""v8.15.0\"""	"\""argv\"":[\""/usr/local/bin/node\"""	"\""/usr/src/app/server.js\""]"	"\""memoryUsage\"":{\""rss\"":99233792"	"\""heapTotal\"":87003136"	"\""heapUsed\"":44771896"	"\""external\"":36798750}}"	"\""os\"":{\""loadavg\"":[4.10693359375"	35.791.015.625	3.130859375]	"\""uptime\"":2603765}"	"\""trace\"":[{\""column\"":11"	"\""file\"":\""/usr/src/app/node_modules/mongodb-core/lib/error.js\"""	"\""function\"":\""Function.MongoError.create\"""	"\""line\"":31"	"\""method\"":\""create\"""	"\""native\"":false}"	"{\""column\"":72"	"\""file\"":\""/usr/src/app/node_modules/mongodb-core/lib/connection/pool.js\"""	"\""function\"":null"	"\""line\"":497"	"\""method\"":null"	"\""native\"":false}"	"{\""column\"":16"	"\""file\"":\""/usr/src/app/node_modules/mongodb-core/lib/connection/pool.js\"""	"\""function\"":\""authenticateStragglers\"""	"\""line\"":443"	"\""method\"":null"	"\""native\"":false}"	"{\""column\"":5"	"\""file\"":\""/usr/src/app/node_modules/mongodb-core/lib/connection/pool.js\"""	"\""function\"":\""Connection.messageHandler\"""	"\""line\"":477"	"\""method\"":\""messageHandler\"""	"\""native\"":false}"	"{\""column\"":22"	"\""file\"":\""/usr/src/app/node_modules/mongodb-core/lib/connection/connection.js\"""	"\""function\"":null"	"\""line\"":333"	"\""method\"":null"	"\""native\"":false}"	"{\""column\"":13"	"\""file\"":\""events.js\"""	"\""function\"":\""emitOne\"""	"\""line\"":116"	"\""method\"":null"	"\""native\"":false}"	"{\""column\"":7"	"\""file\"":\""events.js\"""	"\""function\"":\""Socket.emit\"""	"\""line\"":211"	"\""method\"":\""emit\"""	"\""native\"":false}"	"{\""column\"":12"	"\""file\"":\""_stream_readable.js\"""	"\""function\"":\""addChunk\"""	"\""line\"":263"	"\""method\"":null"	"\""native\"":false}"	"{\""column\"":11"	"\""file\"":\""_stream_readable.js\"""	"\""function\"":\""readableAddChunk\"""	"\""line\"":250"	"\""method\"":null"	"\""native\"":false}"	"{\""column\"":10"	"\""file\"":\""_stream_readable.js\"""	"\""function\"":\""Socket.Readable.push\"""	"\""line\"":208"	"\""method\"":\""push\"""	"\""native\"":false}"	"{\""column\"":20"	"\""file\"":\""net.js\"""	"\""function\"":\""TCP.onread\"""	"\""line\"":601"	"\""method\"":\""onread\"""	"\""native\"":false}]"	"\""timestamp\"":\""2019-03-14T18:27:14.275Z\""}"
stdout	"[33mwarn[39m: [Core] MongoDB disconnected! {""timestamp"":""2019-03-14T18:27:14.664Z""}" 
stdout	"[31merror[39m: [Core] MongoDB connection: MongoError: Authentication failed. {""timestamp"":""2019-03-14T18:27:14.669Z""}" 
stdout	"[33mwarn[39m: [GHome API] MQTT reconnect event {""timestamp"":""2019-03-14T18:27:15.308Z""}" 
stdout	"[33mwarn[39m: [Alexa API] MQTT reconnect event {""timestamp"":""2019-03-14T18:27:15.323Z""}" 
stdout	"[33mwarn[39m: [State API] MQTT reconnect event {""timestamp"":""2019-03-14T18:27:15.332Z""}" 
stdout	"[31merror[39m: [GHome API] MQTT connect error {""timestamp"":""2019-03-14T18:27:15.339Z""}" 
stdout	"[31merror[39m: [Alexa API] MQTT connect error {""timestamp"":""2019-03-14T18:27:15.359Z""}" 
stdout	"[31merror[39m: [State API] MQTT connect error {""timestamp"":""2019-03-14T18:27:15.366Z""}" 
stdout	"[33mwarn[39m: [GHome API] MQTT reconnect event {""timestamp"":""2019-03-14T18:27:16.351Z""}" 
stdout	"[33mwarn[39m: [Alexa API] MQTT reconnect event {""timestamp"":""2019-03-14T18:27:16.402Z""}" 
stdout	"[33mwarn[39m: [State API] MQTT reconnect event {""timestamp"":""2019-03-14T18:27:16.410Z""}" 
stdout	"[31merror[39m: [Alexa API] MQTT connect error {""timestamp"":""2019-03-14T18:27:16.527Z""}" 
stdout	"[31merror[39m: [GHome API] MQTT connect error {""timestamp"":""2019-03-14T18:27:16.530Z""}" 
stdout	"[31merror[39m: [State API] MQTT connect error {""timestamp"":""2019-03-14T18:27:16.538Z""}" 
stderr	npm ERR! code ELIFECYCLE 
stderr	npm ERR! errno 1 
stderr	npm ERR! node-red-alexa-home-skill-v3@0.8.0 start: `node server.js` 
stderr	npm ERR! Exit status 1 
stderr	npm ERR!  
stderr	npm ERR! Failed at the node-red-alexa-home-skill-v3@0.8.0 start script. 
stderr	npm ERR! This is probably not a problem with npm. There is likely additional logging output above. 
stderr 	
stderr	npm ERR! A complete log of this run can be found in: 
stderr	npm ERR!     /root/.npm/_logs/2019-03-14T18_27_17_427Z-debug.log

**Comment by Langer75** [comment]
It seems that the MQTT connections fail first. After that the Mongo Authentication Error occurs. But I have no idea why. I also tried the port 1883 for mqtt. But I got the same error. Mongo, mosquitto, redis, nodejs an nginx are installed as docker container as you wrote it in the wiki. I checked also the network. So at least those five should be able to connect each other.

**Comment by Langer75** [comment]
A look in the mongodb log helped a bit. Here I can read the following:

![Error](https://user-images.githubusercontent.com/45699779/54391618-aac38800-46a5-11e9-99de-2aab6ce6244c.PNG)

The SASL SCRUM-SHA-1 authentication failed. What does it mean?

**Comment by Langer75** [comment]
I tried to add the users manually, but the error said that the users are already existing. So the user are existing and I use the right credentials. So what is going wrong here

**Comment by coldfire84** [comment]
Can you share the full docker create run command for the web app instance (ideally in an email).

Usernames/ passwords for MQTT are automatically created on launch and user creation, you should not need to create these manually.

**Comment by Langer75** [comment]
Yes I know. I just want to sure that the users are created correct. I will send you the full docker create run command for the web app instance in an email.

**Comment by Langer75** [comment]
OK I got it. I used the MONGO ADMIN credentials insteed of the WEB USER credentials. It was also a bit misleading in the wiki page. Here you wrote MONGO_USER and MONGO_PASSWORD insteed of WEB_USER and WEB_PASSWORD. I will correct it on the wiki page.

**Comment by Langer75** [comment]
Next step, next challange. I try to Configure Web Service OAuth. But the page does not open. The answer on the request https://<hostname>/admin/services is complete empty. I checked the logs of the nodejs container and mongodb. But there are no errors. I used the WEB_USER credentials. But when I try to login to https://<hostname> first I got an error invalid username and password. After registration of WEB_USER in the webapp I can login but /admin/services does not open. Any idea what I am doing wrong?

**Comment by Langer75** [comment]
ok I got it. It is not the WEB_USER but the MQTT_USER.

**Comment by Langer75** [comment]
Last remark. The index.js in the Lambda.zip is not the current one. So after the import of the zip-file I had to change the content of the index.js manually.

**Comment by coldfire84** [comment]
> Last remark. The index.js in the Lambda.zip is not the current one. So after the import of the zip-file I had to change the content of the index.js manually.

Thanks, I'll update this.

**Comment by coldfire84** [comment]
Updated lambda code.

Note that mqtt container install/ setup has changed (latest mosquitto version), instructions updated to suite. Note you will have to modify your mosquitto conf file as the mosquitto-auth-plug path has changed
```
sudo sed -i "s|/usr/local/src|/usr/local/lib|g" <path and name of config file>
```
Keep an eye on the wiki for changes relating to thew modularised version becoming master/ latest container version. You will need to perform additional updates to your deployment.

**Comment by Langer75** [comment]
Hi

I recently updateted my own deploy to the latest version of mosquitto. Unfortunatly I got now the following while starting the WebApp container

2019-11-22T20:46:41.168+0000 I  COMMAND  [ftdc] serverStatus was very slow: { after basic: 0, after asserts: 0, after connections: 0, after electionMetrics: 0, 
after extra_info: 36, after flowControl: 36, after globalLock: 36, after locks: 36, after logicalSessionRecordCache: 36, after network: 71, after opLatencies: 7
1, after opReadConcernCounters: 71, after opcounters: 71, after opcountersRepl: 71, after oplogTruncation: 89, after repl: 89, after security: 89, after storage
Engine: 157, after tcmalloc: 301, after trafficRecording: 301, after transactions: 301, after transportSecurity: 301, after twoPhaseCommitCoordinator: 301, afte
r wiredTiger: 1160, at end: 1160 }

what does it mean?
In addition the log of the webapp container said, that the connection to mongodb fails:

> node-red-alexa-home-skill-v3@0.7.0 start /usr/src/app
> node index.js

info: [Core] Connecting to MongoDB server: mongodb://mongodb:27017/users {"timestamp":"2019-11-22T20:45:59.767Z"}
info: [Core] Connecting to MongoDB... {"timestamp":"2019-11-22T20:46:00.064Z"}
info: [Core] Log Level set to: debug {"timestamp":"2019-11-22T20:46:30.921Z"}
warn: [Core] No HOMEGRAPH_APIKEY environment variable supplied. New devices, removal or device changes will not show in users Google Home App without this {"timestamp":"2019-11-22T20:46:31.033Z"}
warn: [Security] Using default Cookie Secret, please supply new secret using COOKIE_SECRET environment variable {"timestamp":"2019-11-22T20:46:31.045Z"}
info: [Core] Connecting to MQTT server: mqtt://mosquitto {"timestamp":"2019-11-22T20:46:34.863Z"}
info: [Core] App listening on: 0.0.0.0:3000 {"timestamp":"2019-11-22T20:46:55.751Z"}
info: [Core] App_ID -> http://localhost:3000 {"timestamp":"2019-11-22T20:46:55.765Z"}
warn: [Core] MongoDB disconnected! {"timestamp":"2019-11-22T20:46:56.078Z"}
error: [Core] MongoDB connection: MongoNetworkError: failed to connect to server [mongodb:27017] on first connect [MongoNetworkError: connection 0 to mongodb:27017 timed out] {"timestamp":"2019-11-22T20:46:56.097Z"}
info: [Core] Connecting to Redis server... {"timestamp":"2019-11-22T20:46:59.793Z"}
info: [Core] Redis connection ready! {"timestamp":"2019-11-22T20:47:01.957Z"}

But I do not understand that just in that moment when the error occurs in the Webapp log the mongodb log says that the connection was established:

2019-11-22T20:46:56.169+0000 I  NETWORK  [listener] connection accepted from 172.18.0.1:43311 #3 (1 connection now open)                                        
2019-11-22T20:46:59.519+0000 I  NETWORK  [listener] connection accepted from 172.18.0.1:34284 #4 (2 connections now open)                                       
2019-11-22T20:46:59.640+0000 I  NETWORK  [conn4] received client metadata from 172.18.0.1:34284 conn4: { driver: { name: "mongoc", version: "1.14.0" }, os: { ty
pe: "Linux", name: "Alpine Linux", version: "3.10.1", architecture: "x86_64" }, platform: "cfg=0x221ee069 posix=200809 stdc=201710 CC=GCC 8.3.0 CFLAGS="" LDFLAG
S=""" }                                                                                                                                                         
2019-11-22T20:47:00.157+0000 I  COMMAND  [conn4] command admin.$cmd command: saslStart { saslStart: 1, mechanism: "SCRAM-SHA-256", payload: "xxx", autoAuthorize
: 1, $db: "admin", $readPreference: { mode: "primaryPreferred" } } numYields:0 reslen:196 locks:{} protocol:op_msg 330ms                                        
2019-11-22T20:47:01.709+0000 I  NETWORK  [conn3] received client metadata from 172.18.0.1:43311 conn3: { driver: { name: "nodejs", version: "2.2.36" }, os: { ty
pe: "Linux", name: "linux", architecture: "x64", version: "3.10.105" }, platform: "Node.js v8.15.0, LE, mongodb-core: 2.1.20" }                                 
2019-11-22T20:47:02.326+0000 I  COMMAND  [ftdc] serverStatus was very slow: { after basic: 19, after asserts: 19, after connections: 19, after electionMetrics: 
19, after extra_info: 19, after flowControl: 19, after globalLock: 56, after locks: 56, after logicalSessionRecordCache: 56, after network: 75, after opLatencie
s: 75, after opReadConcernCounters: 75, after opcounters: 75, after opcountersRepl: 75, after oplogTruncation: 75, after repl: 75, after security: 105, after st
orageEngine: 105, after tcmalloc: 231, after trafficRecording: 231, after transactions: 231, after transportSecurity: 318, after twoPhaseCommitCoordinator: 318,
 after wiredTiger: 2183, at end: 2313 }                                                                                                                         
2019-11-22T20:47:04.756+0000 I  ACCESS   [conn4] Successfully authenticated as principal mqttuser on admin from client 172.18.0.1:34284                         
2019-11-22T20:47:05.155+0000 I  ACCESS   [conn3] Successfully authenticated as principal webuser on sessions from client 172.18.0.1:43311                       
2019-11-22T20:47:45.578+0000 I  NETWORK  [conn3] end connection 172.18.0.1:43311 (1 connection now open)      

After that The WebApp log gives  the following error:

error: [Core] MQTT connect error {"timestamp":"2019-11-22T20:47:05.265Z"}
warn: [Core] MQTT reconnect event {"timestamp":"2019-11-22T20:47:06.595Z"}
error: [Core] MQTT connect error {"timestamp":"2019-11-22T20:47:06.677Z"}
warn: [Core] MQTT reconnect event {"timestamp":"2019-11-22T20:47:07.709Z"}

and the mqtt log the following:

error: [Core] MQTT connect error {"timestamp":"2019-11-22T20:47:05.265Z"}
warn: [Core] MQTT reconnect event {"timestamp":"2019-11-22T20:47:06.595Z"}
error: [Core] MQTT connect error {"timestamp":"2019-11-22T20:47:06.677Z"}
warn: [Core] MQTT reconnect event {"timestamp":"2019-11-22T20:47:07.709Z"}

This is repeating until I stop the WebApp container                                                  
Do you have an idea whats going wrong?

**Comment by coldfire84** [comment]
Can you confirm all of the containers / versions you're using (including tags).

> I recently updateted my own deploy to the latest version of mosquitto. 

I assume you used the Mosquitto Container associated with this skill: `coldfire84/mosquitto-auth:development` ?

Regarding the log outputs:

```
2019-11-22T20:47:02.326+0000 I COMMAND [ftdc] serverStatus was very slow:
```

Whats the specification of the compute environment you're using? I tried running this on an EC2 nano instance and found that I often ran into issues when starting services.

```
warn: [Core] MongoDB disconnected! {"timestamp":"2019-11-22T20:46:56.078Z"}
error: [Core] MongoDB connection: MongoNetworkError: failed to connect to server [mongodb:27017] on first connect [MongoNetworkError: connection 0 to mongodb:27017 timed out] {"timestamp":"2019-11-22T20:46:56.097Z"}
```

Are you sure MongoDB is available? This may be related to the above. Have you tried connecting with the mongo CLI using the username/ password and hostname/ port specified in your ENV declarations?

```
error: [Core] MQTT connect error {"timestamp":"2019-11-22T20:47:05.265Z"}
warn: [Core] MQTT reconnect event {"timestamp":"2019-11-22T20:47:06.595Z"}
```

```
1574455657: |-- getuser(mqttuser) AUTHENTICATED=0 by none
```

The user in question isn't being authenticated by mosquitto-auth-plug. This could be associated with a MongoDB issue. Confirm using mosquitto pub/sub commands to see if you can connect outside of the context of the web app.

**Comment by Langer75** [comment]
I use a Synology DS412+ as environment. I also updates the Docker Package and I set up all containers from scratch.

I tried to priorise the the mongodb container. This is possible with the Docker package of Synology. And this works. Now I am able to start the webapp and everything works fine so far. I still have to test if the alexa app is working with the skill as before.

So it seems to be a performance problem. The updated docker version seems to priorise the containers a bit different than before.

I was already thinking of renewing my synology hardware. Now I have a reason more to do that.

Thanks for your time to answer my last comment

**Comment by Langer75** [comment]
I have still a problem with the alexa app. While using it the webapp will crash with the following error:
![grafik](https://user-images.githubusercontent.com/45699779/69487262-e7f83080-0e56-11ea-9f86-d04b6b339604.png)

Something goes wrong with the OAuth.  Do you have an Idea?

**Comment by coldfire84** [comment]
I've updated the development [container image on Docker Hub](https://hub.docker.com/repository/docker/coldfire84/nr-alexav3-web), can you refresh your container with the latest code, or build from source as outlined [here](https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/wiki/Deploy-Your-Own#build-from-source).

The auto-trigger between GitHub and Docker Hub appears to have stopped working at some point so the code wasn't up-to-date. This will make troubleshooting what's going on *much* easier.
