### ISSUE TITLE
Alexa Skill: Spanish es-es Translation

### ISSUE THREAD

**Issue by coldfire84** [coldfire84/node-red-alexa-home-skill-v3-web#6]
Required for Alexa skill enablement in Spanish-speaking markets.

**Comment by coldfire84** [comment]
Translation required:

| Skill Text | English Text | 
| ----|----|
|Public Name | Node-RED Smart Home Control |
|One Sentence Description| Add Alexa voice control to your Smart Home Node-RED Flows|
| Detailed Description| Using this bridge you can control a variety of Node-RED endpoints, such as MQTT, HTTP(S), Yamaha AVRs, Chromecast (anything that has a Node-RED integration). This bridge currently supports Power, Brightness, Colour, Colour Temperature, Input, Lock, Thermostat, Playback, Step Speaker and Scene control. You'll need to follow the instructions here to get up and running: https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/wiki/Use-the-Hosted-Instance|
|Example Phrase 1| Alexa, turn on the lights|
|Example Phrase 2| Alexa, pause Lounge TV|
|Example Phrase 3| Alexa, set AV Receiver to HDMI 2|

**Comment by Rapejim** [comment]
Of course, I can help you with Spanish texts... I am writing this with my smartphone, when I power on my laptop I will help you with the translate of this table.

**Comment by Rapejim** [comment]
Texto de la Skill | Texto en Español
-- | --
Nombre Público | Node-RED Control de Casa Inteligente
Descripción en una frase | Añade el control por voz de Alexa a tus Flujos de trabajo de Node-RED
Descripción Detallada | Usando este puente, tu puedes controlar una gran variedad de salidas de Node-RED, tales como MQTT, HTTP(S), Yamaha AVRs, Chromecast,... (cualquier cosa que tenga integración con Node-RED). Este puente soporta actualmente Encendido/Apagado, Brillo, Color, Temperatura del Color, Cambio de Entrada (AV, HDMI, ...), Cerraduras, Termostatos, control de Reproducción (pausar, parar,...), Altavoces y control de Escenas. Necesitarás seguir las instrucciones del siguiente enlace para hacerlo funcionar: https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/wiki/Use-the-Hosted-Instance
Frase de Ejemplo 1 | Alexa, enciende las luces
Frase de Ejemplo 2 | Alexa, pausa la Televisión del salón
Frase de Ejemplo 3 | Alexa, pon el HDMI 2 en el Receptor de video

**Comment by coldfire84** [comment]
@Rapejim, that's fantastic - thank you! I've updated the sill information for the market place.

**Comment by coldfire84** [comment]
@Rapejim - I've updated the skill  with the revised translation. Thanks.

**Comment by coldfire84** [comment]
@Rapejim , are you able to assist with the Spanish translation for Google Home? https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/issues/46

Thanks!
