### ISSUE TITLE
Feature Question 

### ISSUE THREAD

**Issue by a011528** [coldfire84/node-red-alexa-home-skill-v3-web#60]
I’m desperate for Blind category in Alexa. I can build / control my blinds through a flow and it all works great if I setup the device as a “Other” in your portal (Alexa Blinds Up/Down; Alexa set Shade %). but I’d love the get the Display Category to be Blinds. I don’t think Amazon currently support this name / icon (no idea why not).

Can the “Other” category be renamed somehow through injection ? 
Or does anyone know if a manufacturer / product = brand/model can be injected to force an endpoint to be recognised as a Blind ?

**Comment by coldfire84** [comment]
> I’m desperate for Blind category in Alexa. I can build / control my blinds through a flow and it all works great if I setup the device as a “Other” in your portal (Alexa Blinds Up/Down; Alexa set Shade %). but I’d love the get the Display Category to be Blinds. I don’t think Amazon currently support this name / icon (no idea why not).

Basically, if the device type isn't listed [here](https://developer.amazon.com/docs/device-apis/alexa-discovery.html#display-categories) it is impossible to present it as you wish in Alexa App.

> Can the “Other” category be renamed somehow through injection ?
Or does anyone know if a manufacturer / product = brand/model can be injected to force an endpoint to be recognised as a Blind ?

As per link above, "OTHER" is an Alexa Display Category, so I'm unable to change this in the portal.
