### ISSUE TITLE
Thermostat: How to set actual temperature?

### ISSUE THREAD

**Issue by superpower10** [coldfire84/node-red-alexa-home-skill-v3-web#62]
In the Alexa app I can adjust the temperature of the thermostat. But I can also see the actual temperature measured by the thermostat:

![IMG_1244](https://user-images.githubusercontent.com/20533966/55943805-8f697f80-5c47-11e9-92e1-b38d618f2d6e.PNG)

### This my Node-RED Flow on my CCU3:

<img width="491" alt="Bildschirmfoto 2019-04-11 um 10 46 09" src="https://user-images.githubusercontent.com/20533966/55944025-fe46d880-5c47-11e9-8d66-97c5a112a939.png">
<img width="893" alt="Bildschirmfoto 2019-04-11 um 09 26 45" src="https://user-images.githubusercontent.com/20533966/55943995-f38c4380-5c47-11e9-9468-b5acf35a3168.png">
<img width="410" alt="Bildschirmfoto 2019-04-11 um 10 48 23" src="https://user-images.githubusercontent.com/20533966/55944004-f850f780-5c47-11e9-8b79-9b24330ed204.png">
<img width="509" alt="Bildschirmfoto 2019-04-11 um 10 53 44" src="https://user-images.githubusercontent.com/20533966/55944075-1a4a7a00-5c48-11e9-8e64-3499b48cba4f.png">

**Comment by superpower10** [comment]
I found a way. 👏🏻. The only problem I have no is that the Acknoledge takes to long. Any Ideas?

Here it is
<img width="830" alt="Bildschirmfoto 2019-04-11 um 12 45 02" src="https://user-images.githubusercontent.com/20533966/55951508-b760df00-5c57-11e9-9a8e-8f6bc458c980.png">
<img width="518" alt="Bildschirmfoto 2019-04-11 um 12 45 23" src="https://user-images.githubusercontent.com/20533966/55951516-bb8cfc80-5c57-11e9-9ae9-1a3f8874a647.png">
<img width="498" alt="Bildschirmfoto 2019-04-11 um 12 45 14" src="https://user-images.githubusercontent.com/20533966/55951521-bdef5680-5c57-11e9-8f77-3a1b8d940310.png">

`[{"id":"42576443.13fac4","type":"ccu-get-value","z":"6678f401.ff3e7c","name":"Gemessene Temperatur","ccuConfig":"38263145.35ea0e","iface":"HmIP-RF","channel":"000A18A98B0219:1 Wohnzimmer-Esstisch-Heizung","sysvar":"Alarmmeldungen","sysvarProperty":"value","datapoint":"ACTUAL_TEMPERATURE","datapointProperty":"value","setProp":"extra","setPropType":"msg","x":670,"y":40,"wires":[["ea3e4022.f95a6"]]},{"id":"38263145.35ea0e","type":"ccu-connection","z":"","name":"localhost","host":"localhost","regaEnabled":true,"bcrfEnabled":true,"iprfEnabled":true,"virtEnabled":true,"bcwiEnabled":false,"cuxdEnabled":false,"regaPoll":true,"regaInterval":"30","rpcPingTimeout":"60","rpcInitAddress":"127.0.0.1","rpcServerHost":"127.0.0.1","rpcBinPort":"2047","rpcXmlPort":"2048","queueTimeout":"5000","queuePause":"250","contextStore":""}]`

**Comment by coldfire84** [comment]
Trying to understand the flow - are you trying to send out of band state updates or build outcome validation into a voice-controlled flow before acknowledgement is sent?

To update state you should not need to send _both_ thermostatSetPoint and thermostatSetpointDelta elements, you can just send **thermostatSetPoint** if known, or thermostatSetpointDelta and the bridge will workout what the new value of thermostatSetPoint. 

thermostatSetpointDelta is only used when adjusting the temperature #/- via Alexa App/ voice control. 

In essence:
* To update ambient (measured) temperature use the **temperature** state element
* To update set point (desired/ target temperature) use the **thermostatSetPoint** state element

You can combine both of the above elements in a single update, just avoid sending both thermostatSetPoint and thermostatSetpointDelta.

**Comment by coldfire84** [comment]
Please re-open if you encounter issues with testing/ provide feedback to let me know this is working.

**Comment by conquerxxl** [comment]
I have the same problem. Do you have a solution for this?
