### ISSUE TITLE
What device is a open/close sensor?

### ISSUE THREAD

**Issue by superpower10** [coldfire84/node-red-alexa-home-skill-v3-web#63]
I have a lot of sensors which tell if a window or door is open or closed. What kind of device do I have to setup at [Devices](https://red.cb-net.co.uk/devices)?

**Comment by coldfire84** [comment]
This will require development work to unlock Contact Sensor capability: https://developer.amazon.com/docs/device-apis/alexa-contactsensor.html

**Comment by coldfire84** [comment]
Node-RED contrib 0.4.44 includes support for Contact Sensor state updates, API has been updated to handle requests for state/ state updates and it is now possible to create "Contact Sensor" device types.

Please test and advise on any issues, if you encounter a problem please include Node-RED console output.

**Comment by coldfire84** [comment]
Please re-open if you encounter issues with testing/ provide feedback to let me know this is working.
