### ISSUE TITLE
Alexa routines on state change

### ISSUE THREAD

**Issue by seno666** [coldfire84/node-red-alexa-home-skill-v3-web#66]
Hi,
many thanks for your work. I am using a device with the service you kindly provided. That device is a contact sensor, which I am able to change the state of. The state is also reflected in the Alexa app.

Alexa allows to configure routines which trigger on contact sensor state change. Now, I am using the state node to switch that property, but the Alexa routine never fires.

I'd appreciate any insight or assistance.

I am using this e.g. this message to make it say "locked":
`{"_msgid":"e1a4ca77.eef808","topic":"","payload":{"state":{"contact":"NOT_DETECTED","time":"2019-05-30T19:17:22.122Z"}},"mydate":"Thu May 30 2019","myyear":2019,"mymonth":"May","mydom":30,"myday":"Thu","myhour":21,"mytime":"21:17","mytimes":"21:17:22","myminute":17,"myminutes":"17:22","mysecond":22,"myepoch":1559243842122,"myrawdate":"2019-05-30T19:17:22.122Z","acknowledge":true}`

Thank you and kind regards

**Comment by coldfire84** [comment]
If I'm reading this correctly, state is viewable but you cannot use out of band state changes to trigger Alexa routines? If this is the case #67 explains why.

**Comment by seno666** [comment]
Yes you are reading this correctly. Alright, will close this one.

**Comment by coldfire84** [comment]
Updated the API to send change reports for ContactSensor device types. Please can you test/ provide feedback in #67.
