### ISSUE TITLE
Support for additional MotionSensor, ContactSensor on Alexa

### ISSUE THREAD

**Issue by zyrorl** [coldfire84/node-red-alexa-home-skill-v3-web#67]
It would be great to support these so that we can allow for reporting events triggered by motion sensors (PIR), contact sensors (door open/window open sensors)

**Comment by coldfire84** [comment]
So, contact sensors are already supported, but for state query only. 

I disabled out of band updates for all devices simply due to the huge overhead this had - I'll look at whether I can enable this for contact sensors only (initially) in order for state changes to be used as triggers.

**Comment by coldfire84** [comment]
ContactSensor "Change Reports" are now enabled in the API. This should enable the use of triggers for this device type.

**Comment by coldfire84** [comment]
MotionSensor code drop has now also been completed. This capability also supported Change Reports, which should ensure that trigger functionality works.

**Comment by superpower10** [comment]
Where can I find an example JSON for MotionSensor State?

**Comment by coldfire84** [comment]
Good spot, I've not added a specific motion sensor  state update, but the expected format is called out in the docs: https://red.cb-net.co.uk/docs#expected-state-payload

Replace "contact" with "motion" in your example and you're good to go.
