### ISSUE TITLE
Mq-red.cb-net.co.uk down? 

### ISSUE THREAD

**Issue by seno666** [coldfire84/node-red-alexa-home-skill-v3-web#68]
Currently none of my connections are working. After digging a little, I found that 
mq-red.cb-net.co.uk 
is offline with an SSL error. Would that be related?

Thanks & KR

**Comment by coldfire84** [comment]
I've just tested the service and it is working fine.

>  I found that mq-red.cb-net.co.uk is offline with an SSL error. Would that be related?

You're not able to use a web browser against this resource, this is an MQTT broker - how did you get the error in question?

Have you checked your Node-RED console logs?

**Comment by coldfire84** [comment]
Please re-open when you have more information/ logs. Service appears to be functional for all users.
