### ISSUE TITLE
MQTT credentials

### ISSUE THREAD

**Issue by prabbit237** [coldfire84/node-red-alexa-home-skill-v3-web#70]
Two questions:

1) Is it possible to change the MQTT server to a local one? It seems to break it when I tried that in setting up the input node from Alexa.

2) If not, I'd like to be able to check ALL MQTT traffic in and out of the server (but only ones for me, obviously) using something like MQTT.fx. It'd make it easier troubleshooting and designing flows if I can see the actual traffic back and forth in full and in real-time.

**Comment by coldfire84** [comment]
> Is it possible to change the MQTT server to a local one? It seems to break it when I tried that in setting up the input node from Alexa.

Afraid not, the local MQTT is in effect the integration/ message broker for the service. 

> If not, I'd like to be able to check ALL MQTT traffic in and out of the server (but only ones for me, obviously) using something like MQTT.fx. It'd make it easier troubleshooting and designing flows if I can see the actual traffic back and forth in full and in real-time.

I'll review the possibility / ACL required to enable this. I've not tested connecting directly to the broker outside of the Node-RED config, but you should be able to do this and access your specific messages (access is limited by your credentials due to MQTT auth plugin.

**Comment by coldfire84** [comment]
I have confirmed that you are able to connect to the broker using mosquitto_sub (and see only your messages) using these commands:

```
# Command (triggered when you ask Alexa to do something):
mosquitto_sub -h mq-red.cb-net.co.uk -t 'command/<bridge_username>/#' -v -u <bridge_username> -P '<bridge password>' --capath /etc/ssl/certs --id test-<bridge_username> -p 8883

# Response (triggered after successful handle of a command via Node-RED):
mosquitto_sub -h mq-red.cb-net.co.uk -t 'response/<bridge_username>/#' -v -u <bridge_username> -P '<bridge password>' --capath /etc/ssl/certs --id test-<bridge_username> -p 8883

# State (for out of band state updates sent via Node-RED):
mosquitto_sub -h mq-red.cb-net.co.uk -t 'state/<bridge_username>/#' -v -u <bridge_username> -P '<bridge password>' --capath /etc/ssl/certs --id test-<bridge_username> -p 8883

# Message (for Node-RED warnings sent to user):
mosquitto_sub -h mq-red.cb-net.co.uk -t 'message/<bridge_username>/#' -v -u <bridge_username> -P '<bridge password>' --capath /etc/ssl/certs --id test-<bridge_username> -p 8883
```
