### ISSUE TITLE
Deploy your own: running into errors

### ISSUE THREAD

**Issue by prabbit237** [coldfire84/node-red-alexa-home-skill-v3-web#71]
OK, maybe I'm a total idiot but........I'm having issues with the "deploy your own."

Issue one: Logger.js triggers an error and thus node.js won't start.

    /usr/src/app/config/logger.js:11
                    level: consoleLoglevel,
                           ^

    ReferenceError: consoleLoglevel is not defined

I was able to resolve this by adding a line to define consoleLoglevel:

    const { format, createLogger, transports } = require('winston');
    
    var debug = (process.env.ALEXA_DEBUG || false);
    var consoleLoglevel = "info";       //.............added this line............
    if (debug == "true") {consoleLoglevel = "debug"};
    
    const logger = createLogger({
            transports: [
              // Console Transport
              new transports.Console({
                    level: consoleLoglevel,
                    format: format.combine(

Issue two: When trying to link an account, it's failing and Amazon says the linking failed. In the log files, I'm finding the following:

    verbose: 35.170.33.28 - - [14/Jul/2019:19:28:19 +0000] "POST /api/v1/authorization HTTP/1.1" 404 160 "-" "-"
     {"timestamp":"2019-07-14T19:28:19.601Z"}

I'm not able to find in the code ANYWHERE where there's a handler for the address https:// [servername] /api/v1/authorization. I was expecting a function in index.js starting as:

    app.post('/api/v1/authorization' ............................

and didn't find such. A search for just in ALL of the files from the three repositories results in only one match in the lambda index.js starting with:

    request.post("https://" + process.env.WEB_API_HOSTNAME + "/api/v1/authorization",{

**Comment by coldfire84** [comment]
> Issue one: Logger.js triggers an error and thus node.js won't start.

You're right. I've been running in debug (and thus with the ENV variable ```ALEXA_DEBUG=true``` ) to make tracking issues easier as the skill has grown in both capability and usage, so had yet to encounter this. I'll drop a fix into the code shortly for this, this will be like-for-like with what you have posted above.

> Issue two: When trying to link an account, it's failing and Amazon says the linking failed.

This sounds like the Alexa Skill URL's/ endpoints relating to authentication are not correct in the skill definition/ Alexa Developer Console, these should be:
- Authorization URI: https://\<FQDN\>/auth/start
- Access Token URI: https://\<FQDN\>/auth/exchange

**Comment by coldfire84** [comment]
Please re-open if you were unable to get this working by adjusting the Authorization URI / Access Token URI.
