### ISSUE TITLE
Alexa: state report reach limit

### ISSUE THREAD

**Issue by Ahrenfelde** [coldfire84/node-red-alexa-home-skill-v3-web#73]
Hi,

first: your service is nice and works very well!

second:
when i´m "program" my flows, i still test the flows quite offen. Sadly the limit goal for state reporting is very fast reached.

How many time the service will allow the state report?

A nice thing would be to have the option to enable a debug feature to raise the limit for an hour or so.
Also it would be nice to bring an error message in node red debug to show clearly that the limit is reached.

At the moment it´s not clear why the state is not shown, wrong state reporting(wrong formatted message) or limit reached.

Greetings

**Comment by coldfire84** [comment]
The primary issue here is the Alexa App, it polls every 2-3 seconds - even if the device in question is configured for state reporting (i.e. out of band updates). I have engaged Amazon on this and they have given feedback to the Alexa Team on making this customisable. 

To answer your questions:

> How many time the service will allow the state report?

100 times in an hour, **per device. ** In reality this is a lot of changes in state/ 3 minutes of having the Alexa App constantly open on a single device.

> [..] it would be nice to bring an error message in node red debug to show clearly that the limit is reached.

You should get feedback in Node-RED, as per https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/issues/51#issuecomment-483057236 

I'd consider using the mosquitto_sub command to review your MQTT traffic, this should make troubleshooting state updates easier. Commands are outlined in https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/issues/70#issuecomment-513585239

> At the moment it´s not clear why the state is not shown, wrong state reporting(wrong formatted message) or limit reached.

You should be able to determine why the state update failed in the Node-RED debug console, see https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/issues/51#issuecomment-483014562

**Comment by Ahrenfelde** [comment]
HI,

thank you. It seems, that i am not the first one with this specific "problem" :)

I think we can close here. I will give this solution above a shot an try it. 
bye
