### ISSUE TITLE
Migration v2 v3

### ISSUE THREAD

**Issue by Seymour77** [coldfire84/node-red-alexa-home-skill-v3-web#74]
Hi, I'm trying to migrate from v2 to v3, I use knxeasy palette, with v2 when I give a command to a knx light for the ON it gives the TRUE command and for OFF FALSE while on the V3 it sends command ON and OFF to datapoint DPT_switch and it doesn't work, I need the skill to give command true and false, how can I do?
Thanks

**Comment by coldfire84** [comment]
Can you use a Change Node? Look for 'ON' and change to 'TRUE', look for 'OFF' and change to 'FALSE'?

**Comment by Seymour77** [comment]
Yes it works, Thank you
