### ISSUE TITLE
SSL Cert expired on mq-red.cb-net.co.uk

### ISSUE THREAD

**Issue by startrk1995** [coldfire84/node-red-alexa-home-skill-v3-web#75]
It redirects to https://nr-alexav3.cb-net.co.uk which has an invalid ssl cert.

Error 526 Ray ID: 50f4b08c6a73e0f6 • 2019-09-01 05:02:01 UTC
Invalid SSL certificate

**Comment by zyrorl** [comment]
Also having same problem, hopefully will rectify soon

**Comment by coldfire84** [comment]
I'll check this when I get home in a couple of hours. You shouldn't be able to browse to https://mq-red.cb-net.co.uk. this is MQTT endpoint only, but shares IP of Web API which is why you're getting the odd behaviour in the browser.

Certificates should auto-renew via certbot.

Other than the browser behaviour what are you seeing in terms of behaviour?

**Comment by zyrorl** [comment]
None of the alexa skills are working arm @coldfire84

**Comment by coldfire84** [comment]
> None of the alexa skills are working arm @coldfire84

OK, I'm back and can confirm that the skill *is* working (at least for me/ the ~40 devices I have configured). Certificates are valid (ignore the error on https://mq-red.cb-net.co.uk this is becuase your trying to browse to an MQTT-only endpoint and NGINX is configured to listen on the IP as well, so you hit the default listener which is https://red.cb-net.co.uk and this doesn't match the requested host-name).

Can you please share output from Node-RED console.

**Comment by startrk1995** [comment]
When I try to update and deploy the configuration node.
Username: st******95
Password: ********
MQTT Hostname: mq-red.cb-net.co.uk
Web API Hostname: red.cb-net.co.uk

Hit Deploy and this is what NR says:
Deploy failed:
502 Bad Gateway
nginx

Output of a Catch All Node:
Error: certificate has expired

**Comment by startrk1995** [comment]
Here is what I have in the configuration node:
Username:  st*********95
Password: ************
MQTT Hostname:  mq-red.cb-net.co.uk
Web API Hostname: red.cb-net.co.uk

When I hit deploy this is the error NR says:

Deploy failed:
502 Bad Gateway
nginx

In NR with a catch all node I get the following:

Error: certificate has expired

**Comment by startrk1995** [comment]
All the nodes for this skill say "disconnected" then "reconnecting".  Every minute or so.

**Comment by coldfire84** [comment]
@startrk1995 can you please share:
- nslookup/ dig for **red.cb-net.co.uk** from device running Node-RED itself, should return:
```
red.cb-net.co.uk.       291     IN      A       104.28.24.58
red.cb-net.co.uk.       291     IN      A       104.28.25.58
```
- nslookup/ dig for **mq-red.cb-net.co.uk** from device running Node-RED itself, should return the below (note this is different to IP address returned for mq-red.cb-net.co.uk as web API is fronted by Cloud Flare):
```
mq-red.cb-net.co.uk.    300     IN      A       35.237.191.52
```
- output from Node-RED console, i.e. if docker ```sudo docker logs -f --tail 200 <container name>``` especially as you apply the configuration. Anything just before/ after and including the below lines (ensure you zero-out username/ password!):
```
httpAdmin post { id: 'd600f657.2b1298',
  user: '<username>',
  pass: '<password>',
  mqtt: 'mq-red.cb-net.co.uk',
  webapi: 'red.cb-net.co.uk' }
```
- version of Node-RED you are running/ how it is running (i.e. Docker, native install etc) and architecture
- version of the node-red-contrib you are using with this skill (should be 0.4.53)

@zyrorl can you please share the same information.

**Comment by coldfire84** [comment]
For my own sanity you can verify certificate validity here (back-end):
```
Found the following certs:
  Certificate Name: mq-red.cb-net.co.uk
    Domains: mq-red.cb-net.co.uk
    Expiry Date: 2019-10-31 01:27:13+00:00 (VALID: 59 days)
    Certificate Path: /etc/letsencrypt/live/mq-red.cb-net.co.uk/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/mq-red.cb-net.co.uk/privkey.pem
  Certificate Name: red.cb-net.co.uk
    Domains: red.cb-net.co.uk
    Expiry Date: 2019-10-31 01:28:24+00:00 (VALID: 59 days)
    Certificate Path: /etc/letsencrypt/live/red.cb-net.co.uk/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/red.cb-net.co.uk/privkey.pem
```

Front-end (CloudFlare SSL fronted):
- https://www.ssllabs.com/ssltest/analyze.html?d=red.cb%2dnet.co.uk&s=104.28.25.58&latest
- https://www.ssllabs.com/ssltest/analyze.html?d=red.cb%2dnet.co.uk&s=104.28.24.58&latest

**Comment by startrk1995** [comment]
Here is the requested info:  
DIG:
`# dig red.cb-net.co.uk

; <<>> DiG 9.14.3 <<>> red.cb-net.co.uk
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35195
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;red.cb-net.co.uk.              IN      A

;; ANSWER SECTION:
red.cb-net.co.uk.       300     IN      A       104.28.25.58
red.cb-net.co.uk.       300     IN      A       104.28.24.58

;; Query time: 29 msec
;; SERVER: 127.0.0.11#53(127.0.0.11)
;; WHEN: Sun Sep 01 10:44:21 EDT 2019
;; MSG SIZE  rcvd: 77

# dig mq-red.cb-net.co.uk

; <<>> DiG 9.14.3 <<>> mq-red.cb-net.co.uk
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31816
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;mq-red.cb-net.co.uk.           IN      A

;; ANSWER SECTION:
mq-red.cb-net.co.uk.    300     IN      A       35.237.191.52

;; Query time: 28 msec
;; SERVER: 127.0.0.11#53(127.0.0.11)
;; WHEN: Sun Sep 01 10:44:35 EDT 2019
;; MSG SIZE  rcvd: 64
`
Logs:
`httpAdmin post { id: 'aa9083ad.6c799',
  user: 'xxxxxxxxxx',
  pass: '__PWRD__',
  mqtt: 'mq-red.cb-net.co.uk',
  webapi: 'red.cb-net.co.uk' }
Error: getDevices status code: 401
Error: getDevices returned data: undefined
1 Sep 10:48:47 - [red] Uncaught Exception:
1 Sep 10:48:47 - SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.res.on (/config/node-red/node_modules/node-red-contrib-alexa-smart-home/alexa.js:907:37)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[01/Sep/2019:10:48:47 -0400] 101 72.246.0.12, 10.21.0.6, 172.30.32.1(172.30.32.2) GET /comms HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36)
2019/09/01 10:48:47 [error] 564#564: *6547 upstream prematurely closed connection while reading response header from upstream, client: 172.30.32.2, server: a0d7b954-nodered, request: "POST /alexa-smart-home-v3/new-account HTTP/1.1", upstream: "http://127.0.0.1:46836/alexa-smart-home-v3/new-account", host: "hassio.xxxxxx.xxxxxx", referrer: "https://hassio.xxxxxx.xxxxxx/api/hassio_ingress/I5lTHxxxxxx.xxxxxxY/"
[01/Sep/2019:10:48:47 -0400] 502 72.246.0.54, 10.21.0.6, 172.30.32.1(172.30.32.2) POST /alexa-smart-home-v3/new-account HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hassio-addon-node-red@ start: `node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hassio-addon-node-red@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-01T14_48_47_536Z-debug.log
`

**Comment by startrk1995** [comment]
Just FYI.  I don't know if you changed anything but I get "connected" now and only get the bad gateway on the first try to deploy.  Let me test to see if the alexa works.

**Comment by startrk1995** [comment]
It is working...  Did you change anything or is it just me?

**Comment by coldfire84** [comment]
Nothing changed... I'm now more confused than I was. It looks as if the config node didn't like the response from the server (likely the device list) but this doesn't explain the MQTT reconnect issue.

**Comment by startrk1995** [comment]
It is all working now..  So strange.  Thank you for all your effort and time as well as a wonderful tool!!  Keep up the good work.

**Comment by jimmycd** [comment]
and again ....
