### ISSUE TITLE
Alexa - Devices not responding

### ISSUE THREAD

**Issue by non092** [coldfire84/node-red-alexa-home-skill-v3-web#76]
Hi,
Since yesterday all my device are not responding (mainly lights)
State reporting (for temperature sensor or doors contact) is working.

Not sure where to look, I've tried recreating the devices then running the Alexa discovery again.
Checked credentials in the node red node, added a debug node : nothing is received in node red upon trying to turn on/off a light.

**Comment by coldfire84** [comment]
Can you check/ share output from Node-RED console itself - 
* If using Docker version of Node-RED use the command ```sudo docker logs -f --tail 200 <container name>``` 
* If using a traditionally installed version use ```tail``` to review Node-RED log output

You can also check whether commands are hitting the skill using mosquitto_sub:
```mosquitto_sub -h mq-red.cb-net.co.uk -t '#' -v -u <bridge_username> -P '<bridge password>' --capath /etc/ssl/certs --id test-<bridge_username> -p 8883```

Can you also confirm your geographic region (i.e. Europe/ Americas/ Asia/ Australia) and username.

**Comment by non092** [comment]
Logs are not showing anything useful, state reporting is working as shown in the logs.
When I try to run on/off a light nothing is logged :

`16 Sep 20:24:09 - [info] [alexa-smart-home-v3-conf:eb64edd2.49d918] Temperature Jardin : sending state update, topic:state/non092/1984 message:{"messageId":"d4918667-c820-48c5-be6f-7107917c7b8c","payload":{"state":{"temperature":23}}}
16 Sep 20:32:54 - [info] [alexa-smart-home-v3-state:Temperature Jardin] Temperature Jardin state node: discarded duplicate state payload
16 Sep 20:32:55 - [info] [alexa-smart-home-v3-conf:eb64edd2.49d918] Temperature Salon : sending state update, topic:state/non092/1983 message:{"messageId":"acc55fc8-5cca-47a4-b1d3-429cdd9aec4e","payload":{"state":{"temperature":23.7}}}
16 Sep 20:32:55 - [info] [alexa-smart-home-v3-conf:eb64edd2.49d918] Temperature Chambre : sending state update, topic:state/non092/1982 message:{"messageId":"b48fbef8-9226-4f43-a479-601f08ed6215","payload":{"state":{"temperature":24.6}}}
16 Sep 20:40:19 - [info] [alexa-smart-home-v3-conf:eb64edd2.49d918] Temperature Chambre : sending state update, topic:state/non092/1982 message:{"messageId":"234db71f-0804-49e0-8e81-5240cb7c1e5c","payload":{"state":{"temperature":24.5}}}
16 Sep 20:50:04 - [info] [alexa-smart-home-v3-conf:eb64edd2.49d918] Temperature Jardin : sending state update, topic:state/non092/1984 message:{"messageId":"a1fad5a9-8b1c-49e0-b85a-442358e5a7c2","payload":{"state":{"temperature":22.7}}}`

Looks like the command are received by the MQTT broker :
`command/non092/1992 {"directive":{"header":{"namespace":"Alexa.PowerController","name":"TurnOff","payloadVersion":"3","messageId":"7987101b-ad87-4ab9-98ac-ea0372edfe67"},"endpoint":{"scope":{"type":"BearerToken"},"endpointId":"1992","cookie":{}},"payload":{}}}
command/non092/1986 {"directive":{"header":{"namespace":"Alexa.PowerController","name":"TurnOff","payloadVersion":"3","messageId":"6d5b84e0-26ff-49b7-8a4c-7e8760ad57fa"},"endpoint":{"scope":{"type":"BearerToken"},"endpointId":"1986","cookie":{}},"payload":{}}}
command/non092/1992 {"directive":{"header":{"namespace":"Alexa.PowerController","name":"TurnOn","payloadVersion":"3","messageId":"09388176-444f-4ac6-9b8b-c8226d3989ac"},"endpoint":{"scope":{"type":"BearerToken"},"endpointId":"1992","cookie":{}},"payload":{}}}`

My username is non092 and I'm in Europe

**Comment by coldfire84** [comment]
I've adjusted the logging in the API to capture user-specific info on MQTT timeouts. Can you try some additional commands via Alexa so I can review the logs.

**Comment by non092** [comment]
Done, just sent 3 commands

**Comment by coldfire84** [comment]
I can see all three commands, and that they all timed out as far as the API is concerned, which means the MQTT client used by the skill-specific Node-RED nodes is not acknowledging / responding to the commands. This means the issue is somewhere on your Node-RED instance.

Can you restart the Node-RED instance and capture the logs from the example below, to the first instance of a state update being sent/ try to initiate a command.
```
Welcome to Node-RED
===================

16 Sep 21:05:17 - [info] Node-RED version: v0.20.8

```

**Comment by non092** [comment]
Logs where not showing anything useful and state reporting stopped working too.
I reinstalled the the node red node and also uninstalled completely the node used for v2.
It is now working again, not sure what happened but thanks for your help :)

**Comment by non092** [comment]
Opening the issue again
After a full restart of my system yesterday it is happening again.
I’m away from home for the next week, the wife wasn’t happy when it stopped working lol
Any issue on your side since yesterday ?

**Comment by non092** [comment]
It seems that removing the configuration node and adding the account again the selecting the account again for each device fix the issue
It happens every time I restart or update my node red container
Somehow the mqtt client doesn’t work until this is done

**Comment by coldfire84** [comment]
Not sure I fully understand whats happening here, are you able to join Slack chat to share more info/ importantly log snippets, link in #83 ?

**Comment by coldfire84** [comment]
I've re-jigged username storage for the Config Node (changes do not affect passwords), see commit for details: https://github.com/coldfire84/node-red-contrib-alexa-home-skill-v3/commit/b9001e0dd2382699093f66a0f1e2661609da87e0

Update the associated Nodes for this skill to version 0.4.58 (or later) to get these changes.

**Comment by non092** [comment]
I confirm the changes to credentials storage fixed it !
Thanks
