### ISSUE TITLE
I have a question on the istallation 

### ISSUE THREAD

**Issue by gsignorini** [coldfire84/node-red-alexa-home-skill-v3-web#79]
My question is: I must put the contnent of git in this directory?
/var/docker/nginx/www

**Comment by coldfire84** [comment]
Please follow the instructions here to deploy this service: https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/wiki/Deploy-Your-Own

Workloads are containerized to enable a relatively straight forwards deployment. 

Also, you don't need to deploy your own instance, you can use the instance here: https://red.cb-net.co.uk/
