### ISSUE TITLE
How to install the latest release?

### ISSUE THREAD

**Issue by Ahrenfelde** [coldfire84/node-red-alexa-home-skill-v3-web#80]
Hello,

i woundering about the release strategy?!

Node-red show me the 0.4.56 as latest release, but in github the Number is 0.10

How can i Update the Adapter?

Reason:
I am in trouble with the Thermostat Controller. 
I checked the box for Modes ON an OFF, but my Alexa says this mode is not possible when i say: "Switch heating off/on".

I can send OFF an ON as state and this works.

Greetings
Jan

**Comment by coldfire84** [comment]
> i woundering about the release strategy?!
Node-red show me the 0.4.56 as latest release, but in github the Number is  0.10

So there are several components:

- Web API (release 0.10)
- Node-RED Nodes (release 0.4.56, shown in Node-RED pallet)
- Lambda Function

In time I will look to co-version, as I agree it is confusing/ an unnecessary differentiation.

> I am in trouble with the Thermostat Controller.
I checked the box for Modes ON an OFF, but my Alexa says this mode is not possible when i say: "Switch heating off/on".

IIRC Alexa doe not support the "ON" mode: https://developer.amazon.com/docs/device-apis/alexa-property-schemas.html#thermostat-mode. The skill is designed to work with both GoogleHome and Alexa, hence there is support for ON. If only Alexa and Google offered similar capabilities in terms of device states.

![image](https://user-images.githubusercontent.com/22571742/68607896-9f7d6200-04a9-11ea-8730-e2830fb3b4a1.png)

When you create the thermostat device "ON" is delineated as being Google Home-specific.
