### ISSUE TITLE
Homematic and Responce 

### ISSUE THREAD

**Issue by Blackei** [coldfire84/node-red-alexa-home-skill-v3-web#81]
Hi,

is it possible to get a ready Flow with a Switch / Dimmer / Shutters with a Responce to Alexa?
I have Problems with the korrekt State.
The Hometic Switches are working with True / False 

Switch on:
`{"topic":"localhost/BidCos-RF/MEQ0361868:1/STATE","payload":true,"ccu":"localhost","iface":"BidCos-RF","device":"MEQ0361868","deviceName":"SA Wohnzimmer","deviceType":"HM-LC-Sw1-FM","channel":"MEQ0361868:1","channelName":"Licht Wohnzimmer","channelType":"SWITCH","channelIndex":1,"datapoint":"STATE","datapointName":"BidCos-RF.MEQ0361868:1.STATE","datapointType":"BOOL","datapointMin":false,"datapointMax":true,"datapointDefault":false,"datapointControl":"SWITCH.STATE","value":true,"valuePrevious":false,"valueStable":true,"rooms":["Haus","Wohnzimmer"],"room":"Haus","functions":["Licht"],"function":"Licht","ts":1572410503201,"tsPrevious":1572410473000,"lc":1572410503201,"change":true,"cache":false,"uncertain":false,"working":false,"stable":true,"_msgid":"8c2375c4.863ed8"}`

Switch OFF:
`{"topic":"localhost/BidCos-RF/MEQ0361868:1/STATE","payload":false,"ccu":"localhost","iface":"BidCos-RF","device":"MEQ0361868","deviceName":"SA Wohnzimmer","deviceType":"HM-LC-Sw1-FM","channel":"MEQ0361868:1","channelName":"Licht Wohnzimmer","channelType":"SWITCH","channelIndex":1,"datapoint":"STATE","datapointName":"BidCos-RF.MEQ0361868:1.STATE","datapointType":"BOOL","datapointMin":false,"datapointMax":true,"datapointDefault":false,"datapointControl":"SWITCH.STATE","value":false,"valuePrevious":true,"valueStable":false,"rooms":["Haus","Wohnzimmer"],"room":"Haus","functions":["Licht"],"function":"Licht","ts":1572410564733,"tsPrevious":1572410503201,"lc":1572410564733,"change":true,"cache":false,"uncertain":false,"working":false,"stable":true,"_msgid":"d1058baf.4c3ab8"}`

Shutter:

Down:

`{"topic":"localhost/BidCos-RF/MEQ0515907:1/LEVEL","payload":0,"ccu":"localhost","iface":"BidCos-RF","device":"MEQ0515907","deviceName":"RA Rolladen Schlafzimmer","deviceType":"HM-LC-Bl1-FM","channel":"MEQ0515907:1","channelName":"Rollladen Schlafzimmer","channelType":"BLIND","channelIndex":1,"datapoint":"LEVEL","datapointName":"BidCos-RF.MEQ0515907:1.LEVEL","datapointType":"FLOAT","datapointMin":0,"datapointMax":1,"datapointDefault":0,"datapointControl":"BLIND.LEVEL","value":0,"valuePrevious":1,"valueStable":0,"rooms":["Haus","Schlafzimmer"],"room":"Haus","functions":["Rolladen"],"function":"Rolladen","ts":1572410760321,"tsPrevious":1572410731773,"lc":1572410760321,"change":true,"cache":false,"uncertain":false,"working":false,"direction":0,"stable":true,"_msgid":"91cd211d.d88ab"}`

Shutters up:

``{"topic":"localhost/BidCos-RF/MEQ0515907:1/LEVEL","payload":1,"ccu":"localhost","iface":"BidCos-RF","device":"MEQ0515907","deviceName":"RA Rolladen Schlafzimmer","deviceType":"HM-LC-Bl1-FM","channel":"MEQ0515907:1","channelName":"Rollladen Schlafzimmer","channelType":"BLIND","channelIndex":1,"datapoint":"LEVEL","datapointName":"BidCos-RF.MEQ0515907:1.LEVEL","datapointType":"FLOAT","datapointMin":0,"datapointMax":1,"datapointDefault":0,"datapointControl":"BLIND.LEVEL","value":1,"valuePrevious":0.405,"valueStable":1,"rooms":["Haus","Schlafzimmer"],"room":"Haus","functions":["Rolladen"],"function":"Rolladen","ts":1572410846181,"tsPrevious":1572410825560,"lc":1572410846181,"change":true,"cache":false,"uncertain":false,"working":false,"direction":0,"stable":true,"_msgid":"db731ab6.c09028"}

Dimmer:

ON:

`{"topic":"localhost/BidCos-RF/MEQ0081427:1/LEVEL","payload":1,"ccu":"localhost","iface":"BidCos-RF","device":"MEQ0081427","deviceName":"DA Schlafzimmer Dimmer","deviceType":"HM-LC-Dim1T-FM","channel":"MEQ0081427:1","channelName":"Schlafzimmer Dimmer","channelType":"DIMMER","channelIndex":1,"datapoint":"LEVEL","datapointName":"BidCos-RF.MEQ0081427:1.LEVEL","datapointType":"FLOAT","datapointMin":0,"datapointMax":1,"datapointDefault":0,"datapointControl":"DIMMER.LEVEL","value":1,"valuePrevious":0.005,"valueStable":1,"rooms":["Haus","Schlafzimmer"],"room":"Haus","functions":["Licht"],"function":"Licht","ts":1572410942859,"tsPrevious":1572410939688,"lc":1572410942859,"change":true,"cache":false,"uncertain":false,"working":false,"direction":0,"stable":true,"_msgid":"244fb88f.90b148"}

OFF:
`{"topic":"localhost/BidCos-RF/MEQ0081427:1/LEVEL","payload":1,"ccu":"localhost","iface":"BidCos-RF","device":"MEQ0081427","deviceName":"DA Schlafzimmer Dimmer","deviceType":"HM-LC-Dim1T-FM","channel":"MEQ0081427:1","channelName":"Schlafzimmer Dimmer","channelType":"DIMMER","channelIndex":1,"datapoint":"LEVEL","datapointName":"BidCos-RF.MEQ0081427:1.LEVEL","datapointType":"FLOAT","datapointMin":0,"datapointMax":1,"datapointDefault":0,"datapointControl":"DIMMER.LEVEL","value":1,"valuePrevious":0.005,"valueStable":1,"rooms":["Haus","Schlafzimmer"],"room":"Haus","functions":["Licht"],"function":"Licht","ts":1572410942859,"tsPrevious":1572410939688,"lc":1572410942859,"change":true,"cache":false,"uncertain":false,"working":false,"direction":0,"stable":true,"_msgid":"244fb88f.90b148"}`

ForThermostate here is a finsihed Flow:

[{"id":"726ca8a8.11ec6","type":"alexa-smart-home-v3","z":"975e9204.e07bd","conf":"de4d137.92ff97","device":"3261","acknowledge":true,"name":"Wohnzimmerheizung","topic":"","x":120,"y":100,"wires":[["fdf9bfad.3e2908"]]},{"id":"fdf9bfad.3e2908","type":"ccu-value","z":"975e9204.e07bd","name":"Wohnzimmer-Heizung-Temperatur-einstellen","iface":"VirtualDevices","channel":"INT0000002:1 Neue Gruppe INT0000002:1","datapoint":"SET_TEMPERATURE","mode":"","start":true,"change":false,"cache":true,"queue":false,"on":0,"onType":"undefined","ramp":0,"rampType":"undefined","working":true,"ccuConfig":"38263145.35ea0e","topic":"","x":470,"y":100,"wires":[["6e8ec690.6f559"]]},{"id":"35cbbc5f.8096dc","type":"alexa-smart-home-v3-state","z":"975e9204.e07bd","conf":"de4d137.92ff97","device":"3261","name":"Wohnzimmerheizung","x":875,"y":100,"wires":[],"icon":"font-awesome/fa-thermometer-2","l":false},{"id":"6e8ec690.6f559","type":"change","z":"975e9204.e07bd","name":"OK","rules":[{"t":"move","p":"payload","pt":"msg","to":"payload.value","tot":"msg"},{"t":"set","p":"payload.state","pt":"msg","to":"{\"thermostatMode\":\"HEAT\"}","tot":"json"},{"t":"set","p":"acknowledge","pt":"msg","to":"true","tot":"bool"},{"t":"set","p":"payload.state.thermostatSetPoint","pt":"msg","to":"payload.value","tot":"msg"},{"t":"set","p":"payload.state.targetSetpointDelta","pt":"msg","to":"value > valuePrevious ? (value-valuePrevious) : ((valuePrevious-value)*(-1))","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":735,"y":100,"wires":[["35cbbc5f.8096dc"]],"icon":"font-awesome/fa-thumbs-up","l":false},{"id":"de4d137.92ff97","type":"alexa-smart-home-v3-conf","z":"","username":"Blackeye","mqttserver":"mq-red.cb-net.co.uk","webapiurl":"red.cb-net.co.uk"},{"id":"38263145.35ea0e","type":"ccu-connection","z":"","name":"localhost","host":"localhost","regaEnabled":true,"bcrfEnabled":true,"iprfEnabled":true,"virtEnabled":true,"bcwiEnabled":false,"cuxdEnabled":false,"regaPoll":true,"regaInterval":"30","rpcPingTimeout":"60","rpcInitAddress":"127.0.0.1","rpcServerHost":"127.0.0.1","rpcBinPort":"2047","rpcXmlPort":"2048"}]

Thank you very much......

**Comment by coldfire84** [comment]
Can you elaborate want you're looking for - are you looking for me to create a pre-defined flow to work with your devices?

I'm unable to import your example flow, I get the error:
```
SyntaxError: Unexpected token t in JSON at position 1090
sg","to":"{"thermostatMo
```
I/m afraid I know little about Hometic. Where is your state information/ payload coming from, via MQTT or web or another interface? 

At a guess though:
* Switch state: `SWITCH.STATE` looks to be the relevant payload for `msg.payload.state.power` - you'll need to use a function to translate `true` to 'ON' and `false` to 'OFF'
* Dimmer: `DIMMER.LEVEL` looks to be the relevant payload for `msg.payload.state.brightness` - you'll need to use a function to translate value that I assume range from `0.000` to `1.000` into `0-100`
* Blind level: there is no direct support for blinds (yet, I can see Google now support this device type). If you're looking to track ON and OFF as a 'pseudo' device, then I would look to use a function to translate `BLIND.LEVEL` and use msg.payload.state.power

**Comment by coldfire84** [comment]
Please re-open with additional information if you still need help.
