### ISSUE TITLE
can't get past the account linking stage

### ISSUE THREAD

**Issue by paul-gordon** [coldfire84/node-red-alexa-home-skill-v3-web#83]
Hi, I've just been pointed at this skill, & really want to try it out. I created an account via the website, but when trying to enable the skill in the Alexa app, it resolutely refuses to accept the account details - just says incorrect email or password. I know for sure that I'm not entering incorrect account details, I even changed the password once via the "my account" page on the website just to be sure...

**Comment by coldfire84** [comment]
Hi @paul-gordon can you join the Slack group here: https://join.slack.com/t/cb-net/shared_invite/enQtODI5OTA2OTEyNDMyLWQwNmQzY2M0NWU3YjQzM2MyOGNhZjU2MTJjYmJjOWEyMDE5NzVmZThlMTI2YmFjNWY0Njc0NGM4ZTY1M2M4NGM

Will need you to share account details and this we we can do via DM.

**Comment by paul-gordon** [comment]
I've joined the Slack group and posted an update there. TL:DR Issue is solved, details are in the #node-red-smart-home channel over there... Cheers.
