### ISSUE TITLE
lost connection from alexa app 2 nodered

### ISSUE THREAD

**Issue by polofahrer00** [coldfire84/node-red-alexa-home-skill-v3-web#85]
skill was working for 2 days now lost connection ( no response from device )  I create a new account  and  register in alexa app same problem.

**Comment by coldfire84** [comment]
Can you share logs from Node-RED console please.

**Comment by polofahrer00** [comment]
here a part:

,29 Nov 17:02:27 - [debug] Flushing localfilesystem context scope
186fdd88.4ff572:b2e50e6a.b9ce38
,29 Nov 17:02:27 - [debug] Flushing localfilesystem context scope global
,29 Nov 17:02:51 - [info] [alexa-smart-home-v3-conf:5818c012.afb568] Garten
: sending state update, topic:state/polofahrer00/4186
message:{"messageId":"e4f18410-0761-44d1-acdf-b06dccfeadfd","payload":{"state":{"temperature":2.7}}}
,29 Nov 17:04:18 - [info] [alexa-smart-home-v3-state:Wc] Timer throttled/
deleted state update: 14f01f44-92d1-4569-867e-951dd45e02da
,29 Nov 17:04:19 - [info] [alexa-smart-home-v3-conf:5818c012.afb568] Wc :
sending state update, topic:state/polofahrer00/4187
message:{"messageId":"3b19ca97-3f34-4978-b1f1-ff93d26dbb76","payload":{"state":{"temperature":17.3,"thermostatMode":"auto","thermostatSetPoint":21}}}
,29 Nov 17:04:47 - [info] [alexa-smart-home-v3-conf:5818c012.afb568]
Kollektor : sending state update, topic:state/polofahrer00/4193
message:{"messageId":"b189022c-36e7-48ee-847e-447c77754e92","payload":{"state":{"temperature":9}}}
,29 Nov 17:04:47 - [info] [alexa-smart-home-v3-conf:5818c012.afb568]
Heizungsrücklauf : sending state update, topic:state/polofahrer00/4191
message:{"messageId":"0679d549-d215-4c62-9e52-a0cefc802e2c","payload":{"state":{"temperature":18.5}}}
,29 Nov 17:04:47 - [info] [alexa-smart-home-v3-conf:5818c012.afb568]
Heizungsvorlauf : sending state update, topic:state/polofahrer00/4190
message:{"messageId":"04aef596-16f4-4bf8-9478-d2563d0ae7c5","payload":{"state":{"temperature":35}}}
,29 Nov 17:06:48 - [info] [alexa-smart-home-v3-conf:5818c012.afb568]
Heizungsvorlauf : sending state update, topic:state/polofahrer00/4190
message:{"messageId":"78bbc734-37ef-4da2-8048-084917d73987","payload":{"state":{"temperature":33.5}}}

,29 Nov 17:08:18 - [info] [alexa-smart-home-v3-conf:5818c012.afb568] Flur :
sending state update, topic:state/polofahrer00/4188
message:{"messageId":"eecb9e99-2f0c-4851-8033-9191dfd41d6e","payload":{"state":{"temperature":17.5,"thermostatMode":"MANUAL","thermostatSetPoint":21}}}
,29 Nov 17:08:49 - [info] [alexa-smart-home-v3-conf:5818c012.afb568]
Brauchwasser : sending state update, topic:state/polofahrer00/4192
message:{"messageId":"d43c85a6-1ed4-4fe0-93f6-3b9a4c5c9b0a","payload":{"state":{"temperature":52}}}
,29 Nov 17:08:49 - [info] [alexa-smart-home-v3-conf:5818c012.afb568]
Heizungsvorlauf : sending state update, topic:state/polofahrer00/4190
message:{"messageId":"f05759f1-e9a2-4e8e-8b1b-f08a84085415","payload":{"state":{"temperature":33}}}
,29 Nov 17:08:49 - [info] [alexa-smart-home-v3-conf:5818c012.afb568]
Rücklaufanhebung : sending state update, topic:state/polofahrer00/4194
message:{"messageId":"b97f5327-0809-4416-b840-1134599f3c44","payload":{"state":{"temperature":33.5}}}
,29 Nov 17:10:50 - [info] [alexa-smart-home-v3-conf:5818c012.afb568]
Kollektor : sending state update, topic:state/polofahrer00/4193
message:{"messageId":"fe060bde-7574-40a0-9b74-0cf8f8ed149b","payload":{"state":{"temperature":8.5}}}
,29 Nov 17:10:50 - [info] [alexa-smart-home-v3-conf:5818c012.afb568]
Heizungsvorlauf : sending state update, topic:state/polofahrer00/4190
message:{"messageId":"6c7b185f-94fd-4098-b344-4cfddbce8b95","payload":{"state":{"temperature":32.5}}}
,29 Nov 17:10:50 - [info] [alexa-smart-home-v3-conf:5818c012.afb568]
Rücklaufanhebung : sending state update, topic:state/polofahrer00/4194
message:{"messageId":"7849021d-5a47-4382-8241-a10c8fa9427c","payload":{"state":{"temperature":33}}}

,29 Nov 17:12:27 - [debug] Flushing localfilesystem context scope global
,29 Nov 17:12:51 - [info] [alexa-smart-home-v3-conf:5818c012.afb568]
Kollektor : sending state update, topic:state/polofahrer00/4193
message:{"messageId":"66d5a9a7-3818-41e2-86fb-07e2b6985432","payload":{"state":{"temperature":8}}}
,29 Nov 17:12:51 - [info] [alexa-smart-home-v3-conf:5818c012.afb568]
Heizungsvorlauf : sending state update, topic:state/polofahrer00/4190
message:{"messageId":"f10bb317-c880-4ba3-90e1-95459458aaa1","payload":{"state":{"temperature":31.5}}}
,29 Nov 17:12:51 - [info] [alexa-smart-home-v3-conf:5818c012.afb568]
Rücklaufanhebung : sending state update, topic:state/polofahrer00/4194
message:{"messageId":"816271a9-25b6-44ee-8a2b-ee85276c8a4b","payload":{"state":{"temperature":32.5}}}
,29 Nov 17:14:52 - [info] [alexa-smart-home-v3-conf:5818c012.afb568]
Heizungsvorlauf : sending state update, topic:state/polofahrer00/4190
message:{"messageId":"f8602fc6-4bea-47c1-9b13-49694281dbb7","payload":{"state":{"temperature":31}}}
,29 Nov 17:14:52 - [info] [alexa-smart-home-v3-conf:5818c012.afb568]
Rücklaufanhebung : sending state update, topic:state/polofahrer00/4194
message:{"messageId":"bc1bf288-cfc7-4c05-8617-f764adb3c558","payload":{"state":{"temperature":31.5}}}
,29 Nov 17:16:53 - [info] [alexa-smart-home-v3-conf:5818c012.afb568]
Heizungsvorlauf : sending state update, topic:state/polofahrer00/4190
message:{"messageId":"11bf9085-cde7-4791-a11e-d2631640d6a8","payload":{"state":{"temperature":30.5}}}
,29 Nov 17:16:53 - [info] [alexa-smart-home-v3-conf:5818c012.afb568]
Rücklaufanhebung : sending state update, topic:state/polofahrer00/4194
message:{"messageId":"9017a0ab-ebb9-4c3a-b089-281ce9aa1cf2","payload":{"state":{"temperature":31}}}
,29 Nov 17:17:27 - [debug] Flushing localfilesystem context scope
343604b2.d3e8ac:7c8bee6f.7bf6a8
,29 Nov 17:17:27 - [debug] Flushing localfilesystem context scope
70295a94.cf1504:7c8bee6f.7bf6a8
,29 Nov 17:17:27 - [debug] Flushing localfilesystem context scope
86257bf6.2914c8:679903b1.b80a34
,29 Nov 17:17:27 - [debug] Flushing localfilesystem context scope
aefa0a97.94acc8:679903b1.b80a34
,29 Nov 17:17:27 - [debug] Flushing localfilesystem context scope
186fdd88.4ff572:b2e50e6a.b9ce38
,29 Nov 17:17:27 - [debug] Flushing localfilesystem context scope
3bcc1fed.1fb06:7c8bee6f.7bf6a8
,29 Nov 17:17:27 - [debug] Flushing localfilesystem context scope
d760356d.25e7c8:7c8bee6f.7bf6a8
,29 Nov 17:17:27 - [debug] Flushing localfilesystem context scope
3835b7e4.96e178:7c8bee6f.7bf6a8
,29 Nov 17:17:27 - [debug] Flushing localfilesystem context scope
7b0dbe5.965bbc:7c8bee6f.7bf6a8
,29 Nov 17:17:27 - [debug] Flushing localfilesystem context scope
150887b8.4983f:7c8bee6f.7bf6a8
,29 Nov 17:17:27 - [debug] Flushing localfilesystem context scope
767da849.3d041:7c8bee6f.7bf6a8
,29 Nov 17:17:27 - [debug] Flushing localfilesystem context scope global
,29 Nov 17:18:54 - [info] [alexa-smart-home-v3-conf:5818c012.afb568]
Heizungsrücklauf : sending state update, topic:state/polofahrer00/4191
message:{"messageId":"bd4d65e6-1e28-42f0-b92d-037a0ecabd95","payload":{"state":{"temperature":18}}}
,29 Nov 17:18:54 - [info] [alexa-smart-home-v3-conf:5818c012.afb568]
Heizungsvorlauf : sending state update, topic:state/polofahrer00/4190
message:{"messageId":"06888273-9f14-4ea6-83fe-c6bbf8d31d4a","payload":{"state":{"temperature":30}}}
,29 Nov 17:18:54 - [info] [alexa-smart-home-v3-conf:5818c012.afb568]
Rücklaufanhebung : sending state update, topic:state/polofahrer00/4194
message:{"messageId":"c56e37c3-cd66-4c81-a408-ae824d8f5fe5","payload":{"state":{"temperature":30.5}}}
,29 Nov 17:20:55 - [info] [alexa-smart-home-v3-conf:5818c012.afb568]
Kollektor : sending state update, topic:state/polofahrer00/4193
message:{"messageId":"3e4f1fba-8cc8-4fe5-90e5-5ea3e427f272","payload":{"state":{"temperature":7.5}}}
,29 Nov 17:20:55 - [info] [alexa-smart-home-v3-conf:5818c012.afb568]
Heizungsvorlauf : sending state update, topic:state/polofahrer00/4190
message:{"messageId":"a1108636-ed8a-44d5-844d-984cd756b016","payload":{"state":{"temperature":29.5}}}
,29 Nov 17:20:55 - [info] [alexa-smart-home-v3-conf:5818c012.afb568]
Rücklaufanhebung : sending state update, topic:state/polofahrer00/4194
message:{"messageId":"d72c9c46-b1da-4ae8-b8ad-d0e1e1468b03","payload":{"state":{"temperature":30}}}
9.3d041:7c8bee6f.7bf6a8
,29 Nov 17:22:27 - [debug] Flushing localfilesystem context scope global
,
many Thx


Am Fr., 29. Nov. 2019 um 12:55 Uhr schrieb coldfire84 <
notifications@github.com>:

**Comment by coldfire84** [comment]
Can you please share:
* Node-RED version and platform/ arch
* Node-RED contrib version (i.e. the nodes associated with this skill)
* The start-up log entries for Node-RED (there is nothing obviously wrong above, skill specific)

I'm unsure what these log events mean:

```
[debug] Flushing localfilesystem context scope global
```
What's the performance of the host running Node-RED like? Are there CPU/ memory/ disk I/O constraints. Any reference I can find to this log entry is associated with posts that note poor performance.

**Comment by polofahrer00** [comment]
[debug] Flushing localfilesystem context scope global

I store global variables on the filesystem .is a Settings in nodered
Settings.js .
all 300 sec the file is overwrited.

the System runs in a docker Container in a Atom  with ssd .

29 Nov 23:10:13 - [info]

Welcome to Node-RED

===================

29 Nov 23:10:13 - [info] Node-RED version: v1.0.3

29 Nov 23:10:13 - [info] Node.js  version: v10.17.0

29 Nov 23:10:13 - [info] Linux 4.15.0-70-generic x64 LE

29 Nov 23:10:15 - [info] Loading palette nodes

29 Nov 23:10:16 - [debug] Module: node-red-contrib-alexa-smart-home 0.4.60

29 Nov 23:10:16 - [debug]
/data/node_modules/node-red-contrib-alexa-smart-home

29 Nov 23:10:16 - [debug] Module: node-red-contrib-deduplicate 0.2.0

29 Nov 23:10:16 - [debug]
/data/node_modules/node-red-contrib-deduplicate

29 Nov 23:10:16 - [debug] Module: node-red-contrib-dwd-local-weather 0.1.8

29 Nov 23:10:16 - [debug]
/data/node_modules/node-red-contrib-dwd-local-weather

29 Nov 23:10:16 - [debug] Module: node-red-dashboard 2.19.0

29 Nov 23:10:16 - [debug]         /data/node_modules/node-red-dashboard

29 Nov 23:10:16 - [debug] Module: node-red-node-rbe 0.2.5

29 Nov 23:10:16 - [debug]
/usr/src/node-red/node_modules/node-red-node-rbe

29 Nov 23:10:16 - [debug] Module: node-red-node-tail 0.0.3

29 Nov 23:10:16 - [debug]
/usr/src/node-red/node_modules/node-red-node-tail

29 Nov 23:10:21 - [info] Dashboard version 2.19.0 started at /nodered/ui

29 Nov 23:10:21 - [info] Settings file  : /data/settings.js

29 Nov 23:10:21 - [info] Context store  : 'default' [module=localfilesystem]

29 Nov 23:10:21 - [info] User directory : /data

29 Nov 23:10:21 - [warn] Projects disabled : editorTheme.projects.enabled=false

29 Nov 23:10:21 - [info] Flows file     : /data/flows.json

29 Nov 23:10:22 - [info] Server now running at http://127.0.0.1:1880/nodered/

29 Nov 23:10:22 - [debug] loaded flow revision: 1282590515124250b6de4e495ba30f63

29 Nov 23:10:22 - [debug] red/runtime/nodes/credentials.load : user provided key

29 Nov 23:10:22 - [debug] red/runtime/nodes/credentials.load : keyType=user

29 Nov 23:10:22 - [info] Starting flows

29 Nov 23:10:22 - [debug] red/nodes/flows.start : starting flow : global

29 Nov 23:10:22 - [debug] red/nodes/flows.start : starting flow :
7c8bee6f.7bf6a8

29 Nov 23:10:22 - [debug] red/nodes/flows.start : starting flow :
679903b1.b80a34

29 Nov 23:10:22 - [debug] red/nodes/flows.start : starting flow :
b2e50e6a.b9ce38

29 Nov 23:10:22 - [debug] red/nodes/flows.start : starting flow :
4c62a3ac.328b64

29 Nov 23:10:22 - [debug] red/nodes/flows.start : starting flow :
2b707e56.0abf42

29 Nov 23:10:22 - [debug] red/nodes/flows.start : starting flow :
d2f04722.1b7cf8

29 Nov 23:10:22 - [info] Started flows

29 Nov 23:10:22 - [info] [mqtt-broker:ef86a849.8c7558] Connected to
broker: mqtt://192.168.178.43:1883

----------------------------------------------------------------------------------------------------------------------------------

mage
nodered/node-red:latest@sha256:599ed30695b5201fd8a67a9ba7c1594513fb65226a6e772f7d79a6aef5fd2133
<http://192.168.178.43:7000/#/images/sha256%3A599ed30695b5201fd8a67a9ba7c1594513fb65226a6e772f7d79a6aef5fd2133>
Port configuration
0.0.0.0:1900 1880/tcp
CMD
ENTRYPOINT npm start -- --userDir /data
ENV
PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NODE_VERSION 10.17.0
YARN_VERSION 1.19.1
NODE_RED_VERSION v1.0.3
NODE_PATH /usr/src/node-red/node_modules:/data/node_modules
FLOWS flows.json
Labels
authors Dave Conway-Jones, Nick O'Leary, James Thomas, Raymond Mouthaan
org.label-schema.arch amd64
org.label-schema.build-date 2019-11-21T20:49:44Z
org.label-schema.description Low-code programming for event-driven
applications.
org.label-schema.docker.dockerfile .docker/Dockerfile.alpine
org.label-schema.license Apache-2.0
org.label-schema.name Node-RED
org.label-schema.url https://nodered.org
org.label-schema.vcs-ref 2dad4559bec8aeb6e42f76da8d519ba15610fc06
org.label-schema.vcs-type Git
org.label-schema.vcs-url https://github.com/node-red/node-red-docker
org.label-schema.version 1.0.3

-----------------------------------------------------------------------------------------
thx



coldfire84 <notifications@github.com> schrieb am Fr., 29. Nov. 2019, 22:20:

**Comment by coldfire84** [comment]
> I store global variables on the filesystem .is a Settings in nodered
Settings.js .
all 300 sec the file is overwrited.

OK, that explains the log entries - thanks.

Strangely the versions and logs look OK. If you try and edit a device-specific node what do you see? Can you confirm account name is listed and that the device is selected?

![image](https://user-images.githubusercontent.com/22571742/69891770-f03ce980-12f6-11ea-95cf-1acd01f89fa1.png)

For the account name listed in the logs I have *no* activity on the web API server. So whilst the logs show it is being sent, it is not reaching the destination. 

What are the nodes themselves showing? Are they connected?

![image](https://user-images.githubusercontent.com/22571742/69891873-a0aaed80-12f7-11ea-8577-48ef23d43a65.png)

This shows MQTT connectivity. If this is not green then the Node-RED instance cannot connect via MQTTS to the web API server which would explain why all devices are not responding. Can you confirm network connectivity (MQTTS and HTPPS), from your Node-RED host, to the hosts below:

![image](https://user-images.githubusercontent.com/22571742/69891893-d0f28c00-12f7-11ea-9a98-1d1a58c3cf07.png)

**Comment by polofahrer00** [comment]
Everything looks  good
when i ceate a NEW Service is shown in Nodered and Alexa find the device ,
but no Update in both directions .the temperatursensors shows in alexa 22 .
if i change a switch in alexa i get device not response ,also if in nodered
the auto achnowledge is activated. no device is working correct

coldfire84 <notifications@github.com> schrieb am Fr., 29. Nov. 2019, 23:31:

**Comment by coldfire84** [comment]
I'm showing little/ no traffic hitting the bridge other than a load of HTTP 401 error (**unauthorised**, usually wrong username/ password):

```
verbose: x.x.x.x - polofahrer00 [03/Dec/2019:19:10:05 +0000] "GET /api/v1/devices HTTP/1.0" 401 - "-" "-"
verbose: x.x.x.x - polofahrer00 [03/Dec/2019:19:12:17 +0000] "GET /api/v1/devices HTTP/1.0" 401 - "-" "-"
verbose: x.x.x.x - polofahrer00 [03/Dec/2019:19:12:43 +0000] "GET /api/v1/devices HTTP/1.0" 401 - "-" "-"
```

**Comment by coldfire84** [comment]
Can you update your Node-RED nodes for this skill and share logs as per instructions [here.](https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/issues/89#issuecomment-562999616)

**Comment by coldfire84** [comment]
Instructions to update to a version of Nodes that should resolve this issue [here](https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/issues/89#issuecomment-563326627) - please test and confirm.
