### ISSUE TITLE
GA -  Alexa Range Controller / Semantics 

### ISSUE THREAD

**Issue by a011528** [coldfire84/node-red-alexa-home-skill-v3-web#86]
Using semantics to enable additional utterances 

Id like to have the option to voice control Blinds and Awnings / Shades with the New Open / Close/ Raise / Lower semantics. Is this something you can add to the functionality of the RangeController in the Devices web interface (SmartHome) either using an array to map (i.e. open=10, Close =0) or is this something i could achieve with my own web instance?

Personally, now that semantics is now General Available this gives SmartHome users more natural control over their devices

(extract from Amazon Semantics Website URL at bottom) 
 When you use the Alexa.RangeController interface, the voice interaction model is already built for you. Users can interact with your device by saying the standard RangeController utterances. For more information, see utterances.

You can optionally enable additional utterances by using semantics. When you use semantics, you manually map the phrases "open", "close", "raise", and "lower" to the RangeController directives SetRangeValue and AdjustRangeValue. For example, if you have a controller for a window shade, you can map the phrase "raise" to the AdjustRangeValue directive.

You can support semantics on different controllers for the same device, however each controller must support different phrases. For example, you can support "raise" on a RangeController, and "open" on a ModeController, but you can't support "open" on both RangeController and ModeController.

To use semantics, include a semantics object in your discover response as described in the following section.

https://developer.amazon.com/docs/device-apis/alexa-rangecontroller.html#semantics

**Comment by coldfire84** [comment]
>  Id like to have the option to voice control Blinds and Awnings / Shades

I've added the Open/ Close natural-language mappings to the RangeController capability. Will look to add "Blind" device type to the UI.

**Comment by a011528** [comment]
Great and Thx , would would also be appreciated if you could also add Awning to device type

**Comment by coldfire84** [comment]
Interior Blind and Exterior Blind display categories added, as per: https://developer.amazon.com/docs/device-apis/alexa-discovery.html#display-categories.

Please test and provide feedback.

**Comment by a011528** [comment]
Does not react to "open" or "close". I can get it to respond to "lower" and "raise" (but that not natural speak, to me per say and id need to retrain my brain).

Also have you or intend to add all Display Categories as listed in the link above, as they would be very useful ?

**Comment by coldfire84** [comment]
>Does not react to "open" or "close"

Open/ Close may be region specific (the code is there, its a copy/ paste form the example on the Smart Home API development page). Where are you based?

Ref adding other categories, the skill gets extended based on demand/ value of the categories.

**Comment by a011528** [comment]
i have my account in UK (although im outside of UK now) 

Be great if you could add these other categories added + 1 obviously  

CAMERA 
DOOR 
DOORBELL
GARAGE_DOOR
NETWORK_HARDWARE

**Comment by coldfire84** [comment]
> CAMERA
DOOR
DOORBELL
GARAGE_DOOR
NETWORK_HARDWARE

Interested to understand use cases for these - 
* what capabilities do you foresee using with these device types?
* how do these devices surface in Node-RED today?
* how would you like to interact with the devices?

**Comment by a011528** [comment]
I surface these as devices in Node Red as Smart Home components devices to control them using flows, using Alexa to provide as much Voice capability/control as possible (or trying to). The icons are great in the Alexa app to make differentiation easier, especially for the rest of the family to build their own routines + IFTTT, at the moment you end up with generic icon but underlying device / HW is very different and limited. so its end user (family) usability, as one is limited in mobility. 
 
Camera - Alexa Show stream On TV or Echo Show
Door - Lock / Open + Confirm and Icon to display Locked/closed
Doorbell to pass notifications 
Garage - Alexa is the Garage door locked / Alexa open / close  
Network HW -  Alexa to confirm status UP / Down etc

**Comment by coldfire84** [comment]
> Does not react to "open" or "close". I can get it to respond to "lower" and "raise" (but that not natural speak, to me per say and id need to retrain my brain).

Open and Close are now working. I'll add the other device types to the feature request bucket.

**Comment by hectorzeta** [comment]
Hi,
Was the DOORBELL device added? I cannot see it.
Are you still planning to add it in a future version?
