### ISSUE TITLE
Not working hosted mqtt / complete connection?

### ISSUE THREAD

**Issue by kwesolowski** [coldfire84/node-red-alexa-home-skill-v3-web#89]
Since few days i observed:

1. Alexa is not responding (or rather alexa works fine but "Kitchen is not responding)
2. no connection indicator on my blocks in node-red,
3. empty output from running: `mosquitto_sub -h mq-red.cb-net.co.uk -t '#' -v -u kwesoly -P 'XXXXXX' --capath /etc/ssl/certs --id test-kwesoly -p 8883
`

Log is empty of anything that would explain it:

> tarted Node-RED graphical event wiring tool.
8 Dec 21:24:04 - [info]
Welcome to Node-RED
===================
8 Dec 21:24:04 - [info] Node-RED version: v0.20.8
8 Dec 21:24:04 - [info] Node.js  version: v10.16.3
8 Dec 21:24:04 - [info] Linux 4.19.66-v7+ arm LE
8 Dec 21:24:05 - [info] Loading palette nodes
8 Dec 21:24:09 - [info] Settings file  : /root/.node-red/settings.js
8 Dec 21:24:09 - [info] Context store  : 'default' [module=memory]
8 Dec 21:24:09 - [info] User directory : /root/.node-red
8 Dec 21:24:09 - [info] Server now running at http://127.0.0.1:1880/
8 Dec 21:24:09 - [info] Starting flows
8 Dec 21:24:11 - [info] Started flows
8 Dec 21:24:12 - [info] [mqtt-broker:local-ampio] Connected to broker: ampio-node-red@mqtt://localhost:1883
8 Dec 21:24:12 - [info] [miio-purifier-input:Purifier Living Room] Initialized
8 Dec 21:24:12 - [info] [miio-humidifier-input:Humidifier Living Room] Initialized
8 Dec 21:24:12 - [info] [miio-humidifier-output:Humidifier Living Room] Initialized
8 Dec 21:24:12 - [info] [alexa-remote-account:kwesoly Alexa Account] intialising "kwesoly Alexa Account" with the PROXY method and saved data...
8 Dec 21:24:13 - [info] [miio-purifier-output:Purifier Living Room] Initialized
8 Dec 21:24:13 - [info] [miio-purifier-input:Purifier Kids] Initialized
8 Dec 21:24:13 - [info] [miio-purifier-input:Purifier Bedroom] Initialized
8 Dec 21:24:13 - [info] [miio-purifier-input:Purifier Office] Initialized
8 Dec 21:24:13 - [info] [miio-purifier-output:Purifier Kids] Initialized
8 Dec 21:24:13 - [info] [miio-purifier-output:Purifier Bedroom] Initialized
8 Dec 21:24:13 - [info] [miio-purifier-output:Purifier Office] Initialized
8 Dec 21:24:14 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Kitchen Main Light : sending state update, topic:state/kwesoly/3419 message:{"messageId":"8f5498f0-a010-4e2f-97ae-fcd5728646de","payload":{"state":{"brightness":100,"power":"ON"}}}
8 Dec 21:24:14 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Countertop Light : sending state update, topic:state/kwesoly/3416 message:{"messageId":"ed32cf93-5d7c-4246-9ff4-5016ea7b8809","payload":{"state":{"brightness":100,"power":"ON"}}}
8 Dec 21:24:14 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Island Light : sending state update, topic:state/kwesoly/3415 message:{"messageId":"7a6c63f1-b9f3-4ad5-be23-7e2028261579","payload":{"state":{"power":"OFF"}}}
8 Dec 21:24:14 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Living Room Main Light : sending state update, topic:state/kwesoly/3417 message:{"messageId":"7102f03d-b850-4ee7-b589-478a07cc4c05","payload":{"state":{"brightness":100,"power":"ON"}}}
8 Dec 21:24:14 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Living Room Table Light : sending state update, topic:state/kwesoly/3418 message:{"messageId":"9fed8944-b941-4e92-9654-276e509b5a4b","payload":{"state":{"brightness":0,"power":"OFF"}}}
8 Dec 21:24:14 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Bedside Chris's Light : sending state update, topic:state/kwesoly/3440 message:{"messageId":"f1eb0983-d0cb-488d-93ae-5dc63bf497e7","payload":{"state":{"brightness":0,"power":"OFF"}}}
8 Dec 21:24:14 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Bedside Ivon's Light : sending state update, topic:state/kwesoly/3438 message:{"messageId":"14a5dcd7-87fe-4aca-a582-b6726c0d96ba","payload":{"state":{"brightness":0,"power":"OFF"}}}
8 Dec 21:24:14 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Bedroom Light : sending state update, topic:state/kwesoly/3436 message:{"messageId":"9a52feab-d91f-416c-941e-e7bc06cd7433","payload":{"state":{"brightness":0,"power":"OFF"}}}
8 Dec 21:24:14 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Bedroom Ledbar : sending state update, topic:state/kwesoly/3442 message:{"messageId":"0c52d244-70ec-445b-992a-556b4e585970","payload":{"state":{"brightness":0,"power":"OFF"}}}
8 Dec 21:24:14 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Bedroom Vanity Table Light : sending state update, topic:state/kwesoly/3443 message:{"messageId":"2ce63e09-23ba-4763-8761-42bb809d2f72","payload":{"state":{"brightness":0,"power":"OFF"}}}
8 Dec 21:24:14 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Corridor Main Light : sending state update, topic:state/kwesoly/3444 message:{"messageId":"a0e14032-5dd7-4c9d-aee3-abf4d0cde771","payload":{"state":{"brightness":0,"power":"OFF"}}}
8 Dec 21:24:14 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Corridor Kitchen Light : sending state update, topic:state/kwesoly/3445 message:{"messageId":"f28fe401-7e75-4905-8b2b-873853a9274c","payload":{"state":{"brightness":0,"power":"OFF"}}}
8 Dec 21:24:14 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Kids Beds Light : sending state update, topic:state/kwesoly/3446 message:{"messageId":"13a76897-a51d-4f3d-b9b0-12fa550fa595","payload":{"state":{"brightness":0,"power":"OFF"}}}
8 Dec 21:24:14 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Kids Play Light : sending state update, topic:state/kwesoly/3447 message:{"messageId":"7743f52a-e4ed-4750-9011-010de5ef21a9","payload":{"state":{"brightness":0,"power":"OFF"}}}
8 Dec 21:24:14 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Bathroom 1 Main Light : sending state update, topic:state/kwesoly/3448 message:{"messageId":"50e60f9c-e6a7-4696-988e-69fc352c5451","payload":{"state":{"brightness":0,"power":"OFF"}}}
8 Dec 21:24:14 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Office Main Light : sending state update, topic:state/kwesoly/3450 message:{"messageId":"595744cf-1cfe-46fd-b4f5-1a89088cf953","payload":{"state":{"brightness":100,"power":"ON"}}}
8 Dec 21:24:14 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Bathroom 2 Main Light : sending state update, topic:state/kwesoly/3449 message:{"messageId":"8f67293a-4cd1-490b-b488-9ca7c63020bf","payload":{"state":{"brightness":0,"power":"OFF"}}}
8 Dec 21:24:14 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Bathroom 2 Temperature : sending state update, topic:state/kwesoly/3787 message:{"messageId":"4ea45b3c-f5fd-419c-a6bb-719fa610399c","payload":{"state":{"temperature":23.288571428571434}}}
8 Dec 21:24:14 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Bathroom 1 Temperature : sending state update, topic:state/kwesoly/3786 message:{"messageId":"e8de0dd0-7322-4216-91d9-40f5f3a2602e","payload":{"state":{"temperature":25.97142857142857}}}
8 Dec 21:24:14 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Office Temperature : sending state update, topic:state/kwesoly/3788 message:{"messageId":"e94ce959-9379-41df-88fe-1a870449b5f5","payload":{"state":{"temperature":20.387500000000042}}}
8 Dec 21:24:14 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Bedroom  Temperature : sending state update, topic:state/kwesoly/3784 message:{"messageId":"417c9006-ba60-4129-95a9-21a1f8dfd9c7","payload":{"state":{"temperature":21.222005730659113}}}
8 Dec 21:24:14 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Kids Temperature : sending state update, topic:state/kwesoly/3785 message:{"messageId":"e45e9409-ae2e-449f-badf-791211f621ad","payload":{"state":{"temperature":25.705571030640662}}}
8 Dec 21:24:14 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Living Room Temperature : sending state update, topic:state/kwesoly/3782 message:{"messageId":"252fa387-dad9-4332-8cf1-2ef2e71af9dc","payload":{"state":{"temperature":21.51169590643274}}}
8 Dec 21:24:14 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Hall Temperature : sending state update, topic:state/kwesoly/3783 message:{"messageId":"53ca48c0-cbb4-421b-aedb-ac121590e849","payload":{"state":{"temperature":22.559649122807013}}}
8 Dec 21:24:15 - [info] [miio-lumi-v3-input:d3060194.d71ee] Initialized

**Comment by coldfire84** [comment]
> a) no connection indicator on my blocks in node-red,

Can you edit your config node (re-enter account username and password) and see if this resolves the issue.

I've added some additional logging to the Node-RED contrib, can you update [nodes](https://www.npmjs.com/package/node-red-contrib-alexa-smart-home) to version 0.4.63 minimum and re-share log output. Log output should now include lines similar to:

```
8 Dec 21:53:53 - [info] [alexa-smart-home-v3-conf:d600f657.2b1298] Connecting to Alexa/ Google Home Skill MQTT server: mq-red.cb-net.co.uk, account username: <account name>
8 Dec 21:53:55 - [info] [alexa-smart-home-v3-conf:d600f657.2b1298] Successfully connected to Alexa/ Google Home Skill MQTT server: mq-red.cb-net.co.uk, account username: <account name>
```

I suspect root cause is similar to #85 - which is still under investigation.

**Comment by kwesolowski** [comment]
After updating no log like you mention, see below from after editing password:

`8 Dec 23:13:39 - [info] Stopping modified flows
8 Dec 23:13:39 - [info] Stopped modified flows
8 Dec 23:13:39 - [info] Starting modified flows
8 Dec 23:13:40 - [info] Started modified flows
8 Dec 23:13:40 - [info] [alexa-smart-home-v3-state:Kitchen Main Light] Kitchen Main Light state node: discarded duplicate state payload
8 Dec 23:13:40 - [info] [alexa-smart-home-v3-state:Countertop Light] Countertop Light state node: discarded duplicate state payload
8 Dec 23:13:40 - [info] [alexa-smart-home-v3-state:Island Light] Island Light state node: discarded duplicate state payload
8 Dec 23:13:40 - [info] [alexa-smart-home-v3-state:Living Room Main Light] Living Room Main Light state node: discarded duplicate state payload
8 Dec 23:13:40 - [info] [alexa-smart-home-v3-state:Living Room Table Light] Living Room Table Light state node: discarded duplicate state payload
8 Dec 23:13:40 - [info] [alexa-smart-home-v3-state:Bedside Chris's Light] Bedside Chris's Light state node: discarded duplicate state payload
8 Dec 23:13:40 - [info] [alexa-smart-home-v3-state:Bedside Ivon's Light] Bedside Ivon's Light state node: discarded duplicate state payload
8 Dec 23:13:40 - [info] [alexa-smart-home-v3-state:Bedroom Light] Bedroom Light state node: discarded duplicate state payload
8 Dec 23:13:40 - [info] [alexa-smart-home-v3-state:Bedroom Ledbar] Bedroom Ledbar state node: discarded duplicate state payload
8 Dec 23:13:40 - [info] [alexa-smart-home-v3-state:Bedroom Vanity Table Light] Bedroom Vanity Table Light state node: discarded duplicate state payload
8 Dec 23:13:40 - [info] [alexa-smart-home-v3-state:Corridor Main Light] Corridor Main Light state node: discarded duplicate state payload
8 Dec 23:13:40 - [info] [alexa-smart-home-v3-state:Corridor Kitchen Light] Corridor Kitchen Light state node: discarded duplicate state payload
8 Dec 23:13:40 - [info] [alexa-smart-home-v3-state:Kids Beds Light] Kids Beds Light state node: discarded duplicate state payload
8 Dec 23:13:40 - [info] [alexa-smart-home-v3-state:Kids Play Light] Kids Play Light state node: discarded duplicate state payload
8 Dec 23:13:40 - [info] [alexa-smart-home-v3-state:Bathroom 1 Main Light] Bathroom 1 Main Light state node: discarded duplicate state payload
8 Dec 23:13:40 - [info] [alexa-smart-home-v3-state:Office Main Light] Office Main Light state node: discarded duplicate state payload
8 Dec 23:13:40 - [info] [alexa-smart-home-v3-state:Bathroom 2 Main Light] Bathroom 2 Main Light state node: discarded duplicate state payload
8 Dec 23:13:41 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Bathroom 2 Temperature : sending state update, topic:state/kwesoly/3787 message:{"messageId":"2159f2c4-a2df-412b-b183-c0526174b27d","payload":{"state":{"temperature":25.800000000000004}}}
8 Dec 23:13:41 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Bathroom 1 Temperature : sending state update, topic:state/kwesoly/3786 message:{"messageId":"fb22f7cf-fdc7-451f-ac2b-278d0b1c57d0","payload":{"state":{"temperature":26.124358974358973}}}
8 Dec 23:13:41 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Office Temperature : sending state update, topic:state/kwesoly/3788 message:{"messageId":"9be9a776-8ace-4b76-8f8e-3ce327770e54","payload":{"state":{"temperature":21.049343832021016}}}
8 Dec 23:13:41 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Bedroom  Temperature : sending state update, topic:state/kwesoly/3784 message:{"messageId":"d3083ec8-ea38-4d16-a4d5-087b7aa577b2","payload":{"state":{"temperature":21.334857142857143}}}
8 Dec 23:13:41 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Kids Temperature : sending state update, topic:state/kwesoly/3785 message:{"messageId":"4267cc10-085d-44f5-82e4-f84ff2fe4b88","payload":{"state":{"temperature":21.570410958904056}}}
8 Dec 23:13:41 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Living Room Temperature : sending state update, topic:state/kwesoly/3782 message:{"messageId":"32457982-d860-40c4-95d0-43d2e74e8ba4","payload":{"state":{"temperature":21.175567867035944}}}
8 Dec 23:13:41 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Hall Temperature : sending state update, topic:state/kwesoly/3783 message:{"messageId":"bf7e6377-b5e0-4b84-bce7-10ae3815e254","payload":{"state":{"temperature":22.275000000000002}}}`

Is there any more verbose look that would help that I can enable?

**Comment by coldfire84** [comment]
Need to see logs straight after Node-RED start-up. Please share the entire start-up sequence. 

Did you update nodes associated with the skill?

**Comment by kwesolowski** [comment]
After issuing: systemctl restart nodered.service && node-red-log

8 Dec 23:40:42 - [info] Stopped flows
nodered.service: Succeeded.
Stopped Node-RED graphical event wiring tool.
Started Node-RED graphical event wiring tool.
8 Dec 23:40:44 - [info]
Welcome to Node-RED
===================
8 Dec 23:40:44 - [info] Node-RED version: v0.20.8
8 Dec 23:40:44 - [info] Node.js  version: v10.16.3
8 Dec 23:40:44 - [info] Linux 4.19.66-v7+ arm LE
8 Dec 23:40:46 - [info] Loading palette nodes
8 Dec 23:40:50 - [info] Settings file  : /root/.node-red/settings.js
8 Dec 23:40:50 - [info] Context store  : 'default' [module=memory]
8 Dec 23:40:50 - [info] User directory : /root/.node-red
8 Dec 23:40:50 - [info] Server now running at http://127.0.0.1:1880/
8 Dec 23:40:50 - [info] Active project : zablocie2162ha
8 Dec 23:40:50 - [info] Flows file     : /root/.node-red/projects/zablocie2162ha/flows_ampio.json
8 Dec 23:40:50 - [info] Starting flows
8 Dec 23:40:52 - [info] Started flows
8 Dec 23:40:53 - [info] [mqtt-broker:local-ampio] Connected to broker: ampio-node-red@mqtt://localhost:1883
8 Dec 23:40:53 - [info] [miio-purifier-input:Purifier Living Room] Initialized
8 Dec 23:40:53 - [info] [miio-humidifier-input:Humidifier Living Room] Initialized
8 Dec 23:40:53 - [info] [miio-humidifier-output:Humidifier Living Room] Initialized
8 Dec 23:40:53 - [info] [alexa-remote-account:kwesoly Alexa Account] intialising "kwesoly Alexa Account" with the PROXY method and saved data...
8 Dec 23:40:54 - [info] [miio-purifier-output:Purifier Living Room] Initialized
8 Dec 23:40:54 - [info] [miio-purifier-input:Purifier Office] Initialized
8 Dec 23:40:54 - [info] [miio-purifier-input:Purifier Kids] Initialized
8 Dec 23:40:54 - [info] [miio-purifier-output:Purifier Kids] Initialized
8 Dec 23:40:54 - [info] [miio-purifier-input:Purifier Bedroom] Initialized
8 Dec 23:40:54 - [info] [miio-purifier-output:Purifier Office] Initialized
8 Dec 23:40:54 - [info] [miio-purifier-output:Purifier Bedroom] Initialized
8 Dec 23:40:54 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Kitchen Main Light : sending state update, topic:state/kwesoly/3419 message:{"messageId":"4bd036b3-b512-42b7-92e2-11a2c2a13248","payload":{"state":{"brightness":100,"power":"ON"}}}
8 Dec 23:40:54 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Countertop Light : sending state update, topic:state/kwesoly/3416 message:{"messageId":"0998e326-a8ae-4e5a-9beb-09dfef80cad8","payload":{"state":{"brightness":100,"power":"ON"}}}
8 Dec 23:40:54 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Island Light : sending state update, topic:state/kwesoly/3415 message:{"messageId":"49f4b5e6-adb9-442b-8ebe-54837877a5ce","payload":{"state":{"power":"OFF"}}}
8 Dec 23:40:54 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Living Room Main Light : sending state update, topic:state/kwesoly/3417 message:{"messageId":"61c43bd8-b06b-4cff-83dc-2f20a6d1f000","payload":{"state":{"brightness":100,"power":"ON"}}}
8 Dec 23:40:54 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Living Room Table Light : sending state update, topic:state/kwesoly/3418 message:{"messageId":"08715b6e-8cff-4628-ba8f-82daa73b6e32","payload":{"state":{"brightness":0,"power":"OFF"}}}
8 Dec 23:40:54 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Bedside Chris's Light : sending state update, topic:state/kwesoly/3440 message:{"messageId":"a1705188-8d4e-44a9-9e28-1cfe3ceb9700","payload":{"state":{"brightness":0,"power":"OFF"}}}
8 Dec 23:40:54 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Bedside Ivon's Light : sending state update, topic:state/kwesoly/3438 message:{"messageId":"7d8b32b7-a020-43b5-a972-fb7eea2f465d","payload":{"state":{"brightness":0,"power":"OFF"}}}
8 Dec 23:40:54 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Bedroom Light : sending state update, topic:state/kwesoly/3436 message:{"messageId":"9596e7ce-7ec0-4193-9bd0-c20ad6750ee1","payload":{"state":{"brightness":0,"power":"OFF"}}}
8 Dec 23:40:55 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Bedroom Ledbar : sending state update, topic:state/kwesoly/3442 message:{"messageId":"a930e523-ca5e-4488-90ab-e817df931649","payload":{"state":{"brightness":0,"power":"OFF"}}}
8 Dec 23:40:55 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Bedroom Vanity Table Light : sending state update, topic:state/kwesoly/3443 message:{"messageId":"81b62a0a-3397-4989-af5f-8781bc237bee","payload":{"state":{"brightness":0,"power":"OFF"}}}
8 Dec 23:40:55 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Corridor Main Light : sending state update, topic:state/kwesoly/3444 message:{"messageId":"60569fab-368e-45ad-872e-6ab252580c87","payload":{"state":{"brightness":0,"power":"OFF"}}}
8 Dec 23:40:55 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Corridor Kitchen Light : sending state update, topic:state/kwesoly/3445 message:{"messageId":"45714e9d-6800-4785-a7e8-19d9e5336d72","payload":{"state":{"brightness":0,"power":"OFF"}}}
8 Dec 23:40:55 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Kids Beds Light : sending state update, topic:state/kwesoly/3446 message:{"messageId":"9930adf2-8997-46fb-8c0e-5fccb6a54a9a","payload":{"state":{"brightness":0,"power":"OFF"}}}
8 Dec 23:40:55 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Kids Play Light : sending state update, topic:state/kwesoly/3447 message:{"messageId":"cd51f0cd-68f4-4019-82a7-8eba6dafbdcf","payload":{"state":{"brightness":0,"power":"OFF"}}}
8 Dec 23:40:55 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Bathroom 1 Main Light : sending state update, topic:state/kwesoly/3448 message:{"messageId":"06be62fa-6c05-4179-be9b-a626098d6438","payload":{"state":{"brightness":0,"power":"OFF"}}}
8 Dec 23:40:55 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Office Main Light : sending state update, topic:state/kwesoly/3450 message:{"messageId":"a7c797b8-f2ba-4a76-968b-dfee95d9bdeb","payload":{"state":{"brightness":100,"power":"ON"}}}
8 Dec 23:40:55 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Bathroom 2 Main Light : sending state update, topic:state/kwesoly/3449 message:{"messageId":"8735a5be-9ae1-4f79-8e54-777ad7b626a1","payload":{"state":{"brightness":0,"power":"OFF"}}}
8 Dec 23:40:55 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Bathroom 2 Temperature : sending state update, topic:state/kwesoly/3787 message:{"messageId":"b53069ab-c601-46b7-9677-c7920d25ccb0","payload":{"state":{"temperature":24.41463414634146}}}
8 Dec 23:40:55 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Bathroom 1 Temperature : sending state update, topic:state/kwesoly/3786 message:{"messageId":"40642ff9-6a5b-4f57-bdb7-5bbd74133778","payload":{"state":{"temperature":25.984375}}}
8 Dec 23:40:55 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Office Temperature : sending state update, topic:state/kwesoly/3788 message:{"messageId":"97b57f0f-d2c6-4575-a6ff-f75979cda898","payload":{"state":{"temperature":21.099732620320935}}}
8 Dec 23:40:55 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Bedroom  Temperature : sending state update, topic:state/kwesoly/3784 message:{"messageId":"46b27a44-f7a0-47b3-b9c2-408deecf14b3","payload":{"state":{"temperature":20.95571428571434}}}
8 Dec 23:40:55 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Kids Temperature : sending state update, topic:state/kwesoly/3785 message:{"messageId":"151bb462-778e-4d80-bf8e-aa4ed251202d","payload":{"state":{"temperature":21.29972527472535}}}
8 Dec 23:40:55 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Living Room Temperature : sending state update, topic:state/kwesoly/3782 message:{"messageId":"c34ed24b-1771-42ef-9d81-d07b659fe035","payload":{"state":{"temperature":21.16724795640327}}}
8 Dec 23:40:55 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Hall Temperature : sending state update, topic:state/kwesoly/3783 message:{"messageId":"bcab6759-d699-4b86-9d5f-a1e089d370a0","payload":{"state":{"temperature":22.23783783783784}}}
8 Dec 23:40:56 - [info] [miio-lumi-v3-input:d3060194.d71ee] Initialized

**Comment by kwesolowski** [comment]
![image](https://user-images.githubusercontent.com/5962607/70397718-e44ad900-1a14-11ea-9cd8-fe45adf03519.png)

**Comment by coldfire84** [comment]
Can you uninstall the nodes and re-install. It's not even *trying* to connect via MQTT to the bridge...

Worth deleting the account config as well.

**Comment by kwesolowski** [comment]
Ok, added some logs and it seems order of node initialization breaks connect logic:

9 Dec 01:33:53 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Node created, configuring MQTT
9 Dec 01:33:54 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] this.register called for id = 78df69ab.906ce8 with type = alexa-smart-home-v3-state
9 Dec 01:33:54 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] this.register first client
9 Dec 01:33:54 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Not connecting as device type is  alexa-smart-home-v3-state
9 Dec 01:33:54 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] this.register called for id = 20a4b51b.c0911a with type = alexa-smart-home-v3-state
9 Dec 01:33:54 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Not connecting as its not first user
9 Dec 01:33:54 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] this.register called for id = ff909dc2.be8ea with type = alexa-smart-home-v3-state
9 Dec 01:33:54 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Not connecting as its not first user
9 Dec 01:33:54 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] this.register called for id = a98e9eed.cc248 with type = alexa-smart-home-v3-state
9 Dec 01:33:54 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Not connecting as its not first user
9 Dec 01:33:54 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] this.register called for id = f22f6f48.705f1 with type = alexa-smart-home-v3-state
9 Dec 01:33:54 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Not connecting as its not first user

**Comment by kwesolowski** [comment]
After "brutal" simplifications works like a charm:
           
            // Connect only on first node register/ connect
            if (Object.keys(node.users).length === 1) {
                node.log("this.register first user");
                node.connect();
            } else {
                node.log("Not connecting as its not first user")
            }

**Comment by kwesolowski** [comment]
Maybe there was some " alexa-smart-home-v3" vs " alexa-smart-home-v3-state" change recently that affected only those where state is registered first?

**Comment by coldfire84** [comment]
Thanks for digging into this in detail - much appreciated - so in summary:
- If state node is created/ registered first and there is no "command" node the connection doesn't take place
- Even when a "command" node is added the connection *still* doesn't take place? This is what is really interesting to understand.

I assume the code block you've modified is as below:
```
this.register = function(deviceNode) {
    node.users[deviceNode.id] = deviceNode;
    // Connect only on first node register/ connect
    if (Object.keys(node.users).length === 1) {
        if (deviceNode.type == "alexa-smart-home-v3") {
            node.connect();
        }
    }
};
```

If so, what's interesting is that this has been in-place since first release of the state node. It's one of few pieces that hasn't changed over time.

**Comment by kwesolowski** [comment]
Yes, thats the code causing the problem.

Then I guess its mostly that state reporting is quite fresh? or state
reporting was there also as long?

**Comment by coldfire84** [comment]
> Then I guess its mostly that state reporting is quite fresh? or state
reporting was there also as long?

Commands using the V3 API came first, and as a result many users entry path to using the skill would have been the command node. State was a fairly early roadmap delivery though, so I'm surprised this hasn't come up until recently (two reported issues).

I've been racking my brains on why this code is even here (was a while ago I introduced the state capability!):
```
        if (deviceNode.type == "alexa-smart-home-v3") {
        }
```

I'll do some testing tonight and look to remove/ assess impact before releasing an updated version of the nodes. Will post an update to this issue when testing/ release is completed.

Thanks again for identifying the source of the issue!

**Comment by kwesolowski** [comment]
And only idea i have about how this got broken for me (in a way I did not
notice until much later) is

a) I added state reporting on some of the first flows, but only did partial
deploy so the whole thing stayed initialized for some days.
b) my RPI was rebooted, and with full init state block is first.

**Comment by coldfire84** [comment]
I've published an "-alpha.1" version (-alpha.1 acts as a filter, to prevent auto updates for all users of the nodes). You can update to this specific version via npm - i.e. for a Docker containerised version of Node-RED:

```
cd /data
npm install node-red-contrib-alexa-smart-home@0.4.64-alpha.1
```

Code change is simply as you discovered, in the alpha release I have commented out the check, will remove entirely if users impacted by this issue, plus wider testing shows no issue.

**Comment by kwesolowski** [comment]
I can confirm that it works fine after updating:

10 Dec 21:48:15 - [info] [alexa-smart-home-v3-conf:a6ac4643.7ba2c8] Successfully connected to Alexa/ Google Home Skill MQTT server: mq-red.cb-net.co.uk, account username: kwesoly

**Comment by coldfire84** [comment]
@kwesolowski, thanks for your help in testing/ identifying required changes to fix this.
