### ISSUE TITLE
Extend thermostat control

### ISSUE THREAD

**Issue by NovaGL** [coldfire84/node-red-alexa-home-skill-v3-web#9]
In the original version of this skill you could say turn on aircon, but in your version that doesn't work, can the skill be updated to allow this? You also can't ask the current temperature

https://i.imgur.com/7C5mVVP.png

**Comment by NovaGL** [comment]
These are the commands I need that I use in the V2 of the API

> "GetTargetTemperatureRequest"
> "GetTemperatureReadingRequest"
> "TurnOnRequest"
> "TurnOffRequest"
> "SetTargetTemperatureRequest"
> "IncrementTargetTemperatureRequest"
> "DecrementTargetTemperatureRequest"
> "ModeChangeRequest"
> "FanModeChangeRequest"

**Comment by NovaGL** [comment]
So I looked into this further, there are definitely missing directives. Please see below tests that were performed.

### ThermostatController
AdjustTargetTemperature (success)
SetThermostatMode (success)
SetTargetTemperature (fail)

### TemperatureSensor
(success)

### PowerController
TurnOn (fail)
TurnOff (fail)

### Fan Speed
Added for completeness might not be required

SetRangeValue (fail)
AdjustRangeValue (fail)

**Comment by coldfire84** [comment]
@NovaGL 

So at present I have built-in support for a [Single Point Thermostat](https://developer.amazon.com/docs/device-apis/alexa-thermostatcontroller.html#single-setpoint-thermostats). I will look to grow the support to include [Dual Point](https://developer.amazon.com/docs/device-apis/alexa-thermostatcontroller.html#dual-setpoint-thermostats) and [Triple Point](https://developer.amazon.com/docs/device-apis/alexa-thermostatcontroller.html#triple-setpoint-thermostats).

Whether this impacts your HVAC experience or not I am unsure.

> Ref Fan Speed

I've not added support for [Range Controller](https://developer.amazon.com/docs/device-apis/alexa-rangecontroller.html), [PowerLevelController](https://developer.amazon.com/docs/device-apis/alexa-powerlevelcontroller.html), [ModeController](https://developer.amazon.com/docs/device-apis/alexa-modecontroller.html) or [PercentageController](https://developer.amazon.com/docs/device-apis/alexa-percentagecontroller.html).  

I would imagine [ModeController](https://developer.amazon.com/docs/device-apis/alexa-modecontroller.html) would fit the bill (would assess and code accordingly).

> Ref Thermostat TurnOn/ TurnOff (PowerController)

Is this really a PowerController directive that you want, or a SetThermostatMode directive? I tested the "Alexa, turn on the AC" and "Alexa, turn off the AC" and both commands return as below.

Turn On returns:

```
msg : Object
object
topic: ""
name: "Thermostat"
_messageId: "< id>"
_endpointId: "91"
_confId: "bfd0fcf4.bc90e"
command: "SetThermostatMode"
extraInfo: object
empty
payload: "COOL"
acknowledge: true
_msgid: "bb27ffaf.30d2"
```

And Turn Off returns:

```
msg : Object
object
topic: ""
name: "Thermostat"
_messageId: "< id>"
_endpointId: "91"
_confId: "bfd0fcf4.bc90e"
command: "SetThermostatMode"
extraInfo: object
empty
payload: "OFF"
acknowledge: true
_msgid: "65e589ff.6b56a8"
```

> Ref SetTargetTemperature (fail)

I tested "Alexa, set thermostat to 24 degrees" this returns:

```
msg : Object
object
topic: ""
name: "Thermostat"
_messageId: "< id>"
_endpointId: "91"
_confId: "bfd0fcf4.bc90e"
command: "SetTargetTemperature"
extraInfo: object
empty
payload: 24
temperatureScale: "CELSIUS"
acknowledge: true
_msgid: "f3c256cc.03a9d8"
```

**Comment by coldfire84** [comment]
> This is a bug on the web tester as when I do set Air con to twenty-two it works.

@NovaGL, I don't understand!

**Comment by NovaGL** [comment]
It's not related to you. I was typing in commands and the alexa developer site doesn't allow numbers.

**Comment by coldfire84** [comment]
OK, so SetTargetTemperature is working?

I just need to look at extending Thermostat device to allow support for PowerController (logic change in Web UI) and review best option for Fan Speed changes?

**Comment by NovaGL** [comment]
Yeh and tell me how to do responses. As I can't use it properly if I don't the response to give

**Comment by coldfire84** [comment]
PowerController can now be added to Thermostat device. I've tested and can issue a Turn Off/ Turn On command (uses PowerController interface) as well as Turn On AC / Turn Off AC (Uses ThermostatController interface).

Any changes to existing devices require that you re-run discovery.

**Comment by coldfire84** [comment]
> Yeh and tell me how to do responses. As I can't use it properly if I don't the response to give

[Example outputs from each capability/ interface](https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/wiki/Example-Flows-and-Node-Outputs#default-node-outputs).

**Comment by NovaGL** [comment]
Auto acknowledge seems to be ignored now for some reason so I don't know what to do.

It just says the temperature is 22 regardless of what I do.

```
msg.acknowledge = true;
msg.payload = 19
msg.temperatureScale = "CELSIUS";
msg.state = {
    "temperature": msg.payload,
    "thermostatMode": "COOL",
    "thermostatSetPoint" : 17
    
};

return msg
```

**Comment by coldfire84** [comment]
In this example the function node is simply injecting msg.acknowledge : true, but you can perform any validation you like prior to injecting this.
```
msg.acknowledge = true;
return msg;
```
Auto-Acknowledge is disabled on the "alexa-smart-home-v3" node, and unless I inject msg.acknowledge Alexa reports the "device is not responding" and the state update will be dropped.

Using this example flow I'm able to set temperature and adjust temperature, I also get the orrect response and state data - i.e. using the command "Alexa, set <device name> to 18 degrees" Alexa responds with "The heat is set to 18 degrees".

![example](https://user-images.githubusercontent.com/22571742/50723374-b9edee80-10d4-11e9-81bc-a4ce2e8ae76c.PNG)

**Comment by coldfire84** [comment]
I've just tested using an inject node followed by a function node with the following javascript you can update the thermostateSetpoint. This then shows correctly in the Alexa App (i.e. State Update was successfully handled).
```
msg = {
        "acknowledge":true,
        "payload" : {
           "state" : {
               "thermostatSetPoint": 23
               }
            }
        }
return msg;
```

**Comment by NovaGL** [comment]
This is what I tried and nothing updated
````
msg.state = {
    "temperature": msg.payload.temp,
    "thermostatMode": "COOL",
    "thermostatSetPoint" : msg.payload.set_temp
    
};
````

**Comment by coldfire84** [comment]
```
msg.payload.state = {
    "temperature": msg.payload.temp,
    "thermostatMode": "COOL",
    "thermostatSetPoint" : msg.payload.set_temp
    
};
```
Can you share your flow? I assume you are also including msg.acknowledge as true?

When you say nothing happened, what are you expecting to happen?

Have you looked at the logs for Node-RED (this will show if state payload is being handled or dropped).

**Comment by NovaGL** [comment]
Now it's working weird. I think I did msg.state not msg.payload.state.


````
payload: 
	state: 
		temperature: "18"
		thermostatMode: "COOL"
		thermostatSetPoint: "20"
_msgid: ""
acknowledge: true
````
