### ISSUE TITLE
 Device does not support the requested value

### ISSUE THREAD

**Issue by DenisMtfl** [coldfire84/node-red-alexa-home-skill-v3-web#90]
i have an Thermostat and NODE-Red says "Device does not support the requested value"
i've tried with the right response node but no success. Whats the Problem? Is there a log?
In my Node-Red instance there is no error in debug.

**Comment by coldfire84** [comment]
Can you screenshot the device config please and confirm usename. I can review the device config.

Example (working device~) - note the min/ max values and the scale. If you issue a command above max or below min then the command will fail, **before** it hits your Node-RED instance.

![image](https://user-images.githubusercontent.com/22571742/70477342-91cef280-1ad0-11ea-90bc-5d2e2d121eb5.png)

**Comment by coldfire84** [comment]
Please re-open with further information if this is still an issue.
