### ISSUE TITLE
Alexa app can't discover devices.

### ISSUE THREAD

**Issue by sibandrew** [coldfire84/node-red-alexa-home-skill-v3-web#91]
Hi, i followed the Deploy Your Own  guide. All docker containers seem to be working.
I have a problem discovering devices from the Alexa app.
I successfully linked my account installing my own skill:  debug: [Core] `OAuth Token good, token` ...
Right after that, i added a device on the web portal, but when i try to discover devices the Alexa app returns no device found.
Displaying nr-alexav3-web container logs, i noticed this message during discovering: `Missing credentials in config` (more logs below).
In addition, in the node red flow i see the alexa-smart-home-v3 node (linked correctly with the device) keeps reconnecting. Debug:
`Re-connecting to Alexa/ Google Home Skill MQTT server: mqtt.myDomain.it, account username: myUser`

What could I made wrong? Thanks!

**nr-alexav3-web docker container log output:**
```
info: [Discover API] Running device discovery for user: myUser {"timestamp":"2019-12-10T11:24:46.936Z"}
2019-12-10T11:24:46.939348657Z verbose: 54.194.197.109 - - [10/Dec/2019:11:24:46 +0000] "GET /api/v1/devices HTTP/1.0" 200 349 "-" "-"
2019-12-10T11:24:46.939396002Z  {"timestamp":"2019-12-10T11:24:46.938Z"}
2019-12-10T11:24:54.272882423Z debug: [Core] OAuth Token good, token: {
2019-12-10T11:24:54.272977249Z   scope: [ 'access_devices', 'create_devices' ],
2019-12-10T11:24:54.273958598Z   active: true,
2019-12-10T11:24:54.273985247Z   _id: 5def807eca916...,
2019-12-10T11:24:54.274011845Z   application: 5def631f1b3e...,
2019-12-10T11:24:54.274035347Z   user: {
2019-12-10T11:24:54.274052852Z     mqttPass: 'PBKDF2$sha256$901$SbAh1CIAc+SbS5Yy$2...',
2019-12-10T11:24:54.274065172Z     superuser: 0,
2019-12-10T11:24:54.274077422Z     activeServices: [ 'Amazon' ],
2019-12-10T11:24:54.274097866Z     _id: 5def63a21b3e80001263e539,
2019-12-10T11:24:54.274121023Z     username: 'myUser',
2019-12-10T11:24:54.274142158Z     email: 'myEmail',
2019-12-10T11:24:54.274163536Z     country: 'IT',
2019-12-10T11:24:54.274185971Z     region: 'Europe',
2019-12-10T11:24:54.274206995Z     created: 2019-12-10T09:21:38.331Z,
2019-12-10T11:24:54.274229628Z     __v: 0,
2019-12-10T11:24:54.274252102Z     topics: 2
2019-12-10T11:24:54.274272765Z   },
2019-12-10T11:24:54.274295409Z   grant: {
2019-12-10T11:24:54.274316183Z     scope: [ 'access_devices', 'create_devices' ],
2019-12-10T11:24:54.274358251Z     active: true,
2019-12-10T11:24:54.274381405Z     _id: 5def63bd1b...,
2019-12-10T11:24:54.274402995Z     application: 5def631f1b3...,
2019-12-10T11:24:54.274425858Z     user: 5def63a21b3e...,
2019-12-10T11:24:54.274446973Z     code: 'mPyqHpTKxL...',
2019-12-10T11:24:54.274467822Z     __v: 0
2019-12-10T11:24:54.274489764Z   },
2019-12-10T11:24:54.274513011Z   token: 'eqGFEJEf9QmQO8CKJggORmhoHSDAXAS7X...',
2019-12-10T11:24:54.274535351Z   expires: 2019-12-10T11:34:46.550Z,
2019-12-10T11:24:54.274555961Z   __v: 0
2019-12-10T11:24:54.274576646Z } {"timestamp":"2019-12-10T11:24:54.272Z"}
2019-12-10T11:24:54.278651751Z info: [Discover API] Running device discovery for user: asibilio {"timestamp":"2019-12-10T11:24:54.278Z"}
2019-12-10T11:24:54.280145018Z verbose: 54.194.197.109 - - [10/Dec/2019:11:24:54 +0000] "GET /api/v1/devices HTTP/1.0" 200 349 "-" "-"
2019-12-10T11:24:54.280175555Z  {"timestamp":"2019-12-10T11:24:54.279Z"}
2019-12-10T11:25:20.658415187Z Error: connect ETIMEDOUT 169.254.169.254:80
2019-12-10T11:25:20.658490803Z     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1126:14) {
2019-12-10T11:25:20.658509949Z   message: 'Missing credentials in config',
2019-12-10T11:25:20.658523870Z   errno: 'ETIMEDOUT',
2019-12-10T11:25:20.658536551Z   code: 'CredentialsError',
2019-12-10T11:25:20.658549024Z   syscall: 'connect',
2019-12-10T11:25:20.658561273Z   address: '169.254.169.254',
2019-12-10T11:25:20.658573547Z   port: 80,
2019-12-10T11:25:20.658585852Z   time: 2019-12-10T11:25:20.657Z,
2019-12-10T11:25:20.658598181Z   originalError: {
2019-12-10T11:25:20.658610265Z     message: 'Could not load credentials from any providers',
2019-12-10T11:25:20.658622656Z     errno: 'ETIMEDOUT',
2019-12-10T11:25:20.658634813Z     code: 'CredentialsError',
2019-12-10T11:25:20.658655750Z     syscall: 'connect',
2019-12-10T11:25:20.658679714Z     address: '169.254.169.254',
2019-12-10T11:25:20.658696721Z     port: 80,
2019-12-10T11:25:20.658709680Z     time: 2019-12-10T11:25:20.657Z,
2019-12-10T11:25:20.658721785Z     originalError: {
2019-12-10T11:25:20.658733665Z       message: 'EC2 Metadata roleName request returned error',
2019-12-10T11:25:20.658745655Z       errno: 'ETIMEDOUT',
2019-12-10T11:25:20.658757555Z       code: 'ETIMEDOUT',
2019-12-10T11:25:20.658769358Z       syscall: 'connect',
2019-12-10T11:25:20.658781287Z       address: '169.254.169.254',
2019-12-10T11:25:20.658793211Z       port: 80,
2019-12-10T11:25:20.658823426Z       time: 2019-12-10T11:25:20.657Z,
2019-12-10T11:25:20.658837087Z       originalError: [Object]
2019-12-10T11:25:20.658849357Z     }
2019-12-10T11:25:20.658861176Z   }
2019-12-10T11:25:20.658872919Z }
```

**Comment by coldfire84** [comment]
>  Right after that, i added a device on the web portal, but when i try to discover devices the Alexa app returns no device found.

If you enable debug on the lambda instance, what doe the associated CloudWatch logs show? You should see the discovery request and response - drop this into JSON Pretty (or similar tool) and sanitize/ share here.

> 2019-12-10T11:25:20.658415187Z Error: connect ETIMEDOUT 169.254.169.254:80

It looks as if something in your stack hasn't got a valid IP address. This is an [APIPA](https://wiki.wireshark.org/APIPA) address which doesn't look right. Use this command to check IP addresses of containers:

```sudo docker ps -q | xargs -n 1 sudo docker inspect --format '{{ .NetworkSettings.IPAddress }} {{ .Name }}' | sed 's/ \// /'```

> Displaying nr-alexav3-web container logs, i noticed this message during discovering: Missing credentials in config (more logs below).

Have you setup the AWS credentials? (there are two sets, one for CloudWatch Logging (using a file for use in Watson) and one for Out of Band Alexa State Updates (specified at runtime in an env variable). 

> In addition, in the node red flow i see the alexa-smart-home-v3 node (linked correctly with the device) keeps reconnecting. Debug:
Re-connecting to Alexa/ Google Home Skill MQTT server: mqtt.myDomain.it, account username: myUser

Check the docker command output above. It looks as if there is something not quite right with your configuration.

**Comment by sibandrew** [comment]
Thanks for your answer.


> It looks as if something in your stack hasn't got a valid IP address. This is an APIPA address which doesn't look right. Use this command to check IP addresses of containers:

I checked ip addresses of containers, but .NetworkSettings.IPAddress is empty for all. The only ip address for each container is specified for .NetworkSettings.Networks.IPAddress.

**Could this be an issue?**

I attach a json file with an example of container NetworksSettings:
[container_networksettings.zip](https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/files/3949734/container_networksettings.zip)

**Comment by sibandrew** [comment]
> If you enable debug on the lambda instance, what doe the associated CloudWatch logs show? You should see the discovery request and response - drop this into JSON Pretty (or similar tool) and sanitize/ share here.

> Have you setup the AWS credentials? (there are two sets, one for CloudWatch Logging (using a file for use in Watson) and one for Out of Band Alexa State Updates (specified at runtime in an env variable).

**Now alexa can discover devices!**
I wrote wrong credentials in the file /var/docker/red/credentials. Now this is fixed.
Sorry, but i don't know what you mean with Out of Band Alexa State Updates credentials. if you mean `ALEXA_CLIENTID` and `ALEXA_CLIENTSECRET`, yes i set them correctly before creating container.

**I still have a big problem regarding mqtt communication**:

> In addition, in the node red flow i see the alexa-smart-home-v3 node (linked correctly with the device) keeps reconnecting. Debug:
> Re-connecting to Alexa/ Google Home Skill MQTT server: mqtt.myDomain.it, account username: myUser

![node-reconnecting](https://user-images.githubusercontent.com/48277672/70625641-20538900-1c23-11ea-8f91-2f393577ccf8.PNG)


Unfortunately this issue remains...
Debug node attached to alexa-smart-home-v3 node in my node-red flow still displays in loop:
`Re-connecting to Alexa/ Google Home Skill MQTT server: mqtt.myDomain.it, account username: myUser`

On CloudWatch, for my site group log, i can see only this error:
`{
    "level": "error",
    "message": "[Alexa API] MQTT connect error"
}`
Lambda logs, instead, didn't return any error log related to mqtt.

If i try to turn on (or off) the light from the Alexa app, app displays "light unreachable" and in the mosquitto container logs:
` 1576071782: |-- mosquitto_auth_acl_check(..., alexaAPI_10dbde66, mqttuser, message/asibilio/2, 2)`
 `1576071782: |--  Expired [F1D8C24FB4E9725A325150866ABC3C614546958E] for (alexaAPI_10dbde66,mqttuser,2)`
 `1576071782: |-- aclcheck(mqttuser, message/asibilio/2, 2) SUPERUSER=Y by mongo`
 `1576071782: |--  Cached  [F1D8C24FB4E9725A325150866ABC3C614546958E] for (alexaAPI_10dbde66,mqttuser,2)`
 `1576071782: |--  Cleanup [16FAA1D09CA4EED37810D42270AD890604FF2ED9]`

Do you have any suggestion for me?

**Comment by coldfire84** [comment]
> On CloudWatch, for my site group log, i can see only this error:
{ "level": "error", "message": "[Alexa API] MQTT connect error" }

This means the API server  cannot connect to MQTT (which it is hosting!). So it is not entirely surprising Node-RED won't connect either. Can you confirm the MQTT docker image you used to build the service? Should be ```coldfire84/mosquitto-auth:development```

In your mosquitto MQTT server logs you should see entries such as the below which show the mongodb <> mqtt auth validation is working:

```
2019-12-11T17:00:32: New connection from 172.18.0.1 on port 8883.
1576083632: |-- mosquitto_auth_unpwd_check(username)
1576083632: |-- ** checking backend mongo
1576083632: |-- getuser(username) AUTHENTICATED=1 by mongo
```

Specifically search your MQTT server logs for ``` AUTHENTICATED=1 by mongo``` 

Worth checking to see if you can connect to the MQTT instance using the troubleshooting commands outlined [here](https://red.cb-net.co.uk/docs#troubleshooting) (try form the server itself and from a remote client). You'll need to change the server FQDN in the commands to match your own instance/ MQTT server.

**Comment by sibandrew** [comment]
> Can you confirm the MQTT docker image you used to build the service?

Yes, mosquitto docker image is: coldfire84/mosquitto-auth:development.

> In your mosquitto MQTT server logs you should see entries such as the below which show the mongodb <> mqtt auth validation is working:

I can see those logs for my mosquitto, where username is equal to my _MQTT_USER_:
```
2019-12-16T09:09:08: New connection from 172.20.0.1 on port 1883.
1576487348: |-- mosquitto_auth_unpwd_check(username)
1576487348: |-- ** checking backend mongo
1576487348: |-- getuser(username) AUTHENTICATED=1 by mongo
```

I noticed that new connection message is from `172.20.0.1` and port `1883`.
Looking your example logs, I think ip address should be `172.18.x.x` and port `8883`.

> Worth checking to see if you can connect to the MQTT instance using the troubleshooting commands outlined here (try form the server itself and from a remote client). You'll need to change the server FQDN in the commands to match your own instance/ MQTT server.

I'm trying to run the command:
```mosquitto_sub -h myMqttFQDN  -t '#' -v -u myMQTT_USER -P 'myMQTT_PASSWORD' --capath /etc/ssl/certs --id test-mqttuser -p 8883```
But, after several seconds, it returns:
`Error: Network is unreachable`

**Comment by sibandrew** [comment]
**Docker network subnet is 172.20.0.0/16 instead of 172.18.0.0/16**

I think the main problem is the wrong docker network subnet.

If i run `docker network inspect nr-alexav3 | grep Subnet` it returns:
`"Subnet": "172.20.0.0/16",`

So i ask to myself, **how i can "set" docker network subnet? What i could made wrong creating docker network nr-alexav3?**

Thanks!

**Comment by coldfire84** [comment]
> Looking your example logs, I think ip address should be 172.18.x.x and port 8883.

No, for the API itself to connect to MQTT it uses 1883 (its on a private Docker network, so this isn't an issue). Any external client connecting in MUST use 8883 (suggested firewall rules enforce this/ there is no rule to allow 1883 externally).

> So i ask to myself, how i can "set" docker network subnet? What i could made wrong creating docker network nr-alexav3?

I'd just delete and re-create the [firewall rules](https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/wiki/Deploy-Your-Own#firewall-configuration
) to match your environment. I'm unsure why you have a different subnet, it may be the subnet range generated is random on creating the docker network. I've built / migrated this service between different hosting providers and always ended up with the same subnet so  not sure why this is an issue for you. Everything uses DNS host names expect for the firewall rules.

This would explain your MQTT connectivity issues.

**Comment by sibandrew** [comment]
> No, for the API itself to connect to MQTT it uses 1883 (its on a private Docker network, so this isn't an issue). Any external client connecting in MUST use 8883 (suggested firewall rules enforce this/ there is no rule to allow 1883 externally).

Ok, got it.

> This would explain your MQTT connectivity issues.

I rebuild the docker network and all containers forcing docker subnet 172.18.0.0/16.
All is working as before, but that problem remains.

If i run on my server:
`mosquitto_sub -h myMqttFQDN -t '#' -v -u myUser-P 'myPassword' --capath /etc/ssl/certs --id test-myUser -p 8883`
I don't get any messages until the `Error: Network is unreachable`

**Trying to find the error...**

My ufw seems to be properly set:
```
#ufw status

Status: active

To                         Action      From
--                         ------      ----
OpenSSH                    ALLOW       Anywhere
22                         ALLOW       Anywhere
443                        ALLOW       Anywhere
80                         ALLOW       Anywhere
8883                       ALLOW       Anywhere
3000/tcp                   ALLOW       172.18.0.0/16
1883/tcp                   ALLOW       172.18.0.0/16
27017/tcp                  ALLOW       172.18.0.0/16
6397/tcp                   ALLOW       172.18.0.0/16
OpenSSH (v6)               ALLOW       Anywhere (v6)
22 (v6)                    ALLOW       Anywhere (v6)
443 (v6)                   ALLOW       Anywhere (v6)
80 (v6)                    ALLOW       Anywhere (v6)
8883 (v6)                  ALLOW       Anywhere (v6)
```

If i try to turn on my light from the Alexa app i get:
```
1576578629: |-- mosquitto_auth_acl_check(..., alexaAPI_dd9b313f, MQTT_USER, command/myUser/2, 2)
1576578629: |--  Expired [0647B6F71B9B6A93E0356952050E902223AF99AF] for (alexaAPI_dd9b313f,MQTT_USER,2)
2019-12-17T10:30:29: Received PUBLISH from alexaAPI_dd9b313f (d0, q0, r0, m0, 'command/myUser/2', ... (236 bytes))
1576578629: |-- aclcheck(MQTT_USER, command/myUser/2, 2) SUPERUSER=Y by mongo
1576578629: |--  Cached  [0647B6F71B9B6A93E0356952050E902223AF99AF] for (alexaAPI_dd9b313f,MQTT_USER,2)
```

Please correct me if i wrong, i think alexaAPI doesn't reach the mosquitto directly, but they pass from nr-alexav3-web -> mosquitto:1883. So, i'm assuming mosquitto container is not reachable from remote (through 8883).
Do you know a way to debug that?

Thanks again.

**Comment by sibandrew** [comment]
Port binding for mosquitto container seems properly set:
```
"NetworkMode": "nr-alexav3",
            "PortBindings": {
                "1883/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "1883"
                    }
                ],
                "8883/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8883"
                    }
                ]
            },


"NetworkSettings": {
            "Bridge": "",
            "SandboxID": "2b164b1119f4a3379ef6a3a7b22f9c08b54b7b6db7c7c96b2fedae8e0acaece5",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "1883/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "1883"
                    }
                ],
                "8883/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8883"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/2b164b1119f4",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nr-alexav3": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "0df54ce45575"
                    ],
                    "NetworkID": "12080e84f42256b17facba6a7f094e358c61c1104d6b88cab6ce7d902cdd91c4",
                    "EndpointID": "e98426a66b07011b1fa311fd86072f16e1bf35fccb74b416ae0dd423f1d69aec",
                    "Gateway": "172.18.0.1",
                    "IPAddress": "172.18.0.5",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:12:00:05",
                    "DriverOpts": null
                }
            }
        }


```

**Comment by sibandrew** [comment]
I'm going to close this issue in order to open a new one more relevant.
