### ISSUE TITLE
Cannot connect to mqtt

### ISSUE THREAD

**Issue by sibandrew** [coldfire84/node-red-alexa-home-skill-v3-web#93]
I followed the "Deploy Your Own" guide and all seems to work, except the connection to mqtt.

**Node reconnecting**
When i insert an alexa-smart-home-v3 node into the node red flow and deploy, the node goes reconnecting in loop:
![node-reconnecting](https://user-images.githubusercontent.com/48277672/71241965-1c9fc080-230d-11ea-8dd4-54beefa4643a.PNG)
And node-red logs:
`Re-connecting to Alexa/ Google Home Skill MQTT server: mqtt.myDomain.it, account username: myUser`

**Trying to find server issue...**
-----------------------------------

**Mosquitto**
If i try to run the `mosquitto_sub` command from my server like [here](https://red.cb-net.co.uk/docs#troubleshooting), i get no response from mosquitto.

On mosquitto docker logs, i can only see:
``` 
 2019-12-20T08:51:40: Received PINGREQ from alexaAPI_das6t78
 2019-12-20T08:51:40: Sending PINGRESP to alexaAPI_das6t78
 2019-12-20T08:51:40: Received PINGREQ from stateAPI_e936d4ec
 2019-12-20T08:51:40: Sending PINGRESP to stateAPI_e936d4ec
 2019-12-20T08:52:40: Received PINGREQ from gHomeAPI_f72a7872
 2019-12-20T08:52:40: Sending PINGRESP to gHomeAPI_f72a7872
```
[This](https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/files/3987526/docker-inspect-mosquitto.txt) is the file with the output of `#docker inspect mosquitto`.

**Firewall**
Running `#ufw status:`
``` 
Status: active

To                         Action      From
--                         ------      ----
OpenSSH                    ALLOW       Anywhere
22                         ALLOW       Anywhere
443                        ALLOW       Anywhere
80                         ALLOW       Anywhere
8883                       ALLOW       Anywhere
3000/tcp                   ALLOW       172.18.0.0/16
1883/tcp                   ALLOW       172.18.0.0/16
27017/tcp                  ALLOW       172.18.0.0/16
6397/tcp                   ALLOW       172.18.0.0/16
OpenSSH (v6)               ALLOW       Anywhere (v6)
22 (v6)                    ALLOW       Anywhere (v6)
443 (v6)                   ALLOW       Anywhere (v6)
80 (v6)                    ALLOW       Anywhere (v6)
8883 (v6)                  ALLOW       Anywhere (v6)
```

**Processes listening**
These are processes listening on my server:
``` 
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      1054/systemd-resolv
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1409/sshd
tcp6       0      0 :::80                   :::*                    LISTEN      19026/docker-proxy
tcp6       0      0 :::8883                 :::*                    LISTEN      18695/docker-proxy
tcp6       0      0 :::22                   :::*                    LISTEN      1409/sshd
tcp6       0      0 :::3000                 :::*                    LISTEN      18850/docker-proxy
tcp6       0      0 :::443                  :::*                    LISTEN      19012/docker-proxy
tcp6       0      0 :::1883                 :::*                    LISTEN      18709/docker-proxy
tcp6       0      0 :::27017                :::*                    LISTEN      14565/docker-proxy
udp        0      0 127.0.0.53:53           0.0.0.0:*                           1054/systemd-resolv
``` 

**Do you have any idea what could be the problem regarding mosquitto no response?**

**Comment by sibandrew** [comment]
**PROBLEM SOLVED!!**

It was a simple error into the dns proxy settings of cloudflare. Thank you very much for the support.

**Comment by coldfire84** [comment]
Keep an eye on: https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/wiki/Release-Upgrade-Paths#release-011

I've just released a revised code-base for Development branch, and to use this you need to perform some task in the back-end database.

Key changes here: https://github.com/coldfire84/node-red-alexa-home-skill-v3-web/wiki/Features-Roadmap#release-011-current-development-branch
