### ISSUE TITLE
Unable to reset PW

### ISSUE THREAD

**Issue by a011528** [coldfire84/node-red-alexa-home-skill-v3-web#94]
Just to let you im unable to reset my PW on your site and hence authentication is failing from node red

**Comment by a011528** [comment]
you can close, it seems fixed again

**Comment by coldfire84** [comment]
Thanks for raising this - I see there was an issue relating to event logging that meant you got an error message, although the password change *was* successful. I've modified the code to address the issue and redeployed so this shouldn't impact anyone else.
