### ISSUE TITLE
Issue - skill no longer responds

### ISSUE THREAD

**Issue by a011528** [coldfire84/node-red-alexa-home-skill-v3-web#95]
The Skill is no longer working as expected in Node Red. I have connectivity ID/PW working as i can see devices, i can login to you web service add / remove devices and use Alexa discovery to synchronize the the changes, but the skills is no longer passing messages along. 

Issue started to occur over last 48 hrs. first connectivity issues (connection being refused), then PW reset not working on your site, then incorrect Token, which is all working now. but the alexa Skill is not responding and ive inserted debugs but messages are not being passed along. 

Ive gone as far as a Total rebuild on my side of 1. Raspberry 2. Node Red 3 add removed skills, all my other skills, flows work except when i use your skills, alexa responds that the devices are not working. I also Un-linked Skill and re-linked your skill.

1. Node-Red is working (V1.03)
2. Other Skills in Node red + flows working 
3. Your skill is installed and Authentication is working (0.4.64)
4. I see devices being refreshed (+when i add/remove devices on your web service)
5. Alexa discovery is working
5. **Yet messages/payloads are Not being passed along** 

manual injection ifor debug s working and as said other skills + flows are working.

**Comment by coldfire84** [comment]
Please reset your account password via the web interface again and see if the recent commit/. change I have made resolves the MQTT issues you are having. Can you also supply Node-RED console logs if the issue persists.

**Comment by a011528** [comment]
Just tried, to reset the PW, wont accept the change in the web interface (even though it says accepted), I also tried resetting the PW by choosing forgot, 3 x times, and although it states the PW has changed, does not allow me to login using new credentials, i had to revert to the old PW to login.

**Comment by coldfire84** [comment]
Please re-test, I've made further changes to the reset password code.

**Comment by a011528** [comment]
Thx for being supportive. PW reset is working, including authentication. Devices however still fail to respond

**Comment by coldfire84** [comment]
Have you checked the /docs information on the website and tested the mosquitto_sub command:
```
mosquitto_sub -h mq-red.cb-net.co.uk -t '#' -v -u <bridge_username> -P '<bridge password>' --capath /etc/ssl/certs --id test-<bridge_username> -p 8883
```
You should see command information when you issue a voice command. If you do, it's your Node-RED instance, in which case I'd recreate the account configuration. If you see nothing in the mosquitto_sub output then come back to me.

**Comment by coldfire84** [comment]
To add, the skill account link looks fine and I can see commands hitting the API for your user account, it is 'simply' that the command isn't being handled by the local Node-RED instance and is timing out, which generates the error message.

**Comment by a011528** [comment]
Thank you, i had to uninstall and re-install MQTT Broker. it is now working again.
