### ISSUE TITLE
[Mongo] empty users database --> cannot connect

### ISSUE THREAD

**Issue by tomtom30** [coldfire84/node-red-alexa-home-skill-v3-web#97]
**Describe the bug**
I have deploy containers with the documentation but I can't connect to mqtt because of empty users database in mongo ( In my mind ).

**To Reproduce**
I use this docker-compose:
```
version: '3'

services:
  mongodb:
    image: mongo:latest
    restart : unless-stopped
    container_name : mongodb_alexa
    ports:
      - 27017:27017
   environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_ADMIN
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    
    volumes:
      - /var/lib/docker/volumes/mongodb/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      - /var/lib/docker/volumes/mongodb/etc/:/etc/mongo/
      - /var/lib/docker/volumes/mongodb/data/:/data/db
      - /var/lib/docker/volumes/mongodb/backup:/backup
    networks:
      - nr-alexav3
    logging:
      options:
        max-size: "10m"
        max-file: "5"
mosquitto_alexa:
    image: coldfire84/mosquitto-auth:development
    container_name: mosquitto_alexa
    restart : unless-stopped
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - /var/lib/docker/volumes/mosquitto_alexa/config:/mosquitto/config
      - /var/lib/docker/volumes/mosquitto_alexa/data:/mosquitto/data
      - /var/lib/docker/volumes/mosquitto_alexa/log:/mosquitto/log
      - /home/docker-user/docker-compose/alexa/certs:/etc/letsencrypt
   logging:
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - nr-alexav3
 redis:
    image: redis:latest
    restart: unless-stopped
    container_name: redis_alexa
    volumes:
      - /var/lib/docker/volumes/redis/data:/data
    networks:
      - nr-alexav3
    logging:
      options:
        max-size: "10m"
        max-file: "5"
 alexav3-web:
    image: coldfire84/nr-alexav3-web:development
    restart: unless-stopped
    container_name: alexav3-web
    ports:
      - 3000:3000
    volumes:
      - ./certs:/etc/letsencrypt 
      - /var/lib/docker/volumes/red/credentials:/root/.aws/credentials
      - /var/lib/docker/volumes/red/.env:/usr/src/app/.env
      - /var/lib/docker/volumes/red/.ghomejwt:/usr/src/app/ghomejwt.json
    depends_on:
      - redis
      - mosquitto_alexa
      - mongodb
    logging:
      options:
        max-size: "10m"
        max-file: "5"
        
networks:
  nr-alexav3:
    external: true
```
with not modified mosquitto.conf

with this node-red-alexa-smart-home-v3.conf

```
auth_plugin /usr/local/lib/auth-plug.so
auth_opt_backends mongo
auth_opt_mongo_uri mongodb://tomtom:mypassword@mongodb_alexa:27017
auth_opt_mongo_database users
auth_opt_mongo_user_username_prop username
auth_opt_mongo_user_password_prop mqttPass
auth_opt_mongo_user_superuser_prop superuser
auth_opt_mongo_user_coll accounts
auth_opt_mongo_topiclist_coll topics
auth_opt_mongo_user_topiclist_fk_prop topics
auth_opt_mongo_topiclist_key_prop _id
auth_opt_mongo_topiclist_topics_prop topics

log_type all

listener 8883
certfile /etc/letsencrypt/live/mydomain.ddns.net/certificate.crt
cafile /etc/letsencrypt/live/mydomain.ddns.net/ca2.pem
keyfile /etc/letsencrypt/live/mydomain.ddns.net/privatekey.key
```

**Expected behavior**
I try to test 8883 connection to MQTT with 

`mosquitto_sub -h mydomain.ddns.net -u tomtom -P mypassword -p 8883 -t command/tomtom/# -i test_client -v --cafile /home/docker-user/docker-compose/alexa/certs/live/rednode.ddns.net/ca2.pem`

**Log Output**
I get this 

> Connection Refused: not authorised.
```
1579711550: Loading config file /mosquitto/config/conf.d/node-red-alexa-smart-home-v3.conf
2020-01-22T16:45:50: mosquitto version 1.6.8 starting
2020-01-22T16:45:50: Config loaded from /mosquitto/config/mosquitto.conf.
2020-01-22T16:45:50: Loading plugin: /usr/local/lib/auth-plug.so
1579711551: |-- *** auth-plug: startup
1579711551: |-- ** Configured order: mongo

2020-01-22T16:45:51:  ├── Username/password checking enabled.
2020-01-22T16:45:51:  ├── TLS-PSK checking enabled.
2020-01-22T16:45:51:  └── Extended authentication not enabled.
2020-01-22T16:45:51: Opening ipv4 listen socket on port 8883.
2020-01-22T16:45:51: Opening ipv6 listen socket on port 8883.
2020-01-22T16:45:51: Opening ipv4 listen socket on port 1883.
2020-01-22T16:45:51: Opening ipv6 listen socket on port 1883.

2020-01-22T16:46:29: New connection from 192.168.1.1 on port 8883.
1579711589: |-- mosquitto_auth_unpwd_check(tomtom)
1579711589: |-- ** checking backend mongo
1579711589: |-- getuser(tomtom) AUTHENTICATED=0 by none
2020-01-22T16:46:29: Sending CONNACK to 192.168.1.1 (0, 5)
2020-01-22T16:46:29: Socket error on client <unknown>, disconnecting.
2020-01-22T16:46:30: New connection from 192.168.1.1 on port 8883.
1579711590: |-- mosquitto_auth_unpwd_check(tomtom)
1579711590: |-- ** checking backend mongo
2020-01-22T16:46:30: Sending CONNACK to 192.168.1.1 (0, 5)
1579711590: |-- getuser(tomtom) AUTHENTICATED=0 by none
2020-01-22T16:46:30: Socket error on client <unknown>, disconnecting.
```

**Environment (please complete the following information):**
I have all my containers in home linux ubuntu 18.04 on docker 19.03.5

**Additional context**

When I browse mongodb users db with tomtom (mongodb compass) :
--> connection is ok
--> users database is here but empty

If someone can help me to understand where is my mistake? is users db might be populated?
Or is it a bug ? 

Really thanks for your help

**Comment by coldfire84** [comment]
Did you create the docker-entrypoint-initdb.d/mongodb-accounts.sh script, that contains user account definitions for MongoDB first run?

https://docs.cb-net.co.uk/en/development-cleanup/deploy-your-own.html#define-service-accounts
https://docs.cb-net.co.uk/en/development-cleanup/deploy-your-own.html#mongodb-container-account-creation

**Comment by tomtom30** [comment]
yes I did : 

```
mongo mongodb://localhost/users --authenticationDatabase admin -u 'admin' -p 'mypassword' --eval '
    db.createUser({
        user: "tomtom",
        pwd: "mypassword",
        roles: [{
            role: "readWrite",
            db: "users"
        }]
    })'

mongo mongodb://localhost/sessions --authenticationDatabase admin -u 'admin' -p 'mypassword' --eval '
    db.createUser({
        user: "tomtom",
        pwd: "mypassword",
        roles: [{
            role: "dbOwner",
            db: "sessions"
        }]
    })'

mongo mongodb://localhost/admin --authenticationDatabase admin -u 'admin' -p 'mypassword' --eval '
    db.createUser({
        user: "tomtom",
        pwd: "mypassword",
        roles: [{
            role: "read",
            db: "users"
        }]
    })'
```

Here is the log for mongo startup : 

> about to fork child process, waiting until server is ready for connections.
> forked process: 28
> 2020-01-22T18:11:12.535+0000 I  CONTROL  [main] ***** SERVER RESTARTED *****
> 2020-01-22T18:11:12.554+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
> 2020-01-22T18:11:12.571+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=28 port=27017 dbpath=/data/db 64-bit host=ebcd45e1c90f
> 2020-01-22T18:11:12.571+0000 I  CONTROL  [initandlisten] db version v4.2.1
> 2020-01-22T18:11:12.571+0000 I  CONTROL  [initandlisten] git version: edf6d45851c0b9ee15548f0f847df141764a317e
> 2020-01-22T18:11:12.571+0000 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
> 2020-01-22T18:11:12.571+0000 I  CONTROL  [initandlisten] allocator: tcmalloc
> 2020-01-22T18:11:12.571+0000 I  CONTROL  [initandlisten] modules: none
> 2020-01-22T18:11:12.571+0000 I  CONTROL  [initandlisten] build environment:
> 2020-01-22T18:11:12.571+0000 I  CONTROL  [initandlisten]     distmod: ubuntu1804
> 2020-01-22T18:11:12.571+0000 I  CONTROL  [initandlisten]     distarch: x86_64
> 2020-01-22T18:11:12.571+0000 I  CONTROL  [initandlisten]     target_arch: x86_64
> 2020-01-22T18:11:12.571+0000 I  CONTROL  [initandlisten] options: { net: { bindIp: "127.0.0.1", port: 27017, tls: { mode: "disabled" } }, processManagement: { fork: true, pidFilePath: "/tmp/docker-entrypoint-temp-mongod.pid" }, systemLog: { destination: "file", logAppend: true, path: "/proc/1/fd/1" } }
> 2020-01-22T18:11:12.572+0000 I  STORAGE  [initandlisten]
> 2020-01-22T18:11:12.572+0000 I  STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
> 2020-01-22T18:11:12.572+0000 I  STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
> 2020-01-22T18:11:12.572+0000 I  STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=5350M,cache_overflow=(file_max=0M),session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress],
> 2020-01-22T18:11:13.409+0000 I  STORAGE  [initandlisten] WiredTiger message [1579716673:409803][28:0x7fe4c5aa4b00], txn-recover: Set global recovery timestamp: (0,0)
> 2020-01-22T18:11:13.420+0000 I  RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
> 2020-01-22T18:11:13.429+0000 I  STORAGE  [initandlisten] Timestamp monitor starting
> 2020-01-22T18:11:13.431+0000 I  CONTROL  [initandlisten]
> 2020-01-22T18:11:13.431+0000 I  CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
> 2020-01-22T18:11:13.431+0000 I  CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
> 2020-01-22T18:11:13.431+0000 I  CONTROL  [initandlisten]
> 2020-01-22T18:11:13.447+0000 I  STORAGE  [initandlisten] createCollection: admin.system.version with provided UUID: 94e1345d-dc4a-4c7a-bfde-8a25b531bf00 and options: { uuid: UUID("94e1345d-dc4a-4c7a-bfde-8a25b531bf00") }
> 2020-01-22T18:11:13.457+0000 I  INDEX    [initandlisten] index build: done building index _id_ on ns admin.system.version
> 2020-01-22T18:11:13.458+0000 I  SHARDING [initandlisten] Marking collection admin.system.version as collection version: <unsharded>
> 2020-01-22T18:11:13.458+0000 I  COMMAND  [initandlisten] setting featureCompatibilityVersion to 4.2
> 2020-01-22T18:11:13.459+0000 I  SHARDING [initandlisten] Marking collection local.system.replset as collection version: <unsharded>
> 2020-01-22T18:11:13.463+0000 I  STORAGE  [initandlisten] Flow Control is enabled on this deployment.
> 2020-01-22T18:11:13.465+0000 I  SHARDING [initandlisten] Marking collection admin.system.roles as collection version: <unsharded>
> 2020-01-22T18:11:13.468+0000 I  STORAGE  [initandlisten] createCollection: local.startup_log with generated UUID: 330b1c00-2172-41bb-afca-91c24a845d09 and options: { capped: true, size: 10485760 }
> 2020-01-22T18:11:13.476+0000 I  INDEX    [initandlisten] index build: done building index _id_ on ns local.startup_log
> 2020-01-22T18:11:13.476+0000 I  SHARDING [initandlisten] Marking collection local.startup_log as collection version: <unsharded>
> 2020-01-22T18:11:13.477+0000 I  FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
> 2020-01-22T18:11:13.487+0000 I  SHARDING [LogicalSessionCacheRefresh] Marking collection config.system.sessions as collection version: <unsharded>
> 2020-01-22T18:11:13.487+0000 I  NETWORK  [initandlisten] Listening on /tmp/mongodb-27017.sock
> 2020-01-22T18:11:13.487+0000 I  NETWORK  [initandlisten] Listening on 127.0.0.1
> 2020-01-22T18:11:13.487+0000 I  NETWORK  [initandlisten] waiting for connections on port 27017
> child process started successfully, parent exiting
> 2020-01-22T18:11:13.531+0000 I  CONTROL  [LogicalSessionCacheReap] Sessions collection is not set up; waiting until next sessions reap interval: config.system.sessions does not exist
> 2020-01-22T18:11:13.531+0000 I  STORAGE  [LogicalSessionCacheRefresh] createCollection: config.system.sessions with provided UUID: db668b27-c43b-4dd2-8a96-a4628532cbde and options: { uuid: UUID("db668b27-c43b-4dd2-8a96-a4628532cbde") }
> 2020-01-22T18:11:13.540+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: done building index _id_ on ns config.system.sessions
> 2020-01-22T18:11:13.548+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: starting on config.system.sessions properties: { v: 2, key: { lastUse: 1 }, name: "lsidTTLIndex", ns: "config.system.sessions", expireAfterSeconds: 1800 } using method: Hybrid
> 2020-01-22T18:11:13.548+0000 I  INDEX    [LogicalSessionCacheRefresh] build may temporarily use up to 500 megabytes of RAM
> 2020-01-22T18:11:13.548+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: collection scan done. scanned 0 total records in 0 seconds
> 2020-01-22T18:11:13.549+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: inserted 0 keys from external sorter into index in 0 seconds
> 2020-01-22T18:11:13.551+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: done building index lsidTTLIndex on ns config.system.sessions
> 2020-01-22T18:11:13.862+0000 I  NETWORK  [listener] connection accepted from 127.0.0.1:35184 #1 (1 connection now open)
> 2020-01-22T18:11:13.865+0000 I  NETWORK  [conn1] received client metadata from 127.0.0.1:35184 conn1: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.2.1" }, os: { type: "Linux", name: "Ubuntu", architecture: "x86_64", version: "18.04" } }
> 2020-01-22T18:11:13.874+0000 I  NETWORK  [conn1] end connection 127.0.0.1:35184 (0 connections now open)
> 2020-01-22T18:11:13.995+0000 I  NETWORK  [listener] connection accepted from 127.0.0.1:35186 #2 (1 connection now open)
> 2020-01-22T18:11:13.996+0000 I  NETWORK  [conn2] received client metadata from 127.0.0.1:35186 conn2: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.2.1" }, os: { type: "Linux", name: "Ubuntu", architecture: "x86_64", version: "18.04" } }
> 2020-01-22T18:11:14.000+0000 I  SHARDING [ftdc] Marking collection local.oplog.rs as collection version: <unsharded>
> 2020-01-22T18:11:14.075+0000 I  SHARDING [conn2] Marking collection admin.system.users as collection version: <unsharded>
> 2020-01-22T18:11:14.075+0000 I  STORAGE  [conn2] createCollection: admin.system.users with generated UUID: 2b8f6d5c-4a0f-4f2e-9f8b-011e6daa2a52 and options: {}
> 2020-01-22T18:11:14.082+0000 I  INDEX    [conn2] index build: done building index _id_ on ns admin.system.users
> 2020-01-22T18:11:14.086+0000 I  INDEX    [conn2] index build: done building index user_1_db_1 on ns admin.system.users
> Successfully added user: {
>         "user" : "admin",
>         "roles" : [
>                 {
>                         "role" : "root",
>                         "db" : "admin"
>                 }
>         ]
> }
> 2020-01-22T18:11:14.091+0000 E  -        [main] Error saving history file: FileOpenFailed: Unable to open() file /home/mongodb/.dbshell: No such file or directory
> 2020-01-22T18:11:14.093+0000 I  NETWORK  [conn2] end connection 127.0.0.1:35186 (0 connections now open)
> 
> /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/mongodb-accounts.sh
> MongoDB shell version v4.2.1
> connecting to: mongodb://localhost:27017/users?authSource=admin&compressors=disabled&gssapiServiceName=mongodb
> 2020-01-22T18:11:14.204+0000 I  NETWORK  [listener] connection accepted from 127.0.0.1:35232 #3 (1 connection now open)
> 2020-01-22T18:11:14.205+0000 I  NETWORK  [conn3] received client metadata from 127.0.0.1:35232 conn3: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.2.1" }, os: { type: "Linux", name: "Ubuntu", architecture: "x86_64", version: "18.04" } }
> 2020-01-22T18:11:14.260+0000 I  ACCESS   [conn3] Successfully authenticated as principal admin on admin from client 127.0.0.1:35232
> Implicit session: session { "id" : UUID("b7693698-3817-4081-8a1b-f298d5a3f34d") }
> MongoDB server version: 4.2.1
> Successfully added user: {
>         "user" : "tomtom",
>         "roles" : [
>                 {
>                         "role" : "readWrite",
>                         "db" : "users"
>                 }
>         ]
> }
> 2020-01-22T18:11:14.334+0000 I  NETWORK  [conn3] end connection 127.0.0.1:35232 (0 connections now open)
> MongoDB shell version v4.2.1
> connecting to: mongodb://localhost:27017/sessions?authSource=admin&compressors=disabled&gssapiServiceName=mongodb
> 2020-01-22T18:11:14.436+0000 I  NETWORK  [listener] connection accepted from 127.0.0.1:35264 #4 (1 connection now open)
> 2020-01-22T18:11:14.436+0000 I  NETWORK  [conn4] received client metadata from 127.0.0.1:35264 conn4: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.2.1" }, os: { type: "Linux", name: "Ubuntu", architecture: "x86_64", version: "18.04" } }
> 2020-01-22T18:11:14.477+0000 I  ACCESS   [conn4] Successfully authenticated as principal admin on admin from client 127.0.0.1:35264
> Implicit session: session { "id" : UUID("c1b32720-3e74-4960-852a-c22797e59c9a") }
> MongoDB server version: 4.2.1
> Successfully added user: {
>         "user" : "tomtom",
>         "roles" : [
>                 {
>                         "role" : "dbOwner",
>                         "db" : "sessions"
>                 }
>         ]
> }
> 2020-01-22T18:11:14.544+0000 I  NETWORK  [conn4] end connection 127.0.0.1:35264 (0 connections now open)
> MongoDB shell version v4.2.1
> connecting to: mongodb://localhost:27017/admin?authSource=admin&compressors=disabled&gssapiServiceName=mongodb
> 2020-01-22T18:11:14.645+0000 I  NETWORK  [listener] connection accepted from 127.0.0.1:35268 #5 (1 connection now open)
> 2020-01-22T18:11:14.645+0000 I  NETWORK  [conn5] received client metadata from 127.0.0.1:35268 conn5: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.2.1" }, os: { type: "Linux", name: "Ubuntu", architecture: "x86_64", version: "18.04" } }
> 2020-01-22T18:11:14.686+0000 I  ACCESS   [conn5] Successfully authenticated as principal admin on admin from client 127.0.0.1:35268
> Implicit session: session { "id" : UUID("7df94e97-69ae-4973-8dd8-566d1c22fd03") }
> MongoDB server version: 4.2.1
> Successfully added user: {
>         "user" : "tomtom",
>         "roles" : [
>                 {
>                         "role" : "read",
>                         "db" : "users"
>                 }
>         ]
> }
> 2020-01-22T18:11:14.752+0000 I  NETWORK  [conn5] end connection 127.0.0.1:35268 (0 connections now open)
> 
> 2020-01-22T18:11:14.788+0000 I  CONTROL  [main] ***** SERVER RESTARTED *****
> 2020-01-22T18:11:14.791+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
> killing process with pid: 28
> 2020-01-22T18:11:14.796+0000 I  CONTROL  [signalProcessingThread] got signal 15 (Terminated), will terminate after current cmd ends
> 2020-01-22T18:11:14.797+0000 I  NETWORK  [signalProcessingThread] shutdown: going to close listening sockets...
> 2020-01-22T18:11:14.797+0000 I  NETWORK  [signalProcessingThread] removing socket file: /tmp/mongodb-27017.sock
> 2020-01-22T18:11:14.797+0000 I  -        [signalProcessingThread] Stopping further Flow Control ticket acquisitions.
> 2020-01-22T18:11:14.798+0000 I  CONTROL  [signalProcessingThread] Shutting down free monitoring
> 2020-01-22T18:11:14.798+0000 I  FTDC     [signalProcessingThread] Shutting down full-time diagnostic data capture
> 2020-01-22T18:11:14.800+0000 I  STORAGE  [signalProcessingThread] Deregistering all the collections
> 2020-01-22T18:11:14.800+0000 I  STORAGE  [signalProcessingThread] Timestamp monitor shutting down
> 2020-01-22T18:11:14.801+0000 I  STORAGE  [signalProcessingThread] WiredTigerKVEngine shutting down
> 2020-01-22T18:11:14.801+0000 I  STORAGE  [signalProcessingThread] Shutting down session sweeper thread
> 2020-01-22T18:11:14.801+0000 I  STORAGE  [signalProcessingThread] Finished shutting down session sweeper thread
> 2020-01-22T18:11:14.802+0000 I  STORAGE  [signalProcessingThread] Shutting down journal flusher thread
> 2020-01-22T18:11:14.825+0000 I  STORAGE  [signalProcessingThread] Finished shutting down journal flusher thread
> 2020-01-22T18:11:14.825+0000 I  STORAGE  [signalProcessingThread] Shutting down checkpoint thread
> 2020-01-22T18:11:14.825+0000 I  STORAGE  [signalProcessingThread] Finished shutting down checkpoint thread
> 2020-01-22T18:11:14.852+0000 I  STORAGE  [signalProcessingThread] shutdown: removing fs lock...
> 2020-01-22T18:11:14.852+0000 I  CONTROL  [signalProcessingThread] now exiting
> 2020-01-22T18:11:14.853+0000 I  CONTROL  [signalProcessingThread] shutting down with code:0
> 
> MongoDB init process complete; ready for start up.
> 
> 2020-01-22T18:11:15.872+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
> 2020-01-22T18:11:15.877+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=ebcd45e1c90f
> 2020-01-22T18:11:15.877+0000 I  CONTROL  [initandlisten] db version v4.2.1
> 2020-01-22T18:11:15.877+0000 I  CONTROL  [initandlisten] git version: edf6d45851c0b9ee15548f0f847df141764a317e
> 2020-01-22T18:11:15.877+0000 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
> 2020-01-22T18:11:15.877+0000 I  CONTROL  [initandlisten] allocator: tcmalloc
> 2020-01-22T18:11:15.877+0000 I  CONTROL  [initandlisten] modules: none
> 2020-01-22T18:11:15.877+0000 I  CONTROL  [initandlisten] build environment:
> 2020-01-22T18:11:15.877+0000 I  CONTROL  [initandlisten]     distmod: ubuntu1804
> 2020-01-22T18:11:15.877+0000 I  CONTROL  [initandlisten]     distarch: x86_64
> 2020-01-22T18:11:15.877+0000 I  CONTROL  [initandlisten]     target_arch: x86_64
> 2020-01-22T18:11:15.877+0000 I  CONTROL  [initandlisten] options: { net: { bindIp: "*" }, security: { authorization: "enabled" } }
> 2020-01-22T18:11:15.878+0000 I  STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
> 2020-01-22T18:11:15.878+0000 I  STORAGE  [initandlisten]
> 2020-01-22T18:11:15.878+0000 I  STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
> 2020-01-22T18:11:15.878+0000 I  STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
> 2020-01-22T18:11:15.878+0000 I  STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=5350M,cache_overflow=(file_max=0M),session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress],
> 2020-01-22T18:11:16.692+0000 I  STORAGE  [initandlisten] WiredTiger message [1579716676:692706][1:0x7fd576ac7b00], txn-recover: Recovering log 1 through 2
> 2020-01-22T18:11:16.794+0000 I  STORAGE  [initandlisten] WiredTiger message [1579716676:794316][1:0x7fd576ac7b00], txn-recover: Recovering log 2 through 2
> 2020-01-22T18:11:16.960+0000 I  STORAGE  [initandlisten] WiredTiger message [1579716676:960797][1:0x7fd576ac7b00], txn-recover: Main recovery loop: starting at 1/30720 to 2/256
> 2020-01-22T18:11:17.104+0000 I  STORAGE  [initandlisten] WiredTiger message [1579716677:104205][1:0x7fd576ac7b00], txn-recover: Recovering log 1 through 2
> 2020-01-22T18:11:17.182+0000 I  STORAGE  [initandlisten] WiredTiger message [1579716677:182102][1:0x7fd576ac7b00], txn-recover: Recovering log 2 through 2
> 2020-01-22T18:11:17.256+0000 I  STORAGE  [initandlisten] WiredTiger message [1579716677:256115][1:0x7fd576ac7b00], txn-recover: Set global recovery timestamp: (0,0)
> 2020-01-22T18:11:17.265+0000 I  RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
> 2020-01-22T18:11:17.270+0000 I  STORAGE  [initandlisten] Timestamp monitor starting
> 2020-01-22T18:11:17.276+0000 I  SHARDING [initandlisten] Marking collection local.system.replset as collection version: <unsharded>
> 2020-01-22T18:11:17.277+0000 I  STORAGE  [initandlisten] Flow Control is enabled on this deployment.
> 2020-01-22T18:11:17.277+0000 I  SHARDING [initandlisten] Marking collection admin.system.roles as collection version: <unsharded>
> 2020-01-22T18:11:17.277+0000 I  SHARDING [initandlisten] Marking collection admin.system.version as collection version: <unsharded>
> 2020-01-22T18:11:17.279+0000 I  SHARDING [initandlisten] Marking collection local.startup_log as collection version: <unsharded>
> 2020-01-22T18:11:17.279+0000 I  FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
> 2020-01-22T18:11:17.282+0000 I  SHARDING [LogicalSessionCacheRefresh] Marking collection config.system.sessions as collection version: <unsharded>
> 2020-01-22T18:11:17.282+0000 I  NETWORK  [initandlisten] Listening on /tmp/mongodb-27017.sock
> 2020-01-22T18:11:17.282+0000 I  NETWORK  [initandlisten] Listening on 0.0.0.0
> 2020-01-22T18:11:17.282+0000 I  SHARDING [LogicalSessionCacheReap] Marking collection config.transactions as collection version: <unsharded>
> 2020-01-22T18:11:17.282+0000 I  NETWORK  [initandlisten] waiting for connections on port 27017
> 2020-01-22T18:11:18.000+0000 I  SHARDING [ftdc] Marking collection local.oplog.rs as collection version: <unsharded>

I can see users creation in db.
I don't know if it is enought

**Comment by tomtom30** [comment]
here is the log from alexa-web (red) : trying to reconnect to mqtt

> warn: [MQTT] MQTT reconnect event {"timestamp":"2020-01-22T19:28:06.087Z"}
> warn: [MQTT] MQTT reconnect event {"timestamp":"2020-01-22T19:28:07.090Z"}
> warn: [MQTT] MQTT reconnect event {"timestamp":"2020-01-22T19:28:08.094Z"}
> warn: [MQTT] MQTT reconnect event {"timestamp":"2020-01-22T19:28:09.096Z"}
> warn: [MQTT] MQTT reconnect event {"timestamp":"2020-01-22T19:28:10.100Z"}
> warn: [MQTT] MQTT reconnect event {"timestamp":"2020-01-22T19:28:11.102Z"}
> warn: [MQTT] MQTT reconnect event {"timestamp":"2020-01-22T19:28:12.106Z"}
> warn: [MQTT] MQTT reconnect event {"timestamp":"2020-01-22T19:28:13.108Z"}
> warn: [MQTT] MQTT reconnect event {"timestamp":"2020-01-22T19:28:14.111Z"}
> warn: [MQTT] MQTT reconnect event {"timestamp":"2020-01-22T19:28:15.114Z"}
> warn: [MQTT] MQTT reconnect event {"timestamp":"2020-01-22T19:28:16.117Z"}
> warn: [MQTT] MQTT reconnect event {"timestamp":"2020-01-22T19:28:17.120Z"}
> warn: [MQTT] MQTT reconnect event {"timestamp":"2020-01-22T19:28:18.124Z"}
> warn: [MQTT] MQTT reconnect event {"timestamp":"2020-01-22T19:28:19.126Z"}
> warn: [MQTT] MQTT reconnect event {"timestamp":"2020-01-22T19:28:20.130Z"}
> warn: [MQTT] MQTT reconnect event {"timestamp":"2020-01-22T19:28:21.133Z"}
> warn: [MQTT] MQTT reconnect event {"timestamp":"2020-01-22T19:28:22.136Z"}
> warn: [MQTT] MQTT reconnect event {"timestamp":"2020-01-22T19:28:23.139Z"}
> warn: [MQTT] MQTT reconnect event {"timestamp":"2020-01-22T19:28:24.142Z"}
> warn: [MQTT] MQTT reconnect event {"timestamp":"2020-01-22T19:28:25.145Z"}
> warn: [MQTT] MQTT reconnect event {"timestamp":"2020-01-22T19:28:26.148Z"}
> warn: [MQTT] MQTT reconnect event {"timestamp":"2020-01-22T19:28:27.151Z"}

**Comment by tomtom30** [comment]
If mongodb-accounts.sh just create account ,which container fill the database?
Can you help me to understand ?
Really thanks

**Comment by tomtom30** [comment]
Ok I have found my mistake in docker-compose, I have forget the network in alexa-web.
Thanks for your help
