### ISSUE TITLE
Re-connecting to Alexa/ Google Home Skill MQTT server

### ISSUE THREAD

**Issue by wossix** [coldfire84/node-red-alexa-home-skill-v3-web#98]
**Describe the bug**
[warn] [alexa-smart-home-v3-conf:ce9856fe.6bad7] Re-connecting to Alexa/ Google Home Skill MQTT server: mq-red.cb-net.co.uk, account username:*****

Since round about an hour I am receiving this warning and can not connect.
Is there any issue with the server/service?

Thank you.

Cheers

**Comment by coldfire84** [comment]
There is a bug that has come up with the new MQTT service, I have a workaround that is just building.

**Comment by coldfire84** [comment]
Error on MQTT service as below:
```
panic: runtime error: index out of range [2] with length 1

goroutine 17 [running, locked to thread]:
github.com/iegomez/mosquitto-go-auth/common.HashCompare(0x55ce01786040, 0xe, 0xc000420180, 0x20, 0x55ce00f68ac0, 0x5, 0x0)
        /app/mosquitto-go-auth/common/utils.go:137 +0x3b2
github.com/iegomez/mosquitto-go-auth/backends.Mongo.GetUser(0x55ce00f6a830, 0x7, 0x55ce00f66e60, 0x5, 0x55ce00f67210, 0x9, 0x55ce00f6a890, 0x22, 0x55ce00f68ac0, 0x5, ...)
        /app/mosquitto-go-auth/backends/mongo.go:151 +0x2a6
main.CheckBackendsAuth(0x55ce01785fe0, 0xa, 0x55ce01786040, 0xe, 0xc0001c0000)
        /app/mosquitto-go-auth/go-auth.go:672 +0x20f
main.AuthUnpwdCheck(0x55ce01785fe0, 0xa, 0x55ce01786040, 0xe, 0x28)
        /app/mosquitto-go-auth/go-auth.go:494 +0x481
main._cgoexpwrap_ebd210e0adf1_AuthUnpwdCheck(0x55ce01785fe0, 0xa, 0x55ce01786040, 0xe, 0xf)
        _cgo_gotypes.go:57 +0x4b
Aborted (core dumped)
```
Modified and re-deployed the MQTT service code as-per: https://github.com/coldfire84/mosquitto-go-auth/commit/216dd43b493372020d13eed137c13168a872adc0

Service looks stable at present.

**Comment by coldfire84** [comment]
No further issues with MQTT service.

**Comment by wossix** [comment]
@coldfire84, I am sorry but I do think the issue is back again. :-/

sorry - looks good again. Do think it was an issue on my system. cheers.

**Comment by coldfire84** [comment]
MQTT broker has been up 19 hours, whereas yesterday it was repeatedly crashing/ restarting.
